var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,f){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,f):$jscomp.polyfillUnisolated(a,b,c,f))};
$jscomp.polyfillUnisolated=function(a,b,c,f){c=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var e=a[f];if(!(e in c))return;c=c[e]}a=a[a.length-1];f=c[a];b=b(f);b!=f&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,f){var e=a.split(".");a=1===e.length;f=e[0];f=!a&&f in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var g=0;g<e.length-1;g++){var d=e[g];if(!(d in f))return;f=f[d]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?f[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&(c=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+c+"$"+e),$jscomp.defineProperty(f,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};
$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){var c=$jscomp.makeIterator(a),f=c.next();$jscomp.generator.ensureIteratorResultIsObject_(f);if(f.done)this.yieldResult=f.value,this.nextAddress=b;else return this.yieldAllIterator_=c,this.yield(f.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var c=this.finallyContexts_.splice(b||0)[0];if(c=this.abruptCompletion_=this.abruptCompletion_||c){if(c.isException)return this.jumpToErrorHandler_();void 0!=c.jumpTo&&this.finallyAddress_<c.jumpTo?(this.nextAddress=c.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(c){return{value:c,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var f=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(f);if(!f.done)return this.context_.stop_(),f;var e=f.value}catch(g){return this.context_.yieldAllIterator_=null,this.context_.throw_(g),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var c=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(c,a.prototype);return c};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(f){return a.next(f)}function c(f){return a["throw"](f)}return new Promise(function(f,e){function g(d){d.done?f(d.value):Promise.resolve(d.value).then(b,c).then(g,e)}g(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.initSymbol=function(){};$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(g,d){this.$jscomp$symbol$id_=g;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:d})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",f=0,e=function(g){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(g||"")+"_"+f++,g)};return e},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var f=$jscomp.global[b[c]];"function"===typeof f&&"function"!=typeof f.prototype[a]&&$jscomp.defineProperty(f.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(d){return d instanceof e?d:new e(function(k,m){k(d)})}if(a&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&"undefined"===typeof $jscomp.global.PromiseRejectionEvent)||!$jscomp.global.Promise||-1===$jscomp.global.Promise.toString().indexOf("[native code]")))return a;b.prototype.asyncExecute=function(d){if(null==this.batch_){this.batch_=[];var k=this;this.asyncExecuteFunction(function(){k.executeBatch_()})}this.batch_.push(d)};
var f=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(d){f(d,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var d=this.batch_;this.batch_=[];for(var k=0;k<d.length;++k){var m=d[k];d[k]=null;try{m()}catch(n){this.asyncThrow_(n)}}}this.batch_=null};b.prototype.asyncThrow_=function(d){this.asyncExecuteFunction(function(){throw d;})};var e=function(d){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var k=this.createResolveAndReject_();
try{d(k.resolve,k.reject)}catch(m){k.reject(m)}};e.prototype.createResolveAndReject_=function(){function d(n){return function(q){m||(m=!0,n.call(k,q))}}var k=this,m=!1;return{resolve:d(this.resolveTo_),reject:d(this.reject_)}};e.prototype.resolveTo_=function(d){if(d===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof e)this.settleSameAsPromise_(d);else{a:switch(typeof d){case "object":var k=null!=d;break a;case "function":k=!0;break a;default:k=!1}k?this.resolveToNonPromiseObj_(d):
this.fulfill_(d)}};e.prototype.resolveToNonPromiseObj_=function(d){var k=void 0;try{k=d.then}catch(m){this.reject_(m);return}"function"==typeof k?this.settleSameAsThenable_(k,d):this.fulfill_(d)};e.prototype.reject_=function(d){this.settle_(2,d)};e.prototype.fulfill_=function(d){this.settle_(1,d)};e.prototype.settle_=function(d,k){if(0!=this.state_)throw Error("Cannot settle("+d+", "+k+"): Promise already settled in state"+this.state_);this.state_=d;this.result_=k;2===this.state_&&this.scheduleUnhandledRejectionCheck_();
this.executeOnSettledCallbacks_()};e.prototype.scheduleUnhandledRejectionCheck_=function(){var d=this;f(function(){if(d.notifyUnhandledRejection_()){var k=$jscomp.global.console;"undefined"!==typeof k&&k.error(d.result_)}},1)};e.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var d=$jscomp.global.CustomEvent,k=$jscomp.global.Event,m=$jscomp.global.dispatchEvent;if("undefined"===typeof m)return!0;"function"===typeof d?d=new d("unhandledrejection",{cancelable:!0}):
"function"===typeof k?d=new k("unhandledrejection",{cancelable:!0}):(d=$jscomp.global.document.createEvent("CustomEvent"),d.initCustomEvent("unhandledrejection",!1,!0,d));d.promise=this;d.reason=this.result_;return m(d)};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var d=0;d<this.onSettledCallbacks_.length;++d)g.asyncExecute(this.onSettledCallbacks_[d]);this.onSettledCallbacks_=null}};var g=new b;e.prototype.settleSameAsPromise_=function(d){var k=this.createResolveAndReject_();
d.callWhenSettled_(k.resolve,k.reject)};e.prototype.settleSameAsThenable_=function(d,k){var m=this.createResolveAndReject_();try{d.call(k,m.resolve,m.reject)}catch(n){m.reject(n)}};e.prototype.then=function(d,k){function m(t,l){return"function"==typeof t?function(r){try{n(t(r))}catch(v){q(v)}}:l}var n,q,w=new e(function(t,l){n=t;q=l});this.callWhenSettled_(m(d,n),m(k,q));return w};e.prototype["catch"]=function(d){return this.then(void 0,d)};e.prototype.callWhenSettled_=function(d,k){function m(){switch(n.state_){case 1:d(n.result_);
break;case 2:k(n.result_);break;default:throw Error("Unexpected state: "+n.state_);}}var n=this;null==this.onSettledCallbacks_?g.asyncExecute(m):this.onSettledCallbacks_.push(m);this.isRejectionHandled_=!0};e.resolve=c;e.reject=function(d){return new e(function(k,m){m(d)})};e.race=function(d){return new e(function(k,m){for(var n=$jscomp.makeIterator(d),q=n.next();!q.done;q=n.next())c(q.value).callWhenSettled_(k,m)})};e.all=function(d){var k=$jscomp.makeIterator(d),m=k.next();return m.done?c([]):new e(function(n,
q){function w(r){return function(v){t[r]=v;l--;0==l&&n(t)}}var t=[],l=0;do t.push(void 0),l++,c(m.value).callWhenSettled_(w(t.length-1),q),m=k.next();while(!m.done)})};return e},"es6","es3");$(".erc").html(" (ERC-20)");$(".changenet").each(function(){this.href+="tokensaleclaimtimeref/"});
var contractAddressMain="0xc279cd282504cCB1C7E7D68630d5BdE4615E4d4D",contractAddressTest="0xEc57AD39Dc2Ca30aEA910302011E13c5F2048f6B",contractTokenBuilder1Main="0xA281713f54CdC6af205BaE122bafA9712CB97BdA",contractTokenBuilder1Test="0x040790ED2c404004A5b2DC31D6c799d12D655055",contractTokenBuilder2Main="0xfC36e31c4facD0fbe36af60F2d6079Ba07d59c95",contractTokenBuilder2Test="0xf3c1B97Ba716DD79076369a25036Ba966B3eD284",contractTokenBuilder3Main="0x32D332487C8703D94C46F99E55b12D3BaAB45190",contractTokenBuilder3Test=
"0x32D332487C8703D94C46F99E55b12D3BaAB45190",contractTokenBuilder4Main="0x1A3Bd3b5F46C429D7d06d0B01F6F97D5698Ba1E2",contractTokenBuilder4Test="0xBFFEfDCC6275bd0D6703fCe006bB69e2a06Fb4B6",contractTokenBuilder5Main="0x592173bc112099c812216b62504a20aaeb38c679",contractTokenBuilder5Test="0x34e18d89B43d0Ef859896D54D024072785D8C48f",contractTokenBuilder1,contractTokenBuilder2,contractTokenBuilder3,contractTokenBuilder4,contractTokenBuilder5,builderCost,contractThis,contractThisSign,contractThisToken,contractThisTokenSign,
balanceEth,thisDecimals,thisTokenAddress,thisAddress,thisSymbol,thisUnsold,thisUnsoldQty,available,thisBalance,thisHardcap,maxDecimals=18,dayms=86400,hourms=3600,abi=[{inputs:[],stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"creator",type:"address"},{indexed:!0,internalType:"address",name:"contractAddress",type:"address"}],name:"ContractCreated",type:"event"},{inputs:[],name:"beneficiary",outputs:[{internalType:"address",name:"",type:"address"}],
stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"_newBeneficiary",type:"address"}],name:"changeBeneficiary",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_newcost",type:"uint256"}],name:"changeCost",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"_newOwner",type:"address"}],name:"changeOwner",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"cost",
outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"_tokenAddress",type:"address"},{internalType:"uint256",name:"_rate",type:"uint256"},{internalType:"uint256",name:"_hardcap",type:"uint256"},{internalType:"uint256",name:"_purchaseLimit",type:"uint256"},{internalType:"address",name:"_beneficiary",type:"address"},{internalType:"uint256",name:"_refPercent",type:"uint256"},{internalType:"uint256",name:"_startTime",type:"uint256"},
{internalType:"uint256",name:"_endTime",type:"uint256"},{internalType:"uint256",name:"_claimTime",type:"uint256"},{internalType:"bool",name:"_allow",type:"bool"},{internalType:"uint256",name:"_delay",type:"uint256"}],name:"createTokenSale",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"payable",type:"function"},{inputs:[],name:"myContracts",outputs:[{internalType:"address[]",name:"",type:"address[]"}],stateMutability:"view",type:"function"},{inputs:[],name:"owner",outputs:[{internalType:"address",
name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalBuilt",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"withdraw",outputs:[],stateMutability:"nonpayable",type:"function"}],abiSale=[{inputs:[{internalType:"address",name:"_tokenAddress",type:"address"},{internalType:"uint256",name:"_rate",type:"uint256"},{internalType:"uint256",name:"_hardcap",type:"uint256"},{internalType:"uint256",name:"_purchaseLimit",
type:"uint256"},{internalType:"address",name:"_beneficiary",type:"address"},{internalType:"uint256",name:"_refPercent",type:"uint256"},{internalType:"uint256",name:"_startTime",type:"uint256"},{internalType:"uint256",name:"_endTime",type:"uint256"},{internalType:"uint256",name:"_claimTime",type:"uint256"},{internalType:"bool",name:"_allow",type:"bool"},{internalType:"uint256",name:"_delay",type:"uint256"}],stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,inputs:[{indexed:!1,internalType:"address",
name:"buyer",type:"address"},{indexed:!1,internalType:"uint256",name:"amount",type:"uint256"}],name:"Contribution",type:"event"},{inputs:[{internalType:"bool",name:"_allow",type:"bool"}],name:"allowClaimAfterHC",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"",type:"address"}],name:"balances",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"beneficiary",outputs:[{internalType:"address",
name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"_ref",type:"address"}],name:"buyToken",outputs:[],stateMutability:"payable",type:"function"},{inputs:[],name:"canClaim",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"uint256",name:"_qty",type:"uint256"}],name:"checkAmount",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"uint256",
name:"_payment",type:"uint256"}],name:"checkChange",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"uint256",name:"_payment",type:"uint256"}],name:"checkQty",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"claim",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"claimAfterHCAllowed",outputs:[{internalType:"bool",name:"",type:"bool"}],
stateMutability:"view",type:"function"},{inputs:[],name:"claimTermsFixed",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[],name:"claimTime",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"delay",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"endTime",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",
type:"function"},{inputs:[],name:"ended",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"fixClaimTerms",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"fixHardCap",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"fixPurchaseLimit",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"fixRate",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"fixRefPercent",
outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"fixSaleTime",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"hardCapFixed",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[],name:"hardcap",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"uint256",name:"_delay",type:"uint256"}],name:"lockAfterHC",outputs:[],stateMutability:"nonpayable",
type:"function"},{inputs:[],name:"makeUnpausable",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"myTokens",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"owner",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"pausable",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[],name:"purchaseLimit",
outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"purchaseLimitFixed",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[],name:"rate",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"rateFixed",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",
name:"",type:"address"}],name:"refEarnings",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"refPercent",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"refPercentFixed",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[],name:"refTotal",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",
type:"function"},{inputs:[],name:"remaining",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"_buyer",type:"address"}],name:"remainingLimit",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"saleOn",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"bool",name:"_on",type:"bool"}],name:"saleOnOff",
outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"saleTimeFixed",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"_newBeneficiary",type:"address"}],name:"setBeneficiary",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_claimTime",type:"uint256"}],name:"setClaimTime",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",
name:"_endTime",type:"uint256"}],name:"setEndTime",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_hardcap",type:"uint256"}],name:"setHardcap",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_amount",type:"uint256"}],name:"setLimit",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"_newOwner",type:"address"}],name:"setOwner",outputs:[],stateMutability:"nonpayable",
type:"function"},{inputs:[{internalType:"uint256",name:"_rate",type:"uint256"}],name:"setRate",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_refPercent",type:"uint256"}],name:"setRefPercent",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_startTime",type:"uint256"}],name:"setStartTime",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"",type:"address"}],
name:"spendings",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"startTime",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"tokenAddress",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"tokenBalance",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],
name:"totalRaised",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalSold",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"unclaimed",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"withdrawBNB",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_quantity",
type:"uint256"}],name:"withdrawTokens",outputs:[],stateMutability:"nonpayable",type:"function"},{stateMutability:"payable",type:"receive"}],abiToken=[{inputs:[{internalType:"string",name:"_name",type:"string"},{internalType:"string",name:"_symbol",type:"string"},{internalType:"uint256",name:"_dec",type:"uint256"},{internalType:"uint256",name:"_supply",type:"uint256"},{internalType:"uint256",name:"_tax1",type:"uint256"},{internalType:"address",name:"_address1",type:"address"},{internalType:"uint256",
name:"_tax2",type:"uint256"},{internalType:"address",name:"_address2",type:"address"},{internalType:"uint256",name:"_deflation",type:"uint256"},{internalType:"uint256",name:"_minSupply",type:"uint256"},{internalType:"address",name:"_owner",type:"address"}],stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"owner",type:"address"},{indexed:!0,internalType:"address",name:"spender",type:"address"},{indexed:!1,internalType:"uint256",name:"value",
type:"uint256"}],name:"Approval",type:"event"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"from",type:"address"},{indexed:!0,internalType:"address",name:"to",type:"address"},{indexed:!1,internalType:"uint256",name:"value",type:"uint256"}],name:"Transfer",type:"event"},{inputs:[],name:"addressTax1",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"addressTax2",outputs:[{internalType:"address",name:"",type:"address"}],
stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"owner",type:"address"},{internalType:"address",name:"spender",type:"address"}],name:"allowance",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"spender",type:"address"},{internalType:"uint256",name:"value",type:"uint256"}],name:"approve",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"nonpayable",type:"function"},
{inputs:[{internalType:"address",name:"owner",type:"address"}],name:"balanceOf",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"burnt",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"decimals",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"deflation",outputs:[{internalType:"uint256",name:"",type:"uint256"}],
stateMutability:"view",type:"function"},{inputs:[],name:"initialSupply",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"minSupply",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"name",outputs:[{internalType:"string",name:"",type:"string"}],stateMutability:"view",type:"function"},{inputs:[],name:"symbol",outputs:[{internalType:"string",name:"",type:"string"}],stateMutability:"view",
type:"function"},{inputs:[],name:"tax1",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"tax2",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalSupply",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalTax1",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},
{inputs:[],name:"totalTax2",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"to",type:"address"},{internalType:"uint256",name:"value",type:"uint256"}],name:"transfer",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"from",type:"address"},{internalType:"address",name:"to",type:"address"},{internalType:"uint256",name:"value",
type:"uint256"}],name:"transferFrom",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"nonpayable",type:"function"}],abiTokenBuilder=[{inputs:[{internalType:"uint256",name:"_cost",type:"uint256"}],stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"oldBeneficiary",type:"address"},{indexed:!0,internalType:"address",name:"newBeneficiary",type:"address"}],name:"BeneficiarySet",type:"event"},{anonymous:!1,inputs:[{indexed:!1,
internalType:"uint256",name:"newCost",type:"uint256"}],name:"Cost",type:"event"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"oldOwner",type:"address"},{indexed:!0,internalType:"address",name:"newOwner",type:"address"}],name:"OwnerSet",type:"event"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"tokenCreator",type:"address"},{indexed:!0,internalType:"address",name:"tokenAddress",type:"address"},{indexed:!1,internalType:"string",name:"name",type:"string"},{indexed:!1,
internalType:"string",name:"symbol",type:"string"},{indexed:!1,internalType:"uint256",name:"totalSupply",type:"uint256"},{indexed:!1,internalType:"uint8",name:"decimals",type:"uint8"}],name:"TokenCreated",type:"event"},{inputs:[],name:"beneficiary",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"newBeneficiary",type:"address"}],name:"changeBeneficiary",outputs:[],stateMutability:"nonpayable",type:"function"},
{inputs:[{internalType:"uint256",name:"_newcost",type:"uint256"}],name:"changeCost",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"newOwner",type:"address"}],name:"changeOwner",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"cost",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"string",name:"name",type:"string"},{internalType:"string",name:"symbol",type:"string"},
{internalType:"uint256",name:"totalSupply",type:"uint256"},{internalType:"uint8",name:"decimals",type:"uint8"},{internalType:"address",name:"to",type:"address"}],name:"createToken",outputs:[{internalType:"address",name:"tokenAddress",type:"address"}],stateMutability:"payable",type:"function"},{inputs:[{internalType:"address",name:"tokenAddress",type:"address"}],name:"getTokenData",outputs:[{internalType:"string",name:"name",type:"string"},{internalType:"string",name:"symbol",type:"string"},{internalType:"uint256",
name:"totalSupply",type:"uint256"},{internalType:"uint256",name:"decimals",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"myTokens",outputs:[{internalType:"address[]",name:"",type:"address[]"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"",type:"address"},{internalType:"uint256",name:"",type:"uint256"}],name:"mytokens",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"owner",
outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"",type:"address"}],name:"tokens",outputs:[{internalType:"string",name:"name",type:"string"},{internalType:"string",name:"symbol",type:"string"},{internalType:"uint256",name:"totalSupply",type:"uint256"},{internalType:"uint8",name:"decimals",type:"uint8"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalBuilt",outputs:[{internalType:"uint256",name:"",
type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"withdraw",outputs:[],stateMutability:"nonpayable",type:"function"}];
function init(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return contract=new ethers.Contract(contractAddress,abi,provider),contractSign=contract.connect(signer),a.yield(contract.cost(),2);builderCost=a.yieldResult;$("#buildercost").html(ethers.utils.formatEther(builderCost));myAddress&&($("#newbeneficiary").val(myAddress),checkBen());makeTable();a.jumpToEnd()})}
function makeTable(){var a,b,c,f,e,g,d,k,m,n,q,w,t,l,r,v,y,z,u,A;return $jscomp.asyncExecutePromiseGeneratorProgram(function(p){switch(p.nextAddress){case 1:return a="",p.yield(contract.myContracts({from:myAddress}),2);case 2:b=p.yieldResult;if(!(0<b.length)){a="Not found";p.jumpTo(3);break}c=b;f=0;case 4:if(!(f<c.length)){p.jumpTo(3);break}e=c[f];g=new ethers.Contract(e,abiSale,provider);return p.yield(g.tokenAddress(),7);case 7:return d=p.yieldResult,p.yield(g.startTime(),8);case 8:return k=p.yieldResult,
p.yield(g.endTime(),9);case 9:return m=p.yieldResult,p.yield(g.remaining(),10);case 10:return n=p.yieldResult,p.yield(g.checkQty(n),11);case 11:return q=p.yieldResult,p.yield(g.saleOn(),12);case 12:return w=p.yieldResult,p.yield(g.canClaim(),13);case 13:return t=p.yieldResult,p.yield(g.unclaimed(),14);case 14:return l=p.yieldResult,v=new ethers.Contract(d,abiToken,provider),p.yield(v.name(),15);case 15:return y=p.yieldResult,p.yield(v.symbol(),16);case 16:return z=p.yieldResult,p.yield(v.balanceOf(e),
17);case 17:u=p.yieldResult;Date.now()>1E3*Number(m)||0==Number(q)?(r="Finished",r=t?r+"<br>Claim unlocked":r+"<br>Claim locked",Number(u)<Number(l)&&(r+='<br><span class="err">Add tokens</span>')):Date.now()<1E3*Number(k)?(r="Upcoming",Number(u)<Number(q)&&(r+='<br><span class="err">Add tokens</span>')):Date.now()>1E3*Number(k)&&Date.now()<1E3*Number(m)&&(r=w?"Active":'<span class="err">Paused</span>',Number(u)<Number(q)&&(r+=' <span class="err">Add tokens</span>'));A=Number(f+1);a=a+'<div class="salerow" title="Click to open admin panel" onclick="admin(\''+
e+'\')"><div class="saleno">'+A+'</div><div class="saleaddress">'+e+'</div><div class="saletoken">'+y+"("+z+')</div><div class="salestatus">'+r+"</div>";a+="</div>";f++;p.jumpTo(4);break;case 3:$("#mycontr").html(a),p.jumpToEnd()}})}
$("#mytokens").click(function(){var a,b,c,f,e,g,d,k,m,n,q,w,t;return $jscomp.asyncExecutePromiseGeneratorProgram(function(l){switch(l.nextAddress){case 1:return $("#mytoks").show(),curnet==mainnet||curnet==mainnetAlt?(contractTokenBuilder1=contractTokenBuilder1Main,contractTokenBuilder2=contractTokenBuilder2Main,contractTokenBuilder3=contractTokenBuilder3Main,contractTokenBuilder4=contractTokenBuilder4Main,contractTokenBuilder5=contractTokenBuilder5Main):curnet==testnet&&(contractTokenBuilder1=contractTokenBuilder1Test,
contractTokenBuilder2=contractTokenBuilder2Test,contractTokenBuilder3=contractTokenBuilder3Test,contractTokenBuilder4=contractTokenBuilder4Test,contractTokenBuilder5=contractTokenBuilder5Test),contractToken1=new ethers.Contract(contractTokenBuilder1,abiTokenBuilder,provider),contractToken2=new ethers.Contract(contractTokenBuilder2,abiTokenBuilder,provider),contractToken3=new ethers.Contract(contractTokenBuilder3,abiTokenBuilder,provider),contractToken4=new ethers.Contract(contractTokenBuilder4,abiTokenBuilder,
provider),contractToken5=new ethers.Contract(contractTokenBuilder5,abiTokenBuilder,provider),a="",b=0,l.yield(contractToken1.myTokens({from:myAddress}),2);case 2:c=l.yieldResult;if(c==[]){l.jumpTo(3);break}f=c;e=0;case 4:if(!(e<f.length)){l.jumpTo(3);break}g=f[e];d=new ethers.Contract(g,abiToken,provider);return l.yield(d.name(),7);case 7:return k=l.yieldResult,l.yield(d.symbol(),8);case 8:m=l.yieldResult;b=Number(b+1);a=a+"<tr><td>"+b+'</td><td><a title="View on explorer" target="_blank" href="'+
tracker+"token/"+g+'">'+g+"</a></td><td>"+k+"</td><td>"+m+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+g+"')\">choose</span></td>";a+="</tr>";e++;l.jumpTo(4);break;case 3:return l.yield(contractToken2.myTokens({from:myAddress}),9);case 9:n=l.yieldResult;if(n==[]){l.jumpTo(10);break}f=n;e=0;case 11:if(!(e<f.length)){l.jumpTo(10);break}g=f[e];d=new ethers.Contract(g,abiToken,provider);return l.yield(d.name(),14);case 14:return k=l.yieldResult,l.yield(d.symbol(),15);
case 15:m=l.yieldResult;b=Number(b+1);a=a+"<tr><td>"+b+'</td><td><a title="View on explorer" target="_blank" href="'+tracker+"token/"+g+'">'+g+"</a></td><td>"+k+"</td><td>"+m+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+g+"')\">choose</span></td>";a+="</tr>";e++;l.jumpTo(11);break;case 10:return l.yield(contractToken3.myTokens({from:myAddress}),16);case 16:q=l.yieldResult;if(q==[]){l.jumpTo(17);break}f=q;e=0;case 18:if(!(e<f.length)){l.jumpTo(17);break}g=f[e];d=
new ethers.Contract(g,abiToken,provider);return l.yield(d.name(),21);case 21:return k=l.yieldResult,l.yield(d.symbol(),22);case 22:m=l.yieldResult;b=Number(b+1);a=a+"<tr><td>"+b+'</td><td><a title="View on explorer" target="_blank" href="'+tracker+"token/"+g+'">'+g+"</a></td><td>"+k+"</td><td>"+m+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+g+"')\">choose</span></td>";a+="</tr>";e++;l.jumpTo(18);break;case 17:return l.yield(contractToken4.myTokens({from:myAddress}),
23);case 23:w=l.yieldResult;if(w==[]){l.jumpTo(24);break}f=w;e=0;case 25:if(!(e<f.length)){l.jumpTo(24);break}g=f[e];d=new ethers.Contract(g,abiToken,provider);return l.yield(d.name(),28);case 28:return k=l.yieldResult,l.yield(d.symbol(),29);case 29:m=l.yieldResult;b=Number(b+1);a=a+"<tr><td>"+b+'</td><td><a title="View on explorer" target="_blank" href="'+tracker+"token/"+g+'">'+g+"</a></td><td>"+k+"</td><td>"+m+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+g+"')\">choose</span></td>";
a+="</tr>";e++;l.jumpTo(25);break;case 24:return l.yield(contractToken5.myTokens({from:myAddress}),30);case 30:t=l.yieldResult;if(t==[]){l.jumpTo(31);break}f=t;e=0;case 32:if(!(e<f.length)){l.jumpTo(31);break}g=f[e];d=new ethers.Contract(g,abiToken,provider);return l.yield(d.name(),35);case 35:return k=l.yieldResult,l.yield(d.symbol(),36);case 36:m=l.yieldResult;b=Number(b+1);a=a+"<tr><td>"+b+'</td><td><a title="View on explorer" target="_blank" href="'+tracker+"token/"+g+'">'+g+"</a></td><td>"+k+
"</td><td>"+m+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+g+"')\">choose</span></td>";a+="</tr>";e++;l.jumpTo(32);break;case 31:$("#strHtmlTokens").html(a),l.jumpToEnd()}})});function choose(a){$("#newtknaddress").val(a);$("#mytoks").hide();checkToken()}$("#newtknaddress").on("keyup input",checkToken);
function checkToken(){var a,b,c,f,e;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){switch(g.nextAddress){case 1:$("#tokendata").html("");a=$("#newtknaddress").val();if(""==a||!ethers.utils.isAddress(a))return""==a?$("#tokendata").html(""):$("#tokendata").html('<span class="err">Error: check token address!</span>'),g["return"](!1);$("#errors").html("");g.setCatchFinallyBlocks(3);b=new ethers.Contract(a,abiToken,provider);return g.yield(b.name(),5);case 5:return c=g.yieldResult,g.yield(b.symbol(),
6);case 6:f=g.yieldResult;if(c&&f)return $("#tokendata").html('<span style="color: green">'+c+" ("+f+")</span>"),g["return"](!0);$("#tokendata").html('<span class="err">Error: check token address!</span>');return g["return"](!1);case 3:return e=g.enterCatchBlock(),console.log(e),$("#tokendata").html('<span class="err">Error: check token address!</span>'),g["return"](!1)}})}$("#newstartdate").on("keyup input",checkTime);$("#newenddate").on("keyup input",checkTime);
function checkTime(){$("#duration").html("");var a=new Date($("#newstartdate").val()),b=new Date($("#newenddate").val());if(a&&b){if(b>=a&&b>=Date.now())return a=Number(b)-Number(a),$("#duration").html('<span style="color:green">Duration: '+dhm(a)+"</span>"),!0;b>=a&&b<Date.now()?$("#duration").html('<span class="err">End date must be in the future!</span>'):b<a&&b>Date.now()?$("#duration").html('<span class="err">End date must be later than start date!</span>'):b<a&&b<Date.now()?$("#duration").html('<span class="err">End date must be later than start date and in the future!</span>'):
$("#duration").html("");return!1}$("#duration").html("");return!1}function dhm(a){days=Math.floor(a/864E5);daysms=a%864E5;hours=Math.floor(daysms/36E5);hoursms=a%36E5;minutes=Math.floor(hoursms/6E4);minutesms=a%6E4;return days+" days "+hours+" hours "+minutes+" minutes"}$("#afterend").on("change",function(){$("#afterend").is(":checked")?$("#newunlockdate").hide():$("#newunlockdate").show()});$("#unlimited").on("change",function(){$("#unlimited").is(":checked")?$("#limits").hide():$("#limits").show()});
$("#newbeneficiary").on("keyup input",checkBen);function checkBen(){$("#isben").html("");var a=$("#newbeneficiary").val();if(a&&""!=a){if(ethers.utils.isAddress(a))return a==myAddress?$("#isben").html('<span style="color:green">Beneficiary is you</span>'):$("#isben").html(""),!0;$("#isben").html('<span class="err">Please check beneficiary address!</span>');return!1}$("#isben").html("");return!1}$("#benme").click(function(){myAddress&&($("#newbeneficiary").val(myAddress),checkBen())});
function admin(a){var b,c,f,e,g,d,k,m,n,q,w,t,l,r,v,y,z,u,A,p,F,G,C,D,H,I,B,J,K,L,M,N,O,P,Q,R,E,x;return $jscomp.asyncExecutePromiseGeneratorProgram(function(h){switch(h.nextAddress){case 1:return $("#admin").show(),$("#todo").html(""),$("#thisAddr").html(a),$(".uiAddr").html(a),$("#uiAddrLnk").html(tracker+"address/"+a),$("#thisSaleAddress").html(a),$("#thisSaleAddress").attr("href",tracker+"address/"+a),$("#thisSaleAddress2").html(a),$("#thisSaleAddress2").attr("href",tracker+"address/"+a),thisAddress=
a,contractThis=new ethers.Contract(a,abiSale,provider),contractThisSign=contractThis.connect(signer),h.yield(contractThis.tokenAddress(),2);case 2:return thisTokenAddress=h.yieldResult,$("#thisTokenAddress").html(thisTokenAddress),$("#thisTokenAddress").attr("href",tracker+"token/"+thisTokenAddress),$(".tokenAddressUI").html(thisTokenAddress),$("#tokenAddressUIlnk").html(tracker+"token/"+thisTokenAddress),contractThisToken=new ethers.Contract(thisTokenAddress,abiToken,provider),contractThisTokenSign=
contractThisToken.connect(signer),h.yield(contractThisToken.name(),3);case 3:return b=h.yieldResult,$("#thisName").html(b),$("#tokenNameUI").html(b),h.yield(contractThisToken.symbol(),4);case 4:return thisSymbol=h.yieldResult,$(".thisSymbol").html(thisSymbol),h.yield(contractThisToken.decimals(),5);case 5:return thisDecimals=h.yieldResult,$("#thisDec").html(Number(thisDecimals)),$("#tokenDecimalsUI").html(Number(thisDecimals)),h.yield(contractThisToken.totalSupply(),6);case 6:return c=h.yieldResult,
$("#tokenSupplyUI").html(Number(ethers.utils.formatUnits(c,thisDecimals))),h.yield(contractThisToken.balanceOf(thisAddress),7);case 7:return f=h.yieldResult,$("#tokenbalance").html(Number(ethers.utils.formatUnits(f,thisDecimals))),h.yield(contractThis.owner(),8);case 8:return e=h.yieldResult,$("#thisOwner").html(e),h.yield(contractThis.beneficiary(),9);case 9:return g=h.yieldResult,$("#thisBen").html(g),h.yield(contractThis.rate(),10);case 10:return d=h.yieldResult,k=ethers.utils.formatUnits(d,thisDecimals),
$("#thisRate").html(k),m=1/Number(k),$("#thisPrice").html(m),h.yield(contractThis.hardcap(),11);case 11:return thisHardcap=h.yieldResult,$(".thisHardcap").html(ethers.utils.formatEther(thisHardcap)),h.yield(contractThis.checkQty(thisHardcap),12);case 12:return n=h.yieldResult,$(".thisQty").html(ethers.utils.formatUnits(n,thisDecimals)),h.yield(contractThis.purchaseLimit(),13);case 13:return q=h.yieldResult,$("#thisMax").html(ethers.utils.formatEther(q)),h.yield(contractThis.refPercent(),14);case 14:return w=
h.yieldResult,$("#thisRef").html(Number(w)/10),h.yield(contractThis.refTotal(),15);case 15:return t=h.yieldResult,$("#thisRefTotal").html(ethers.utils.formatEther(t)),h.yield(contractThis.totalSold(),16);case 16:return l=h.yieldResult,$("#thisSold").html(ethers.utils.formatUnits(l,thisDecimals)),h.yield(contractThis.totalRaised(),17);case 17:return r=h.yieldResult,$("#thisRaised").html(ethers.utils.formatEther(r)),h.yield(contractThis.remaining(),18);case 18:return v=h.yieldResult,$("#thisRemaining").html(ethers.utils.formatEther(v)),
$("#progress").attr("max",thisHardcap),$("#progress").attr("value",r),h.yield(contractThis.checkQty(v),19);case 19:return thisUnsoldQty=h.yieldResult,$("#thisUnsoldQty").html(ethers.utils.formatUnits(thisUnsoldQty,thisDecimals)),h.yield(provider.getBalance(a),20);case 20:return thisBalance=h.yieldResult,available=ethers.utils.formatEther(thisBalance),$("#thisBalance").html(available),h.yield(contractThis.startTime(),21);case 21:return y=h.yieldResult,z=new Date(1E3*Number(y)),$("#thisStart").html(z),
h.yield(contractThis.endTime(),22);case 22:return u=h.yieldResult,A=new Date(1E3*Number(u)),$("#thisEnd").html(A),p=Number(A)-Number(z),$("#thisDuration").html(dhm(p)),h.yield(contractThis.claimTime(),23);case 23:return F=h.yieldResult,G=new Date(1E3*Number(F)),$("#thisClaim").html(G),h.yield(contractThis.claimAfterHCAllowed(),24);case 24:return C=h.yieldResult,h.yield(contractThis.delay(),25);case 25:return D=h.yieldResult,C?(0<D?$("#thisClaimAfterHC").html("Can be claimed after hardcap is reached +"+
dhm(1E3*Number(D))):$("#thisClaimAfterHC").html("Can be claimed immediately after hardcap is reached"),$("#allowClaim").hide(),$("#disallowClaim").show()):($("#thisClaimAfterHC").html("Can be claimed only when unlock time comes"),$("#allowClaim").show(),$("#disallowClaim").hide()),h.yield(contractThis.ended(),26);case 26:return H=h.yieldResult,I=new Date(1E3*Number(H)),$("#endedUI").html(I),h.yield(contractThis.unclaimed(),27);case 27:return B=h.yieldResult,$("#thisUnclaimed").html(ethers.utils.formatUnits(B,
thisDecimals)),J=Number(f)-Number(B),$("#availableTok").html(ethers.utils.formatUnits(J,thisDecimals)),h.yield(contractThis.canClaim(),28);case 28:return(K=h.yieldResult)?$("#canClaim").html('<span style="color:green">Tokens are unlocked and can be claimed</span>'):$("#canClaim").html('<span style="color:red">Tokens are locked</span>'),h.yield(contractThis.hardCapFixed(),29);case 29:return(L=h.yieldResult)?($("#hardCapFixed").html('<span style="color:red">Hardcap is fixed and can not be changed</span>'),
$("#fixHardCap").hide(),$("#admHardcap").hide()):($("#hardCapFixed").html('<span style="color:green">Hardcap can be changed</span>'),$("#fixHardCap").show(),$("#admHardcap").show()),h.yield(contractThis.purchaseLimitFixed(),30);case 30:return(M=h.yieldResult)?($("#purchaseLimitFixed").html('<span style="color:red">Purchase limit is fixed and can not be changed</span>'),$("#fixPurchaseLimit").hide(),$("#admMax").hide()):($("#purchaseLimitFixed").html('<span style="color:green">Purchase limit can be changed</span>'),
$("#fixPurchaseLimit").show(),$("#admMax").show()),h.yield(contractThis.rateFixed(),31);case 31:return(N=h.yieldResult)?($("#rateFixed").html('<span style="color:red">Rate is fixed and can not be changed</span>'),$("#fixRate").hide(),$("#admRate").hide()):($("#rateFixed").html('<span style="color:green">Rate can be changed</span>'),$("#fixRate").show(),$("#admRate").show()),h.yield(contractThis.refPercentFixed(),32);case 32:return(O=h.yieldResult)?($("#refPercentFixed").html('<span style="color:red">Referral commission is fixed and can not be changed</span>'),
$("#fixRefPercent").hide(),$("#admRef").hide()):($("#refPercentFixed").html('<span style="color:green">Referral commission can be changed</span>'),$("#fixRefPercent").show(),$("#admRef").show()),h.yield(contractThis.saleTimeFixed(),33);case 33:return(P=h.yieldResult)?($("#saleTimeFixed").html('<span style="color:red">Sale time is fixed and can not be changed</span>'),$("#fixSaleTime").hide(),$(".admTime").hide()):($("#saleTimeFixed").html('<span style="color:green">Sale time can be changed</span>'),
$("#fixSaleTime").show(),$(".admTime").show()),h.yield(contractThis.claimTermsFixed(),34);case 34:return(Q=h.yieldResult)?($("#claimTermsFixed").html('<span style="color:red">Terms of token claim is fixed and can not be changed</span>'),$("#fixClaimTerms").hide(),$("#admClaim").hide()):($("#claimTermsFixed").html('<span style="color:green">Terms of token claim can be changed</span>'),$("#fixClaimTerms").show(),$("#admClaim").show()),h.yield(contractThis.pausable(),35);case 35:return(R=h.yieldResult)?
($("#pausable").html('<span style="color:green">The contract is pausable</span>'),$("#makeUnpausable").show(),$("#admPause").show()):($("#pausable").html('<span style="color:red">Contract can not be paused</span>'),$("#makeUnpausable").hide(),$("#admPause").hide()),h.yield(contractThis.saleOn(),36);case 36:(E=h.yieldResult)?($("#saleOn").hide(),$("#saleOff").show()):($("#saleOn").show(),$("#saleOff").hide()),Date.now()>1E3*Number(u)||0==Number(thisUnsoldQty)?(x="Finished",x=C?x+"<br>Claim unlocked":
x+"<br>Claim locked",Number(f)<Number(B)&&(x+='<br><span class="err">Add tokens to sale contract</span>')):Date.now()<1E3*Number(y)?(x="Upcoming",Number(f)<Number(thisUnsoldQty)&&(x+='<br><span class="err">Add tokens to sale contract</span>'),E||(x+='<br><span class="err">Paused</span>')):Date.now()>1E3*Number(y)&&Date.now()<1E3*Number(u)&&(x=E?"Active":'<span class="err">Paused</span>',Number(f)<Number(thisUnsoldQty)&&(x+=' <span class="err">Add tokens to sale contract</span>')),$("#thisStatus").html(x),
curnet==testnet?($("#istest").html("true"),$("#switchbtnid").html("addTestMATIC"),$("#switchbtn").html("Polygon (MATIC) Mumbai Testnet")):($("#istest").html("false"),$("#switchbtnid").html("addMainMATIC"),$("#switchbtn").html("Polygon (MATIC) Mainnet")),getQR(a),h.jumpToEnd()}})}$("#setnewrate").click(setRate);
function setRate(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return(a=$("#thisnewrate").val())?b.yield(contractThisSign.setRate(String(ethers.utils.parseUnits(a,thisDecimals))),3):b.jumpTo(0);if(4!=b.nextAddress)return tx=b.yieldResult,b.yield(tx.wait(),4);admin(thisAddress);b.jumpToEnd()})}$("#setnewhc").click(setHardcap);
function setHardcap(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return(a=$("#thisnewhc").val())?b.yield(contractThisSign.setHardcap(String(ethers.utils.parseEther(a))),3):b.jumpTo(0);if(4!=b.nextAddress)return tx=b.yieldResult,b.yield(tx.wait(),4);admin(thisAddress);b.jumpToEnd()})}$("#setnewmax").click(setLimit);
function setLimit(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return(a=$("#thisnewmax").val())?b.yield(contractThisSign.setLimit(String(ethers.utils.parseEther(a))),3):b.jumpTo(0);if(4!=b.nextAddress)return tx=b.yieldResult,b.yield(tx.wait(),4);admin(thisAddress);b.jumpToEnd()})}$("#setnewmax1").click(setLimit1);
function setLimit1(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return(a=thisHardcap)?b.yield(contractThisSign.setLimit(String(a)),3):b.jumpTo(0);if(4!=b.nextAddress)return tx=b.yieldResult,b.yield(tx.wait(),4);admin(thisAddress);b.jumpToEnd()})}$("#setnewstart").click(setStartTime);
function setStartTime(){var a,b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress){a=$("#thisnewstart").val();if(!a)return c.jumpTo(0);b=Date.parse(a);return c.yield(contractThisSign.setStartTime(String(Number(b)/1E3)),3)}if(4!=c.nextAddress)return tx=c.yieldResult,c.yield(tx.wait(),4);admin(thisAddress);c.jumpToEnd()})}$("#setnewend").click(setEndTime);
function setEndTime(){var a,b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress){a=$("#thisnewend").val();if(!a)return c.jumpTo(0);b=Date.parse(a);return c.yield(contractThisSign.setEndTime(String(Number(b)/1E3)),3)}if(4!=c.nextAddress)return tx=c.yieldResult,c.yield(tx.wait(),4);admin(thisAddress);c.jumpToEnd()})}$("#setnewclaim").click(setClaimTime);
function setClaimTime(){var a,b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress){a=$("#thisnewclaim").val();if(!a)return c.jumpTo(0);b=Date.parse(a);return c.yield(contractThisSign.setClaimTime(String(Number(b)/1E3)),3)}if(4!=c.nextAddress)return tx=c.yieldResult,c.yield(tx.wait(),4);admin(thisAddress);c.jumpToEnd()})}$("#allowClaim").click(allowClaim);
function allowClaim(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return a.yield(contractThisSign.allowClaimAfterHC(!0),2);if(3!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),3);admin(thisAddress);a.jumpToEnd()})}$("#disallowClaim").click(disallowClaim);
function disallowClaim(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return a.yield(contractThisSign.allowClaimAfterHC(!1),2);if(3!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),3);admin(thisAddress);a.jumpToEnd()})}$("#setnewdelay").click(lockAfterHC);
function lockAfterHC(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return(a=$("#thisnewdelay").val())?b.yield(contractThisSign.lockAfterHC(String(Number(a)*hourms)),3):b.jumpTo(0);if(4!=b.nextAddress)return tx=b.yieldResult,b.yield(tx.wait(),4);admin(thisAddress);b.jumpToEnd()})}$("#setnewref").click(setRefPercent);
function setRefPercent(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return(a=$("#thisnewref").val())?b.yield(contractThisSign.setRefPercent(String(10*Number(a))),3):b.jumpTo(0);if(4!=b.nextAddress)return tx=b.yieldResult,b.yield(tx.wait(),4);admin(thisAddress);b.jumpToEnd()})}$("#saleOn").click(saleOn);
function saleOn(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return $("#todo").html(""),0<Number(thisUnsoldQty)?a.yield(contractThisSign.saleOnOff(!0),3):($("#todo").html('<span class="err">Hard cap has been reached!</span>'),a.jumpTo(0));if(4!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),4);admin(thisAddress);a.jumpToEnd()})}$("#saleOff").click(saleOff);
function saleOff(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return a.yield(contractThisSign.saleOnOff(!1),2);if(3!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),3);admin(thisAddress);a.jumpToEnd()})}$("#fixHardCap").click(fixHardCap);
function fixHardCap(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return a.yield(contractThisSign.fixHardCap(),2);if(3!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),3);admin(thisAddress);a.jumpToEnd()})}$("#fixPurchaseLimit").click(fixPurchaseLimit);
function fixPurchaseLimit(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return a.yield(contractThisSign.fixPurchaseLimit(),2);if(3!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),3);admin(thisAddress);a.jumpToEnd()})}$("#fixRate").click(fixRate);
function fixRate(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return a.yield(contractThisSign.fixRate(),2);if(3!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),3);admin(thisAddress);a.jumpToEnd()})}$("#fixRefPercent").click(fixRefPercent);
function fixRefPercent(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return a.yield(contractThisSign.fixRefPercent(),2);if(3!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),3);admin(thisAddress);a.jumpToEnd()})}$("#fixSaleTime").click(fixSaleTime);
function fixSaleTime(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return a.yield(contractThisSign.fixSaleTime(),2);if(3!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),3);admin(thisAddress);a.jumpToEnd()})}$("#fixClaimTerms").click(fixClaimTerms);
function fixClaimTerms(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return a.yield(contractThisSign.fixClaimTerms(),2);if(3!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),3);admin(thisAddress);a.jumpToEnd()})}$("#makeUnpausable").click(makeUnpausable);
function makeUnpausable(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return a.yield(contractThisSign.makeUnpausable(),2);if(3!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),3);admin(thisAddress);a.jumpToEnd()})}$("#withdrawTok").click(withdrawTokens);
function withdrawTokens(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return(a=$("#toWithdrawTok").val())?b.yield(contractThisSign.withdrawTokens(String(ethers.utils.parseUnits(a,thisDecimals))),3):b.jumpTo(0);if(4!=b.nextAddress)return tx=b.yieldResult,b.yield(tx.wait(),4);admin(thisAddress);b.jumpToEnd()})}$("#thisnewowner").on("keyup input",checkOwner);
function checkOwner(){$("#checkthisowner").html("");var a=$("#thisnewowner").val();if(a&&""!=a&&ethers.utils.isAddress(a))return $("#checkthisowner").html(""),!0;a&&""!=a&&!ethers.utils.isAddress(a)?$("#checkthisowner").html('<span class="err">Incorrect address!</span>'):$("#checkthisowner").html("");return!1}$("#setnewowner").click(setOwner);
function setOwner(){var a,b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress)return $("#checkthisowner").html(""),a=checkOwner(),b=$("#thisnewowner").val(),a?c.yield(contractThisSign.setOwner(String(b)),3):($("#checkthisowner").html('<span class="err">Incorrect address!</span>'),c.jumpTo(0));if(4!=c.nextAddress)return tx=c.yieldResult,c.yield(tx.wait(),4);admin(thisAddress);c.jumpToEnd()})}$("#thisnewben").on("keyup input",checkThisBen);
function checkThisBen(){$("#checkthisben").html("");var a=$("#thisnewben").val();if(a&&""!=a&&ethers.utils.isAddress(a))return $("#checkthisben").html(""),!0;a&&""!=a&&!ethers.utils.isAddress(a)?$("#checkthisben").html('<span class="err">Incorrect address!</span>'):$("#checkthisben").html("");return!1}$("#setnewben").click(setBen);
function setBen(){var a,b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress)return $("#checkthisben").html(""),a=checkBen(),b=$("#thisnewben").val(),a?c.yield(contractThisSign.setBeneficiary(String(b)),3):($("#checkthisben").html('<span class="err">Incorrect address!</span>'),c.jumpTo(0));if(4!=c.nextAddress)return tx=c.yieldResult,c.yield(tx.wait(),4);admin(thisAddress);c.jumpToEnd()})}
$("#withdrawBnb").click(function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return 0<Number(thisBalance)?a.yield(contractThisSign.withdrawBNB(),3):a.jumpTo(0);if(4!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),4);admin(thisAddress);a.jumpToEnd()})});$("#addToken").click(function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){watchToken(thisTokenAddress,thisSymbol,thisDecimals);a.jumpToEnd()})});
function watchToken(a,b,c){return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){ethereum.request({method:"wallet_watchAsset",params:{type:"ERC20",options:{address:String(a),symbol:String(b),decimals:String(c)}}});f.jumpToEnd()})}
$("#buildbtn").click(function(){var a,b,c,f,e,g,d,k,m,n,q,w,t,l,r,v,y,z;return $jscomp.asyncExecutePromiseGeneratorProgram(function(u){switch(u.nextAddress){case 1:$("#errors").html("");if(!myAddress){u.jumpTo(0);break}return u.yield(checkToken(),3);case 3:a=u.yieldResult;b=checkTime();c=checkBen();f=$("#newrate").val();e=$("#newhardcap").val();g=$("#newmax").val();$("#unlimited").is(":checked")&&(g=e);if(!(a&&b&&c&&f&&0<Number(f)&&10>=Number(f)^18&&e&&0<Number(e)&&g)){checkToken();checkTime();checkBen();
$("#errors").html("Error: fields are empty or incorrect!");u.jumpTo(0);break}$("#errors").html("");v=$("#newtknaddress").val();y=new ethers.Contract(v,abiToken,provider);return u.yield(y.decimals(),5);case 5:return z=u.yieldResult,q=$("#newstartdate").val(),w=Date.parse(q),t=$("#newenddate").val(),l=Date.parse(t),(d=$("#afterend").is(":checked")?l:Date.parse($("#newunlockdate").val()))&&""!=d||(d=l),k=$("#allow").is(":checked")?!0:!1,(m=$("#newafterhc").val())&&""!=m||(m=0),(n=$("#newref").val())&&
""!=n||(n=0),r=$("#newbeneficiary").val(),r&&""!=r||(r=myAddress,$("#newbeneficiary").val(r)),console.log(a,b,c,f,e,g,d,k,m,n,q,t),u.yield(contractSign.createTokenSale(String(v),String(ethers.utils.parseUnits(f,z)),String(ethers.utils.parseEther(e)),String(ethers.utils.parseEther(g)),String(r),String(10*Number(n)),String(Number(w)/1E3),String(Number(l)/1E3),String(Number(d)/1E3),k,String(Number(m)*hourms),{value:builderCost}),6);case 6:return tx=u.yieldResult,u.yield(tx.wait(),7);case 7:init(),u.jumpToEnd()}})});
$("#newrate").on("keyup input",function(){$("#tokenprice").html("");var a=$("#newrate").val();a&&""!=a&&0<Number(a)&&(a=1/Number(a),$("#tokenprice").html('<span style="color: green">1 token = '+Number(a)+" MATIC</span>"));getQty()});$("#newhardcap").on("keyup input",getQty);function getQty(){$("#quantity").html("");var a=$("#newhardcap").val(),b=$("#newrate").val();a&&""!=a&&b&&""!=b&&(a=Number(a)*Number(b),$("#quantity").html('<span style="color: green"> ~ '+Number(a)+"tokens</span>"))}
function getQR(a){a=encodeURIComponent(a);$("#refqr").html('<img style="max-width: 80%" src="https://dappbuilder.org/php/qr.php?data='+a+'">');$("#refd").attr("href","https://dappbuilder.org/php/qr.php?data="+a)}$("#copyaddress").on("click",function(){var a=$("<textarea>");$("body").append(a);a.val($("#thisTokenAddress").html()).select();document.execCommand("copy");a.remove()});
$("#copysaleaddress").on("click",function(){var a=$("<textarea>");$("body").append(a);a.val($("#thisSaleAddress").html()).select();document.execCommand("copy");a.remove()});$("#copysaleaddress2").on("click",function(){var a=$("<textarea>");$("body").append(a);a.val($("#thisSaleAddress2").html()).select();document.execCommand("copy");a.remove()});