var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,e){if(a==Array.prototype||a==Object.prototype)return a;a[b]=e.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var e=a[b];if(e&&e.Math==Math)return e}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var e=$jscomp.propertyToPolyfillSymbol[b];if(null==e)return a[b];e=a[e];return void 0!==e?e:a[b]};
$jscomp.polyfill=function(a,b,e,f){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,e,f):$jscomp.polyfillUnisolated(a,b,e,f))};$jscomp.polyfillUnisolated=function(a,b,e,f){e=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var d=a[f];if(!(d in e))return;e=e[d]}a=a[a.length-1];f=e[a];b=b(f);b!=f&&null!=b&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,e,f){var d=a.split(".");a=1===d.length;f=d[0];f=!a&&f in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var h=0;h<d.length-1;h++){var c=d[h];if(!(c in f))return;f=f[c]}d=d[d.length-1];e=$jscomp.IS_SYMBOL_NATIVE&&"es6"===e?f[d]:null;b=b(e);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:b}):b!==e&&(void 0===$jscomp.propertyToPolyfillSymbol[d]&&(e=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+e+"$"+d),$jscomp.defineProperty(f,$jscomp.propertyToPolyfillSymbol[d],{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(e){}return!1};
$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};
$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){var e=$jscomp.makeIterator(a),f=e.next();$jscomp.generator.ensureIteratorResultIsObject_(f);if(f.done)this.yieldResult=f.value,this.nextAddress=b;else return this.yieldAllIterator_=e,this.yield(f.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,e){e?this.finallyContexts_[e]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var e=this.finallyContexts_.splice(b||0)[0];if(e=this.abruptCompletion_=this.abruptCompletion_||e){if(e.isException)return this.jumpToErrorHandler_();void 0!=e.jumpTo&&this.finallyAddress_<e.jumpTo?(this.nextAddress=e.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(e){return{value:e,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,e){try{var f=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(f);if(!f.done)return this.context_.stop_(),f;var d=f.value}catch(h){return this.context_.yieldAllIterator_=null,this.context_.throw_(h),this.nextStep_()}this.context_.yieldAllIterator_=null;e.call(this.context_,d);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var e=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(e,a.prototype);return e};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(f){return a.next(f)}function e(f){return a["throw"](f)}return new Promise(function(f,d){function h(c){c.done?f(c.value):Promise.resolve(c.value).then(b,e).then(h,d)}h(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.initSymbol=function(){};$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(h,c){this.$jscomp$symbol$id_=h;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:c})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var e="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",f=0,d=function(h){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new b(e+(h||"")+"_"+f++,h)};return d},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),e=0;e<b.length;e++){var f=$jscomp.global[b[e]];"function"===typeof f&&"function"!=typeof f.prototype[a]&&$jscomp.defineProperty(f.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function e(c){return c instanceof d?c:new d(function(g,l){g(c)})}if(a&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&"undefined"===typeof $jscomp.global.PromiseRejectionEvent)||!$jscomp.global.Promise||-1===$jscomp.global.Promise.toString().indexOf("[native code]")))return a;b.prototype.asyncExecute=function(c){if(null==this.batch_){this.batch_=[];var g=this;this.asyncExecuteFunction(function(){g.executeBatch_()})}this.batch_.push(c)};
var f=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(c){f(c,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var c=this.batch_;this.batch_=[];for(var g=0;g<c.length;++g){var l=c[g];c[g]=null;try{l()}catch(p){this.asyncThrow_(p)}}}this.batch_=null};b.prototype.asyncThrow_=function(c){this.asyncExecuteFunction(function(){throw c;})};var d=function(c){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var g=this.createResolveAndReject_();
try{c(g.resolve,g.reject)}catch(l){g.reject(l)}};d.prototype.createResolveAndReject_=function(){function c(p){return function(m){l||(l=!0,p.call(g,m))}}var g=this,l=!1;return{resolve:c(this.resolveTo_),reject:c(this.reject_)}};d.prototype.resolveTo_=function(c){if(c===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(c instanceof d)this.settleSameAsPromise_(c);else{a:switch(typeof c){case "object":var g=null!=c;break a;case "function":g=!0;break a;default:g=!1}g?this.resolveToNonPromiseObj_(c):
this.fulfill_(c)}};d.prototype.resolveToNonPromiseObj_=function(c){var g=void 0;try{g=c.then}catch(l){this.reject_(l);return}"function"==typeof g?this.settleSameAsThenable_(g,c):this.fulfill_(c)};d.prototype.reject_=function(c){this.settle_(2,c)};d.prototype.fulfill_=function(c){this.settle_(1,c)};d.prototype.settle_=function(c,g){if(0!=this.state_)throw Error("Cannot settle("+c+", "+g+"): Promise already settled in state"+this.state_);this.state_=c;this.result_=g;2===this.state_&&this.scheduleUnhandledRejectionCheck_();
this.executeOnSettledCallbacks_()};d.prototype.scheduleUnhandledRejectionCheck_=function(){var c=this;f(function(){if(c.notifyUnhandledRejection_()){var g=$jscomp.global.console;"undefined"!==typeof g&&g.error(c.result_)}},1)};d.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var c=$jscomp.global.CustomEvent,g=$jscomp.global.Event,l=$jscomp.global.dispatchEvent;if("undefined"===typeof l)return!0;"function"===typeof c?c=new c("unhandledrejection",{cancelable:!0}):
"function"===typeof g?c=new g("unhandledrejection",{cancelable:!0}):(c=$jscomp.global.document.createEvent("CustomEvent"),c.initCustomEvent("unhandledrejection",!1,!0,c));c.promise=this;c.reason=this.result_;return l(c)};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var c=0;c<this.onSettledCallbacks_.length;++c)h.asyncExecute(this.onSettledCallbacks_[c]);this.onSettledCallbacks_=null}};var h=new b;d.prototype.settleSameAsPromise_=function(c){var g=this.createResolveAndReject_();
c.callWhenSettled_(g.resolve,g.reject)};d.prototype.settleSameAsThenable_=function(c,g){var l=this.createResolveAndReject_();try{c.call(g,l.resolve,l.reject)}catch(p){l.reject(p)}};d.prototype.then=function(c,g){function l(r,k){return"function"==typeof r?function(t){try{p(r(t))}catch(u){m(u)}}:k}var p,m,n=new d(function(r,k){p=r;m=k});this.callWhenSettled_(l(c,p),l(g,m));return n};d.prototype["catch"]=function(c){return this.then(void 0,c)};d.prototype.callWhenSettled_=function(c,g){function l(){switch(p.state_){case 1:c(p.result_);
break;case 2:g(p.result_);break;default:throw Error("Unexpected state: "+p.state_);}}var p=this;null==this.onSettledCallbacks_?h.asyncExecute(l):this.onSettledCallbacks_.push(l);this.isRejectionHandled_=!0};d.resolve=e;d.reject=function(c){return new d(function(g,l){l(c)})};d.race=function(c){return new d(function(g,l){for(var p=$jscomp.makeIterator(c),m=p.next();!m.done;m=p.next())e(m.value).callWhenSettled_(g,l)})};d.all=function(c){var g=$jscomp.makeIterator(c),l=g.next();return l.done?e([]):new d(function(p,
m){function n(t){return function(u){r[t]=u;k--;0==k&&p(r)}}var r=[],k=0;do r.push(void 0),k++,e(l.value).callWhenSettled_(n(r.length-1),m),l=g.next();while(!l.done)})};return d},"es6","es3");$(".erc").html(" (BEP-20)");$(".changenet").each(function(){this.href+="tokensale/"});
var contractAddressMain="0xB9D361e7C28e851609dBd7875076be0869825728",contractAddressTest="0xDaDcdBF763e64566d4e387B8be84C801b0FfBcb5",contractTokenBuilder1Main="0x32D332487C8703D94C46F99E55b12D3BaAB45190",contractTokenBuilder1Test="0x32D332487C8703D94C46F99E55b12D3BaAB45190",contractTokenBuilder2Main="0x76079d9098b84cb28F2045c4fbC44EF6AAf5b0e7",contractTokenBuilder2Test="0xA61Bc01643CC20e722761E35e4C270BbF4c36A03",contractTokenBuilder3Main="0xeE4B8458741492455d7B9929F87342Aed9D4eF4b",contractTokenBuilder3Test=
"0xBFFEfDCC6275bd0D6703fCe006bB69e2a06Fb4B6",contractTokenBuilder4Main="0x592173bc112099c812216b62504a20aaeb38c679",contractTokenBuilder4Test="0x34e18d89B43d0Ef859896D54D024072785D8C48f",contractTokenBuilder5Main="0xF74A3016E6cb9C0f112F6F6ACf5e9A5dcFB13C66",contractTokenBuilder5Test="0xA56750825ad3c76b53731AFaa7C9Eb982Fb7F0C3",contractTokenBuilder1,contractTokenBuilder2,contractTokenBuilder3,contractTokenBuilder4,contractTokenBuilder5,builderCost,contractThis,contractThisSign,contractThisToken,contractThisTokenSign,
balanceEth,thisDecimals,thisTokenAddress,thisAddress,thisSymbol,thisUnsold,available,maxDecimals=18,abi=[{inputs:[{internalType:"uint256",name:"_cost",type:"uint256"}],stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"oldBeneficiary",type:"address"},{indexed:!0,internalType:"address",name:"newBeneficiary",type:"address"}],name:"BeneficiarySet",type:"event"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"contractCreator",
type:"address"},{indexed:!0,internalType:"address",name:"contractAddress",type:"address"},{indexed:!1,internalType:"address",name:"tokenAddress",type:"address"},{indexed:!1,internalType:"uint256",name:"tokenQuantity",type:"uint256"},{indexed:!1,internalType:"uint256",name:"salePrice",type:"uint256"}],name:"ContractCreated",type:"event"},{anonymous:!1,inputs:[{indexed:!1,internalType:"uint256",name:"newCost",type:"uint256"}],name:"Cost",type:"event"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",
name:"oldOwner",type:"address"},{indexed:!0,internalType:"address",name:"newOwner",type:"address"}],name:"OwnerSet",type:"event"},{inputs:[],name:"beneficiary",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"newBeneficiary",type:"address"}],name:"changeBeneficiary",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_newcost",type:"uint256"}],name:"changeCost",outputs:[],
stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"newOwner",type:"address"}],name:"changeOwner",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"cost",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"tokenAddress",type:"address"},{internalType:"uint256",name:"saleQty",type:"uint256"},{internalType:"uint256",name:"salePrice",type:"uint256"}],name:"createContract",
outputs:[{internalType:"address",name:"contractAddress",type:"address"}],stateMutability:"payable",type:"function"},{inputs:[],name:"myContracts",outputs:[{internalType:"address[]",name:"",type:"address[]"}],stateMutability:"view",type:"function"},{inputs:[],name:"owner",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalBuilt",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],
name:"withdraw",outputs:[],stateMutability:"nonpayable",type:"function"}],abiSale=[{inputs:[{internalType:"address",name:"_tokenAddress",type:"address"},{internalType:"uint256",name:"_saleQuantity",type:"uint256"},{internalType:"uint256",name:"_salePrice",type:"uint256"}],stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,inputs:[{indexed:!1,internalType:"address",name:"buyer",type:"address"},{indexed:!1,internalType:"uint256",name:"quantity",type:"uint256"}],name:"TokenSold",type:"event"},
{inputs:[],name:"buyToken",outputs:[],stateMutability:"payable",type:"function"},{inputs:[],name:"owner",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"saleOn",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[],name:"saleQuantity",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"tokenAddress",outputs:[{internalType:"address",
name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"tokenPrice",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalRaised",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalSold",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"unsoldQuantity",outputs:[{internalType:"uint256",
name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"uint256",name:"_amount",type:"uint256"}],name:"withdraw",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"withdrawAll",outputs:[],stateMutability:"nonpayable",type:"function"},{stateMutability:"payable",type:"receive"}],abiToken=[{inputs:[{internalType:"string",name:"_name",type:"string"},{internalType:"string",name:"_symbol",type:"string"},{internalType:"uint256",name:"_dec",type:"uint256"},
{internalType:"uint256",name:"_supply",type:"uint256"},{internalType:"uint256",name:"_tax1",type:"uint256"},{internalType:"address",name:"_address1",type:"address"},{internalType:"uint256",name:"_tax2",type:"uint256"},{internalType:"address",name:"_address2",type:"address"},{internalType:"uint256",name:"_deflation",type:"uint256"},{internalType:"uint256",name:"_minSupply",type:"uint256"},{internalType:"address",name:"_owner",type:"address"}],stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,
inputs:[{indexed:!0,internalType:"address",name:"owner",type:"address"},{indexed:!0,internalType:"address",name:"spender",type:"address"},{indexed:!1,internalType:"uint256",name:"value",type:"uint256"}],name:"Approval",type:"event"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"from",type:"address"},{indexed:!0,internalType:"address",name:"to",type:"address"},{indexed:!1,internalType:"uint256",name:"value",type:"uint256"}],name:"Transfer",type:"event"},{inputs:[],name:"addressTax1",
outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"addressTax2",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"owner",type:"address"},{internalType:"address",name:"spender",type:"address"}],name:"allowance",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"spender",
type:"address"},{internalType:"uint256",name:"value",type:"uint256"}],name:"approve",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"owner",type:"address"}],name:"balanceOf",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"burnt",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"decimals",
outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"deflation",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"initialSupply",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"minSupply",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"name",
outputs:[{internalType:"string",name:"",type:"string"}],stateMutability:"view",type:"function"},{inputs:[],name:"symbol",outputs:[{internalType:"string",name:"",type:"string"}],stateMutability:"view",type:"function"},{inputs:[],name:"tax1",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"tax2",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalSupply",outputs:[{internalType:"uint256",
name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalTax1",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalTax2",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"to",type:"address"},{internalType:"uint256",name:"value",type:"uint256"}],name:"transfer",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"nonpayable",
type:"function"},{inputs:[{internalType:"address",name:"from",type:"address"},{internalType:"address",name:"to",type:"address"},{internalType:"uint256",name:"value",type:"uint256"}],name:"transferFrom",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"nonpayable",type:"function"}],abiTokenBuilder=[{inputs:[{internalType:"uint256",name:"_cost",type:"uint256"}],stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"oldBeneficiary",
type:"address"},{indexed:!0,internalType:"address",name:"newBeneficiary",type:"address"}],name:"BeneficiarySet",type:"event"},{anonymous:!1,inputs:[{indexed:!1,internalType:"uint256",name:"newCost",type:"uint256"}],name:"Cost",type:"event"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"oldOwner",type:"address"},{indexed:!0,internalType:"address",name:"newOwner",type:"address"}],name:"OwnerSet",type:"event"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"tokenCreator",
type:"address"},{indexed:!0,internalType:"address",name:"tokenAddress",type:"address"},{indexed:!1,internalType:"string",name:"name",type:"string"},{indexed:!1,internalType:"string",name:"symbol",type:"string"},{indexed:!1,internalType:"uint256",name:"totalSupply",type:"uint256"},{indexed:!1,internalType:"uint8",name:"decimals",type:"uint8"}],name:"TokenCreated",type:"event"},{inputs:[],name:"beneficiary",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},
{inputs:[{internalType:"address",name:"newBeneficiary",type:"address"}],name:"changeBeneficiary",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_newcost",type:"uint256"}],name:"changeCost",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"newOwner",type:"address"}],name:"changeOwner",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"cost",outputs:[{internalType:"uint256",name:"",
type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"string",name:"name",type:"string"},{internalType:"string",name:"symbol",type:"string"},{internalType:"uint256",name:"totalSupply",type:"uint256"},{internalType:"uint8",name:"decimals",type:"uint8"},{internalType:"address",name:"to",type:"address"}],name:"createToken",outputs:[{internalType:"address",name:"tokenAddress",type:"address"}],stateMutability:"payable",type:"function"},{inputs:[{internalType:"address",name:"tokenAddress",
type:"address"}],name:"getTokenData",outputs:[{internalType:"string",name:"name",type:"string"},{internalType:"string",name:"symbol",type:"string"},{internalType:"uint256",name:"totalSupply",type:"uint256"},{internalType:"uint256",name:"decimals",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"myTokens",outputs:[{internalType:"address[]",name:"",type:"address[]"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"",type:"address"},{internalType:"uint256",
name:"",type:"uint256"}],name:"mytokens",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"owner",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"",type:"address"}],name:"tokens",outputs:[{internalType:"string",name:"name",type:"string"},{internalType:"string",name:"symbol",type:"string"},{internalType:"uint256",name:"totalSupply",type:"uint256"},
{internalType:"uint8",name:"decimals",type:"uint8"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalBuilt",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"withdraw",outputs:[],stateMutability:"nonpayable",type:"function"}];
function init(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return contract=new ethers.Contract(contractAddress,abi,provider),contractSign=contract.connect(signer),a.yield(contract.cost(),2);builderCost=a.yieldResult;$("#buildercost").html(ethers.utils.formatEther(builderCost));filter=contract.filters.ContractCreated(myAddress);contract.on(filter,function(b,e,f,d,h){console.log("New sale contract for token "+f+", sale quantity "+d+", price "+h+" - created at address "+
e+".");makeTable()});makeTable();a.jumpToEnd()})}
function makeTable(){var a,b,e,f,d,h,c,g,l,p,m,n,r,k,t,u,v,w,x;return $jscomp.asyncExecutePromiseGeneratorProgram(function(q){switch(q.nextAddress){case 1:return a="",q.yield(contract.myContracts({from:myAddress}),2);case 2:b=q.yieldResult;if(b==[]){q.jumpTo(3);break}e=b;f=0;case 4:if(!(f<e.length)){q.jumpTo(3);break}d=e[f];h=new ethers.Contract(d,abiSale,provider);return q.yield(h.tokenAddress(),7);case 7:return c=q.yieldResult,q.yield(h.saleQuantity(),8);case 8:return g=q.yieldResult,q.yield(h.unsoldQuantity(),
9);case 9:return l=q.yieldResult,q.yield(h.tokenPrice(),10);case 10:return p=q.yieldResult,q.yield(h.saleOn(),11);case 11:return m=q.yieldResult,r=new ethers.Contract(c,abiToken,provider),q.yield(r.name(),12);case 12:return k=q.yieldResult,q.yield(r.symbol(),13);case 13:return t=q.yieldResult,q.yield(r.decimals(),14);case 14:return q.yield(r.allowance(myAddress,d),15);case 15:return u=q.yieldResult,q.yield(r.balanceOf(myAddress),16);case 16:return v=q.yieldResult,q.yield(r.decimals(),17);case 17:w=
q.yieldResult;n=Number(u)<Number(l)?'<span style="color: red">Approve!</span>':Number(v)<Number(l)?'<span style="color: red">Add balance!</span>':m?"OK":"Finished";x=Number(f+1);a=a+"<tr><td>"+x+'</td><td><a title="View on explorer" target="_blank" href="'+tracker+"address/"+d+'">'+d+'</a></td><td><a title="View on explorer" target="_blank" href="'+tracker+"token/"+c+'">'+k+"("+t+")</a></td><td>"+ethers.utils.formatUnits(g,w)+"</td><td>"+ethers.utils.formatEther(p)+"</td><td>"+n+'</td><td><span title="Admin panel" class="clickable" onclick="admin(\''+
d+'\')">admin</span></td><td><span title="User interface" class="clickable" onclick="ui(\''+d+"')\">UI</span></td>";a+="</tr>";f++;q.jumpTo(4);break;case 3:$("#strHtml").html(a),q.jumpToEnd()}})}
$("#mytokens").click(function(){var a,b,e,f,d,h,c,g,l,p,m,n,r;return $jscomp.asyncExecutePromiseGeneratorProgram(function(k){switch(k.nextAddress){case 1:return $("#mytoks").show(),curnet==mainnet||curnet==mainnetAlt?(contractTokenBuilder1=contractTokenBuilder1Main,contractTokenBuilder2=contractTokenBuilder2Main,contractTokenBuilder3=contractTokenBuilder3Main,contractTokenBuilder4=contractTokenBuilder4Main,contractTokenBuilder5=contractTokenBuilder5Main):curnet==testnet&&(contractTokenBuilder1=contractTokenBuilder1Test,
contractTokenBuilder2=contractTokenBuilder2Test,contractTokenBuilder3=contractTokenBuilder3Test,contractTokenBuilder4=contractTokenBuilder4Test,contractTokenBuilder5=contractTokenBuilder5Test),contractToken1=new ethers.Contract(contractTokenBuilder1,abiTokenBuilder,provider),contractToken2=new ethers.Contract(contractTokenBuilder2,abiTokenBuilder,provider),contractToken3=new ethers.Contract(contractTokenBuilder3,abiTokenBuilder,provider),contractToken4=new ethers.Contract(contractTokenBuilder4,abiTokenBuilder,
provider),contractToken5=new ethers.Contract(contractTokenBuilder5,abiTokenBuilder,provider),a="",b=0,k.yield(contractToken1.myTokens({from:myAddress}),2);case 2:e=k.yieldResult;if(e==[]){k.jumpTo(3);break}f=e;d=0;case 4:if(!(d<f.length)){k.jumpTo(3);break}h=f[d];c=new ethers.Contract(h,abiToken,provider);return k.yield(c.name(),7);case 7:return g=k.yieldResult,k.yield(c.symbol(),8);case 8:l=k.yieldResult;b=Number(b+1);a=a+"<tr><td>"+b+'</td><td><a title="View on explorer" target="_blank" href="'+
tracker+"token/"+h+'">'+h+"</a></td><td>"+g+"</td><td>"+l+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+h+"')\">choose</span></td>";a+="</tr>";d++;k.jumpTo(4);break;case 3:return k.yield(contractToken2.myTokens({from:myAddress}),9);case 9:p=k.yieldResult;if(p==[]){k.jumpTo(10);break}f=p;d=0;case 11:if(!(d<f.length)){k.jumpTo(10);break}h=f[d];c=new ethers.Contract(h,abiToken,provider);return k.yield(c.name(),14);case 14:return g=k.yieldResult,k.yield(c.symbol(),15);
case 15:l=k.yieldResult;b=Number(b+1);a=a+"<tr><td>"+b+'</td><td><a title="View on explorer" target="_blank" href="'+tracker+"token/"+h+'">'+h+"</a></td><td>"+g+"</td><td>"+l+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+h+"')\">choose</span></td>";a+="</tr>";d++;k.jumpTo(11);break;case 10:return k.yield(contractToken3.myTokens({from:myAddress}),16);case 16:m=k.yieldResult;if(m==[]){k.jumpTo(17);break}f=m;d=0;case 18:if(!(d<f.length)){k.jumpTo(17);break}h=f[d];c=
new ethers.Contract(h,abiToken,provider);return k.yield(c.name(),21);case 21:return g=k.yieldResult,k.yield(c.symbol(),22);case 22:l=k.yieldResult;b=Number(b+1);a=a+"<tr><td>"+b+'</td><td><a title="View on explorer" target="_blank" href="'+tracker+"token/"+h+'">'+h+"</a></td><td>"+g+"</td><td>"+l+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+h+"')\">choose</span></td>";a+="</tr>";d++;k.jumpTo(18);break;case 17:return k.yield(contractToken4.myTokens({from:myAddress}),
23);case 23:n=k.yieldResult;if(n==[]){k.jumpTo(24);break}f=n;d=0;case 25:if(!(d<f.length)){k.jumpTo(24);break}h=f[d];c=new ethers.Contract(h,abiToken,provider);return k.yield(c.name(),28);case 28:return g=k.yieldResult,k.yield(c.symbol(),29);case 29:l=k.yieldResult;b=Number(b+1);a=a+"<tr><td>"+b+'</td><td><a title="View on explorer" target="_blank" href="'+tracker+"token/"+h+'">'+h+"</a></td><td>"+g+"</td><td>"+l+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+h+"')\">choose</span></td>";
a+="</tr>";d++;k.jumpTo(25);break;case 24:return k.yield(contractToken5.myTokens({from:myAddress}),30);case 30:r=k.yieldResult;if(r==[]){k.jumpTo(31);break}f=r;d=0;case 32:if(!(d<f.length)){k.jumpTo(31);break}h=f[d];c=new ethers.Contract(h,abiToken,provider);return k.yield(c.name(),35);case 35:return g=k.yieldResult,k.yield(c.symbol(),36);case 36:l=k.yieldResult;b=Number(b+1);a=a+"<tr><td>"+b+'</td><td><a title="View on explorer" target="_blank" href="'+tracker+"token/"+h+'">'+h+"</a></td><td>"+g+
"</td><td>"+l+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+h+"')\">choose</span></td>";a+="</tr>";d++;k.jumpTo(32);break;case 31:$("#strHtmlTokens").html(a),k.jumpToEnd()}})});function choose(a){$("#newtknaddress").val(a);$("#mytoks").hide();checkToken()}
function admin(a){var b,e,f,d,h,c,g,l,p,m;return $jscomp.asyncExecutePromiseGeneratorProgram(function(n){switch(n.nextAddress){case 1:return $("#admin").show(),$("#thisAddr").html(a),$("#viewThis").html('<a title="View on explorer" target="_blank" href="'+tracker+"address/"+a+'">'+a+"</a>"),thisAddress=a,contractThis=new ethers.Contract(a,abiSale,provider),contractThisSign=contractThis.connect(signer),n.yield(contractThis.tokenAddress(),2);case 2:return thisTokenAddress=n.yieldResult,$("#thisTokenAddress").html(thisTokenAddress),
$("#viewThisToken").html('<a title="View on explorer" target="_blank" href="'+tracker+"token/"+thisTokenAddress+'">'+thisTokenAddress+"</a>"),contractThisToken=new ethers.Contract(thisTokenAddress,abiToken,provider),contractThisTokenSign=contractThisToken.connect(signer),n.yield(contractThisToken.name(),3);case 3:return b=n.yieldResult,$("#thisName").html(b),n.yield(contractThisToken.symbol(),4);case 4:return thisSymbol=n.yieldResult,$("#thisSymbol").html(thisSymbol),n.yield(contractThisToken.decimals(),
5);case 5:return thisDecimals=n.yieldResult,$("#thisDec").html(Number(thisDecimals)),n.yield(contractThisToken.allowance(myAddress,a),6);case 6:return e=n.yieldResult,n.yield(contractThisToken.balanceOf(myAddress),7);case 7:return f=n.yieldResult,n.yield(contractThis.saleQuantity(),8);case 8:return d=n.yieldResult,$("#thisSaleQty").html(ethers.utils.formatUnits(d,thisDecimals)),n.yield(contractThis.tokenPrice(),9);case 9:return h=n.yieldResult,$("#thisTokenPrice").html(ethers.utils.formatEther(h)),
n.yield(contractThis.totalSold(),10);case 10:return c=n.yieldResult,$("#thisSold").html(ethers.utils.formatUnits(c,thisDecimals)),n.yield(contractThis.totalRaised(),11);case 11:return g=n.yieldResult,$("#thisRaised").html(ethers.utils.formatEther(g)),n.yield(contractThis.unsoldQuantity(),12);case 12:return thisUnsold=n.yieldResult,$("#thisUnsold").html(ethers.utils.formatUnits(thisUnsold,thisDecimals)),n.yield(provider.getBalance(a),13);case 13:return l=n.yieldResult,available=ethers.utils.formatEther(l),
$("#thisBalance").html(available),n.yield(contractThis.saleOn(),14);case 14:p=n.yieldResult,Number(e)<Number(thisUnsold)&&Number(f)>=Number(thisUnsold)?(m='<span style="color: red">Approve!</span>',$("#thisApprove").show()):(m=Number(f)<Number(thisUnsold)?'<span style="color: red">Add balance!</span>':p?'<span style="color: green">OK</span>':"Finished",$("#thisApprove").hide()),$("#thisStatus").html(m),$("#addToken").click(function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(r){watchToken(thisTokenAddress,
thisSymbol,thisDecimals);r.jumpToEnd()})}),n.jumpToEnd()}})}$("#thisApprove").click(function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return thisAddress&&thisUnsold?a.yield(contractThisTokenSign.approve(String(thisAddress),String(thisUnsold),{gasLimit:1E5}),3):a.jumpTo(0);if(4!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),4);init();admin(thisAddress);a.jumpToEnd()})});
$("#thisWithdraw").click(function(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return a=$("#thisWithdrawAmount").val(),""!=a&&0<a?b.yield(contractThisSign.withdraw(ethers.utils.parseEther(a),{gasLimit:1E5}),3):b.jumpTo(0);if(4!=b.nextAddress)return tx=b.yieldResult,b.yield(tx.wait(),4);admin(thisAddress);b.jumpToEnd()})});
$("#thisWithdrawAll").click(function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return 0<available?a.yield(contractThisSign.withdrawAll({gasLimit:1E5}),3):a.jumpTo(0);if(4!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),4);admin(thisAddress);a.jumpToEnd()})});
function watchToken(a,b,e){return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){ethereum.request({method:"wallet_watchAsset",params:{type:"ERC20",options:{address:String(a),symbol:String(b),decimals:String(e)}}});f.jumpToEnd()})}$("#newtknaddress").on("keyup input",checkToken);
function checkToken(){var a,b,e,f,d;return $jscomp.asyncExecutePromiseGeneratorProgram(function(h){switch(h.nextAddress){case 1:$("#tokendata").html("");a=$("#newtknaddress").val();if(""==a||!ethers.utils.isAddress(a))return""==a?$("#tokendata").html(""):$("#tokendata").html('<span class="err">Error: check token address!</span>'),h["return"](!1);$("#errors").html("");h.setCatchFinallyBlocks(3);b=new ethers.Contract(a,abiToken,provider);return h.yield(b.name(),5);case 5:return e=h.yieldResult,h.yield(b.symbol(),
6);case 6:f=h.yieldResult;if(e&&f)return $("#tokendata").html('<span style="color: green">'+e+" ("+f+")</span>"),h["return"](!0);$("#tokendata").html('<span class="err">Error: check token address!</span>');return h["return"](!1);case 3:return d=h.enterCatchBlock(),console.log(d),$("#tokendata").html('<span class="err">Error: check token address!</span>'),h["return"](!1)}})}
$("#buildbtn").click(function(){var a,b,e,f,d,h,c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){switch(g.nextAddress){case 1:if(!myAddress){g.jumpTo(0);break}return g.yield(provider.getBalance(myAddress),3);case 3:a=g.yieldResult;if(!(Number(a)>Number(builderCost))){$("#errors").html("Insufficient balance in your wallet! Contract creation cost is "+ethers.utils.formatEther(builderCost)+" BNB + network fees (gas)!");g.jumpTo(0);break}return g.yield(checkToken(),5);case 5:b=g.yieldResult;
e=$("#newtknaddress").val();f=$("#newprice").val();d=$("#newqty").val();if(!(""!=e&&0<d&&f&&1E-18<=Number(f)&&b)){f&&1E-18>Number(f)?$("#errors").html("Error: too low token price!"):($("#errors").html("Error: fields are empty or incorrect!"),checkToken());g.jumpTo(0);break}$("#errors").html("");h=new ethers.Contract(e,abiToken,provider);return g.yield(h.decimals(),7);case 7:return c=g.yieldResult,g.yield(contractSign.createContract(String(e),String(ethers.utils.parseUnits(d,c)),String(ethers.utils.parseEther(f)),
{value:builderCost}),8);case 8:return tx=g.yieldResult,g.yield(tx.wait(),9);case 9:init(),g.jumpToEnd()}})});$("#newprice").on("keyup input",function(){var a=$("#newprice").val();a=1/Number(a);$("#tokperbnb").html(Number(a))});$("#thisWithdrawAmount").change(function(){var a=$("#thisWithdrawAmount").val();0>a?a=0:a>available&&(a=available);$("#thisWithdrawAmount").val(Number(a))});
function ui(a){var b,e,f,d,h,c,g,l,p;return $jscomp.asyncExecutePromiseGeneratorProgram(function(m){switch(m.nextAddress){case 1:return $("#ui").show(),$(".uiAddr").html(a),$(".uiAddrlnk").attr("href",tracker+"address/"+a),curnet==testnet?$("#istest").html("true"):$("#istest").html("false"),b=new ethers.Contract(a,abiSale,provider),m.yield(b.tokenAddress(),2);case 2:return e=m.yieldResult,$(".tokenAddressUI").html(e),$(".tokenAddressUIlnk").attr("href",tracker+"token/"+e),f=new ethers.Contract(e,
abiToken,provider),m.yield(f.name(),3);case 3:return d=m.yieldResult,$("#tokenNameUI").html(d),m.yield(f.symbol(),4);case 4:return tokenSymbolUI=m.yieldResult,$("#tokenSymbolUI").html(tokenSymbolUI),m.yield(f.decimals(),5);case 5:return tokenDecimalsUI=m.yieldResult,$("#tokenDecimalsUI").html(Number(tokenDecimalsUI)),m.yield(f.totalSupply(),6);case 6:return h=m.yieldResult,$("#tokenSupplyUI").html(Number(ethers.utils.formatUnits(h,tokenDecimalsUI)).toFixed(0)),m.yield(b.saleQuantity(),7);case 7:return c=
m.yieldResult,$("#quantityUI").html(Number(ethers.utils.formatUnits(c,tokenDecimalsUI))),m.yield(b.totalSold(),8);case 8:return g=m.yieldResult,$("#soldUI").html(Number(ethers.utils.formatUnits(g,tokenDecimalsUI))),m.yield(b.unsoldQuantity(),9);case 9:return l=m.yieldResult,availableUI=ethers.utils.formatUnits(l,tokenDecimalsUI),$("#unsoldUI").html(Number(availableUI)),m.yield(b.tokenPrice(),10);case 10:return priceUI=m.yieldResult,$("#priceUI").html(ethers.utils.formatEther(priceUI)),m.yield(b.totalRaised(),
11);case 11:p=m.yieldResult,$("#raisedUI").html(ethers.utils.formatEther(p)),getQR(a),m.jumpToEnd()}})}function getQR(a){a=encodeURIComponent(a);$("#refqr").html('<img style="max-width: 80%" src="https://create.metaexchange.finance/php/qr.php?data='+a+'">');$("#refd").attr("href","https://create.metaexchange.finance/php/qr.php?data="+a)};