var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,f){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,f):$jscomp.polyfillUnisolated(a,b,c,f))};
$jscomp.polyfillUnisolated=function(a,b,c,f){c=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var e=a[f];if(!(e in c))return;c=c[e]}a=a[a.length-1];f=c[a];b=b(f);b!=f&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,f){var e=a.split(".");a=1===e.length;f=e[0];f=!a&&f in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var g=0;g<e.length-1;g++){var d=e[g];if(!(d in f))return;f=f[d]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?f[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&(c=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+c+"$"+e),$jscomp.defineProperty(f,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};
$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){var c=$jscomp.makeIterator(a),f=c.next();$jscomp.generator.ensureIteratorResultIsObject_(f);if(f.done)this.yieldResult=f.value,this.nextAddress=b;else return this.yieldAllIterator_=c,this.yield(f.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var c=this.finallyContexts_.splice(b||0)[0];if(c=this.abruptCompletion_=this.abruptCompletion_||c){if(c.isException)return this.jumpToErrorHandler_();void 0!=c.jumpTo&&this.finallyAddress_<c.jumpTo?(this.nextAddress=c.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(c){return{value:c,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var f=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(f);if(!f.done)return this.context_.stop_(),f;var e=f.value}catch(g){return this.context_.yieldAllIterator_=null,this.context_.throw_(g),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var c=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(c,a.prototype);return c};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(f){return a.next(f)}function c(f){return a["throw"](f)}return new Promise(function(f,e){function g(d){d.done?f(d.value):Promise.resolve(d.value).then(b,c).then(g,e)}g(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.initSymbol=function(){};$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(g,d){this.$jscomp$symbol$id_=g;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:d})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",f=0,e=function(g){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(g||"")+"_"+f++,g)};return e},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var f=$jscomp.global[b[c]];"function"===typeof f&&"function"!=typeof f.prototype[a]&&$jscomp.defineProperty(f.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(d){return d instanceof e?d:new e(function(h,n){h(d)})}if(a&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&"undefined"===typeof $jscomp.global.PromiseRejectionEvent)||!$jscomp.global.Promise||-1===$jscomp.global.Promise.toString().indexOf("[native code]")))return a;b.prototype.asyncExecute=function(d){if(null==this.batch_){this.batch_=[];var h=this;this.asyncExecuteFunction(function(){h.executeBatch_()})}this.batch_.push(d)};
var f=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(d){f(d,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var d=this.batch_;this.batch_=[];for(var h=0;h<d.length;++h){var n=d[h];d[h]=null;try{n()}catch(q){this.asyncThrow_(q)}}}this.batch_=null};b.prototype.asyncThrow_=function(d){this.asyncExecuteFunction(function(){throw d;})};var e=function(d){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var h=this.createResolveAndReject_();
try{d(h.resolve,h.reject)}catch(n){h.reject(n)}};e.prototype.createResolveAndReject_=function(){function d(q){return function(t){n||(n=!0,q.call(h,t))}}var h=this,n=!1;return{resolve:d(this.resolveTo_),reject:d(this.reject_)}};e.prototype.resolveTo_=function(d){if(d===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof e)this.settleSameAsPromise_(d);else{a:switch(typeof d){case "object":var h=null!=d;break a;case "function":h=!0;break a;default:h=!1}h?this.resolveToNonPromiseObj_(d):
this.fulfill_(d)}};e.prototype.resolveToNonPromiseObj_=function(d){var h=void 0;try{h=d.then}catch(n){this.reject_(n);return}"function"==typeof h?this.settleSameAsThenable_(h,d):this.fulfill_(d)};e.prototype.reject_=function(d){this.settle_(2,d)};e.prototype.fulfill_=function(d){this.settle_(1,d)};e.prototype.settle_=function(d,h){if(0!=this.state_)throw Error("Cannot settle("+d+", "+h+"): Promise already settled in state"+this.state_);this.state_=d;this.result_=h;2===this.state_&&this.scheduleUnhandledRejectionCheck_();
this.executeOnSettledCallbacks_()};e.prototype.scheduleUnhandledRejectionCheck_=function(){var d=this;f(function(){if(d.notifyUnhandledRejection_()){var h=$jscomp.global.console;"undefined"!==typeof h&&h.error(d.result_)}},1)};e.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var d=$jscomp.global.CustomEvent,h=$jscomp.global.Event,n=$jscomp.global.dispatchEvent;if("undefined"===typeof n)return!0;"function"===typeof d?d=new d("unhandledrejection",{cancelable:!0}):
"function"===typeof h?d=new h("unhandledrejection",{cancelable:!0}):(d=$jscomp.global.document.createEvent("CustomEvent"),d.initCustomEvent("unhandledrejection",!1,!0,d));d.promise=this;d.reason=this.result_;return n(d)};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var d=0;d<this.onSettledCallbacks_.length;++d)g.asyncExecute(this.onSettledCallbacks_[d]);this.onSettledCallbacks_=null}};var g=new b;e.prototype.settleSameAsPromise_=function(d){var h=this.createResolveAndReject_();
d.callWhenSettled_(h.resolve,h.reject)};e.prototype.settleSameAsThenable_=function(d,h){var n=this.createResolveAndReject_();try{d.call(h,n.resolve,n.reject)}catch(q){n.reject(q)}};e.prototype.then=function(d,h){function n(l,v){return"function"==typeof l?function(r){try{q(l(r))}catch(u){t(u)}}:v}var q,t,w=new e(function(l,v){q=l;t=v});this.callWhenSettled_(n(d,q),n(h,t));return w};e.prototype["catch"]=function(d){return this.then(void 0,d)};e.prototype.callWhenSettled_=function(d,h){function n(){switch(q.state_){case 1:d(q.result_);
break;case 2:h(q.result_);break;default:throw Error("Unexpected state: "+q.state_);}}var q=this;null==this.onSettledCallbacks_?g.asyncExecute(n):this.onSettledCallbacks_.push(n);this.isRejectionHandled_=!0};e.resolve=c;e.reject=function(d){return new e(function(h,n){n(d)})};e.race=function(d){return new e(function(h,n){for(var q=$jscomp.makeIterator(d),t=q.next();!t.done;t=q.next())c(t.value).callWhenSettled_(h,n)})};e.all=function(d){var h=$jscomp.makeIterator(d),n=h.next();return n.done?c([]):new e(function(q,
t){function w(r){return function(u){l[r]=u;v--;0==v&&q(l)}}var l=[],v=0;do l.push(void 0),v++,c(n.value).callWhenSettled_(w(l.length-1),t),n=h.next();while(!n.done)})};return e},"es6","es3");$(".erc").html(" (BEP-20)");$(".changenet").each(function(){this.href+="tokensaleclaimtimeref/"});
var contractAddressMain="0x27b4F34D49b1d0f9C867D391751A5eD7488001C3",contractAddressTest="0x77466c300dC923280AE922a959445cB66049b9de",contractAddressMain1="0x912b200B119FeD9cA0c274d817bb24f2C057a7CD",contractAddressTest1="0x1E4F26A627963f14424f3C78bb484E620b26FDAD",contractTokenBuilder1Main="0x32D332487C8703D94C46F99E55b12D3BaAB45190",contractTokenBuilder1Test="0x32D332487C8703D94C46F99E55b12D3BaAB45190",contractTokenBuilder2Main="0x76079d9098b84cb28F2045c4fbC44EF6AAf5b0e7",contractTokenBuilder2Test=
"0xA61Bc01643CC20e722761E35e4C270BbF4c36A03",contractTokenBuilder3Main="0xeE4B8458741492455d7B9929F87342Aed9D4eF4b",contractTokenBuilder3Test="0xBFFEfDCC6275bd0D6703fCe006bB69e2a06Fb4B6",contractTokenBuilder4Main="0x592173bc112099c812216b62504a20aaeb38c679",contractTokenBuilder4Test="0x34e18d89B43d0Ef859896D54D024072785D8C48f",contractTokenBuilder5Main="0xF74A3016E6cb9C0f112F6F6ACf5e9A5dcFB13C66",contractTokenBuilder5Test="0xA56750825ad3c76b53731AFaa7C9Eb982Fb7F0C3",contractTokenBuilder1,contractTokenBuilder2,
contractTokenBuilder3,contractTokenBuilder4,contractTokenBuilder5,contractAddressV1,contractV1,builderCost,builderedge,contractThis,contractThisSign,contractThisToken,contractThisTokenSign,balanceEth,thisDecimals,thisTokenAddress,thisAddress,thisSymbol,thisUnsold,thisUnsoldQty,available,thisBalance,thisHardcap,maxDecimals=18,dayms=86400,hourms=3600,abi=[{inputs:[],stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"creator",type:"address"},
{indexed:!0,internalType:"address",name:"contractAddress",type:"address"}],name:"ContractCreated",type:"event"},{inputs:[],name:"beneficiary",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"builtFree",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"builtPaid",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",
name:"_newBeneficiary",type:"address"}],name:"changeBeneficiary",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_newcost",type:"uint256"}],name:"changeCost",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_newedge",type:"uint256"}],name:"changeEdge",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"_newOwner",type:"address"}],name:"changeOwner",outputs:[],
stateMutability:"nonpayable",type:"function"},{inputs:[],name:"cost",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"_tokenAddress",type:"address"},{internalType:"uint256[]",name:"_params",type:"uint256[]"},{internalType:"address",name:"_beneficiary",type:"address"},{internalType:"bool",name:"_allow",type:"bool"},{internalType:"bool",name:"_free",type:"bool"}],name:"createTokenSale",outputs:[{internalType:"address",
name:"",type:"address"}],stateMutability:"payable",type:"function"},{inputs:[],name:"edge",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"myContracts",outputs:[{internalType:"address[]",name:"",type:"address[]"}],stateMutability:"view",type:"function"},{inputs:[],name:"owner",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalBuilt",outputs:[{internalType:"uint256",
name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"withdraw",outputs:[],stateMutability:"nonpayable",type:"function"},{stateMutability:"payable",type:"receive"}],abiSale=[{inputs:[{internalType:"address",name:"_tokenAddress",type:"address"},{internalType:"uint256[]",name:"_params",type:"uint256[]"},{internalType:"address",name:"_beneficiary",type:"address"},{internalType:"bool",name:"_allow",type:"bool"},{internalType:"address",name:"_dappbuilderAddress",type:"address"},
{internalType:"uint256",name:"_edge",type:"uint256"}],stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,inputs:[{indexed:!1,internalType:"address",name:"buyer",type:"address"},{indexed:!1,internalType:"uint256",name:"amount",type:"uint256"}],name:"Contribution",type:"event"},{inputs:[{internalType:"bool",name:"_allow",type:"bool"}],name:"allowClaimAfterHC",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"",type:"address"}],name:"balances",
outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"beneficiary",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"_ref",type:"address"}],name:"buyToken",outputs:[],stateMutability:"payable",type:"function"},{inputs:[],name:"canClaim",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"uint256",
name:"_qty",type:"uint256"}],name:"checkAmount",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"uint256",name:"_payment",type:"uint256"}],name:"checkChange",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"uint256",name:"_payment",type:"uint256"}],name:"checkQty",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},
{inputs:[],name:"claim",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"claimAfterHCAllowed",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[],name:"claimTermsFixed",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[],name:"claimTime",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"dappbuilderEdge",outputs:[{internalType:"uint256",
name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"delay",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"endTime",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"ended",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"fixClaimTerms",outputs:[],stateMutability:"nonpayable",
type:"function"},{inputs:[],name:"fixHardCap",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"fixPurchaseLimit",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"fixRate",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"fixRefPercent",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"fixSaleTime",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"hardCapFixed",outputs:[{internalType:"bool",
name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[],name:"hardcap",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"uint256",name:"_delay",type:"uint256"}],name:"lockAfterHC",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"makeUnpausable",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"myTokens",outputs:[{internalType:"uint256",name:"",type:"uint256"}],
stateMutability:"view",type:"function"},{inputs:[],name:"owner",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"pausable",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[],name:"purchaseLimit",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"purchaseLimitFixed",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",
type:"function"},{inputs:[],name:"rate",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"rateFixed",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"",type:"address"}],name:"refEarnings",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"refPercent",outputs:[{internalType:"uint256",name:"",
type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"refPercentFixed",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[],name:"refTotal",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"remaining",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"_buyer",type:"address"}],name:"remainingLimit",
outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"saleOn",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"bool",name:"_on",type:"bool"}],name:"saleOnOff",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"saleTimeFixed",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",
name:"_newBeneficiary",type:"address"}],name:"setBeneficiary",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_claimTime",type:"uint256"}],name:"setClaimTime",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_endTime",type:"uint256"}],name:"setEndTime",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_hardcap",type:"uint256"}],name:"setHardcap",outputs:[],stateMutability:"nonpayable",
type:"function"},{inputs:[{internalType:"uint256",name:"_amount",type:"uint256"}],name:"setLimit",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"_newOwner",type:"address"}],name:"setOwner",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_rate",type:"uint256"}],name:"setRate",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_refPercent",type:"uint256"}],name:"setRefPercent",
outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_startTime",type:"uint256"}],name:"setStartTime",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"",type:"address"}],name:"spendings",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"startTime",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},
{inputs:[],name:"tokenAddress",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"tokenBalance",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalRaised",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalSold",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},
{inputs:[],name:"unclaimed",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"withdrawBNB",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"_address",type:"address"}],name:"withdrawCustomToken",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_quantity",type:"uint256"}],name:"withdrawTokens",outputs:[],stateMutability:"nonpayable",type:"function"},
{stateMutability:"payable",type:"receive"}],abiToken=[{inputs:[{internalType:"string",name:"_name",type:"string"},{internalType:"string",name:"_symbol",type:"string"},{internalType:"uint256",name:"_dec",type:"uint256"},{internalType:"uint256",name:"_supply",type:"uint256"},{internalType:"uint256",name:"_tax1",type:"uint256"},{internalType:"address",name:"_address1",type:"address"},{internalType:"uint256",name:"_tax2",type:"uint256"},{internalType:"address",name:"_address2",type:"address"},{internalType:"uint256",
name:"_deflation",type:"uint256"},{internalType:"uint256",name:"_minSupply",type:"uint256"},{internalType:"address",name:"_owner",type:"address"}],stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"owner",type:"address"},{indexed:!0,internalType:"address",name:"spender",type:"address"},{indexed:!1,internalType:"uint256",name:"value",type:"uint256"}],name:"Approval",type:"event"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"from",
type:"address"},{indexed:!0,internalType:"address",name:"to",type:"address"},{indexed:!1,internalType:"uint256",name:"value",type:"uint256"}],name:"Transfer",type:"event"},{inputs:[],name:"addressTax1",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"addressTax2",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"owner",type:"address"},{internalType:"address",
name:"spender",type:"address"}],name:"allowance",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"spender",type:"address"},{internalType:"uint256",name:"value",type:"uint256"}],name:"approve",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"owner",type:"address"}],name:"balanceOf",outputs:[{internalType:"uint256",name:"",type:"uint256"}],
stateMutability:"view",type:"function"},{inputs:[],name:"burnt",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"decimals",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"deflation",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"initialSupply",outputs:[{internalType:"uint256",name:"",type:"uint256"}],
stateMutability:"view",type:"function"},{inputs:[],name:"minSupply",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"name",outputs:[{internalType:"string",name:"",type:"string"}],stateMutability:"view",type:"function"},{inputs:[],name:"symbol",outputs:[{internalType:"string",name:"",type:"string"}],stateMutability:"view",type:"function"},{inputs:[],name:"tax1",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",
type:"function"},{inputs:[],name:"tax2",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalSupply",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalTax1",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalTax2",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",
type:"function"},{inputs:[{internalType:"address",name:"to",type:"address"},{internalType:"uint256",name:"value",type:"uint256"}],name:"transfer",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"from",type:"address"},{internalType:"address",name:"to",type:"address"},{internalType:"uint256",name:"value",type:"uint256"}],name:"transferFrom",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"nonpayable",
type:"function"}],abiTokenBuilder=[{inputs:[{internalType:"uint256",name:"_cost",type:"uint256"}],stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"oldBeneficiary",type:"address"},{indexed:!0,internalType:"address",name:"newBeneficiary",type:"address"}],name:"BeneficiarySet",type:"event"},{anonymous:!1,inputs:[{indexed:!1,internalType:"uint256",name:"newCost",type:"uint256"}],name:"Cost",type:"event"},{anonymous:!1,inputs:[{indexed:!0,
internalType:"address",name:"oldOwner",type:"address"},{indexed:!0,internalType:"address",name:"newOwner",type:"address"}],name:"OwnerSet",type:"event"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"tokenCreator",type:"address"},{indexed:!0,internalType:"address",name:"tokenAddress",type:"address"},{indexed:!1,internalType:"string",name:"name",type:"string"},{indexed:!1,internalType:"string",name:"symbol",type:"string"},{indexed:!1,internalType:"uint256",name:"totalSupply",type:"uint256"},
{indexed:!1,internalType:"uint8",name:"decimals",type:"uint8"}],name:"TokenCreated",type:"event"},{inputs:[],name:"beneficiary",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"newBeneficiary",type:"address"}],name:"changeBeneficiary",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_newcost",type:"uint256"}],name:"changeCost",outputs:[],stateMutability:"nonpayable",
type:"function"},{inputs:[{internalType:"address",name:"newOwner",type:"address"}],name:"changeOwner",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"cost",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"string",name:"name",type:"string"},{internalType:"string",name:"symbol",type:"string"},{internalType:"uint256",name:"totalSupply",type:"uint256"},{internalType:"uint8",name:"decimals",type:"uint8"},
{internalType:"address",name:"to",type:"address"}],name:"createToken",outputs:[{internalType:"address",name:"tokenAddress",type:"address"}],stateMutability:"payable",type:"function"},{inputs:[{internalType:"address",name:"tokenAddress",type:"address"}],name:"getTokenData",outputs:[{internalType:"string",name:"name",type:"string"},{internalType:"string",name:"symbol",type:"string"},{internalType:"uint256",name:"totalSupply",type:"uint256"},{internalType:"uint256",name:"decimals",type:"uint256"}],stateMutability:"view",
type:"function"},{inputs:[],name:"myTokens",outputs:[{internalType:"address[]",name:"",type:"address[]"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"",type:"address"},{internalType:"uint256",name:"",type:"uint256"}],name:"mytokens",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"owner",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",
name:"",type:"address"}],name:"tokens",outputs:[{internalType:"string",name:"name",type:"string"},{internalType:"string",name:"symbol",type:"string"},{internalType:"uint256",name:"totalSupply",type:"uint256"},{internalType:"uint8",name:"decimals",type:"uint8"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalBuilt",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"withdraw",outputs:[],stateMutability:"nonpayable",type:"function"}];
function init(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return contract=new ethers.Contract(contractAddress,abi,provider),contractSign=contract.connect(signer),a.yield(contract.cost(),2);if(3!=a.nextAddress)return builderCost=a.yieldResult,$("#buildercost").html(ethers.utils.formatEther(builderCost)),a.yield(contract.edge(),3);builderEdge=a.yieldResult;$("#builderedge").html(Number(builderEdge)/10);myAddress&&($("#newbeneficiary").val(myAddress),checkBen());
makeTable();a.jumpToEnd()})}
function makeTable(){var a,b,c,f,e,g,d,h,n,q,t,w,l,v,r,u,y,z,x,A,p,C;return $jscomp.asyncExecutePromiseGeneratorProgram(function(m){switch(m.nextAddress){case 1:return a="",m.yield(contract.myContracts({from:myAddress}),2);case 2:b=m.yieldResult;if(!(0<b.length)){m.jumpTo(3);break}c=b;f=0;case 4:if(!(f<c.length)){m.jumpTo(3);break}e=c[f];g=new ethers.Contract(e,abiSale,provider);return m.yield(g.tokenAddress(),7);case 7:return d=m.yieldResult,m.yield(g.startTime(),8);case 8:return h=m.yieldResult,
m.yield(g.endTime(),9);case 9:return n=m.yieldResult,m.yield(g.remaining(),10);case 10:return q=m.yieldResult,m.yield(g.checkQty(q),11);case 11:return t=m.yieldResult,m.yield(g.saleOn(),12);case 12:return w=m.yieldResult,m.yield(g.canClaim(),13);case 13:return l=m.yieldResult,m.yield(g.unclaimed(),14);case 14:return v=m.yieldResult,u=new ethers.Contract(d,abiToken,provider),m.yield(u.name(),15);case 15:return y=m.yieldResult,m.yield(u.symbol(),16);case 16:return z=m.yieldResult,m.yield(u.balanceOf(e),
17);case 17:x=m.yieldResult;Date.now()>1E3*Number(n)||0==Number(t)?(r="Finished",r=l?r+"<br>Claim unlocked":r+"<br>Claim locked",Number(x)<Number(v)&&(r+='<br><span class="err">Add tokens</span>')):Date.now()<1E3*Number(h)?(r="Upcoming",Number(x)<Number(t)&&(r+='<br><span class="err">Add tokens</span>')):Date.now()>1E3*Number(h)&&Date.now()<1E3*Number(n)&&(r=w?"Active":'<span class="err">Paused</span>',Number(x)<Number(t)&&(r+=' <span class="err">Add tokens</span>'));A=Number(f+1);a=a+'<div class="salerow" title="Click to open admin panel" onclick="admin(\''+
e+'\')"><div class="saleno">'+A+'</div><div class="saleaddress">'+e+'</div><div class="saletoken">'+y+"("+z+')</div><div class="salestatus">'+r+"</div>";a+="</div>";f++;m.jumpTo(4);break;case 3:return curnet==mainnet||curnet==mainnetAlt?contractAddressV1=contractAddressMain1:curnet==testnet&&(contractAddressV1=contractAddressTest1),contractV1=new ethers.Contract(contractAddressV1,abi,provider),m.yield(contractV1.myContracts({from:myAddress}),18);case 18:p=m.yieldResult;if(!(0<p.length)){m.jumpTo(19);
break}C=p;f=0;case 20:if(!(f<C.length)){m.jumpTo(19);break}e=C[f];g=new ethers.Contract(e,abiSale,provider);return m.yield(g.tokenAddress(),23);case 23:return d=m.yieldResult,m.yield(g.startTime(),24);case 24:return h=m.yieldResult,m.yield(g.endTime(),25);case 25:return n=m.yieldResult,m.yield(g.remaining(),26);case 26:return q=m.yieldResult,m.yield(g.checkQty(q),27);case 27:return t=m.yieldResult,m.yield(g.saleOn(),28);case 28:return w=m.yieldResult,m.yield(g.canClaim(),29);case 29:return l=m.yieldResult,
m.yield(g.unclaimed(),30);case 30:return v=m.yieldResult,u=new ethers.Contract(d,abiToken,provider),m.yield(u.name(),31);case 31:return y=m.yieldResult,m.yield(u.symbol(),32);case 32:return z=m.yieldResult,m.yield(u.balanceOf(e),33);case 33:x=m.yieldResult;Date.now()>1E3*Number(n)||0==Number(t)?(r="Finished",r=l?r+"<br>Claim unlocked":r+"<br>Claim locked",Number(x)<Number(v)&&(r+='<br><span class="err">Add tokens</span>')):Date.now()<1E3*Number(h)?(r="Upcoming",Number(x)<Number(t)&&(r+='<br><span class="err">Add tokens</span>')):
Date.now()>1E3*Number(h)&&Date.now()<1E3*Number(n)&&(r=w?"Active":'<span class="err">Paused</span>',Number(x)<Number(t)&&(r+=' <span class="err">Add tokens</span>'));A=Number(f+1);a=a+'<div class="salerow" title="Click to open admin panel" onclick="admin(\''+e+'\')"><div class="saleno">'+A+'</div><div class="saleaddress">'+e+'</div><div class="saletoken">'+y+"("+z+')</div><div class="salestatus">'+r+"</div>";a+="</div>";f++;m.jumpTo(20);break;case 19:$("#mycontr").html(a),m.jumpToEnd()}})}
$("#mytokens").click(function(){var a,b,c,f,e,g,d,h,n,q,t,w;return $jscomp.asyncExecutePromiseGeneratorProgram(function(l){switch(l.nextAddress){case 1:return $("#mytoks").show(),curnet==mainnet||curnet==mainnetAlt?(contractTokenBuilder1=contractTokenBuilder1Main,contractTokenBuilder2=contractTokenBuilder2Main,contractTokenBuilder3=contractTokenBuilder3Main,contractTokenBuilder4=contractTokenBuilder4Main,contractTokenBuilder5=contractTokenBuilder5Main):curnet==testnet&&(contractTokenBuilder1=contractTokenBuilder1Test,
contractTokenBuilder2=contractTokenBuilder2Test,contractTokenBuilder3=contractTokenBuilder3Test,contractTokenBuilder4=contractTokenBuilder4Test,contractTokenBuilder5=contractTokenBuilder5Test),contractToken1=new ethers.Contract(contractTokenBuilder1,abiTokenBuilder,provider),contractToken2=new ethers.Contract(contractTokenBuilder2,abiTokenBuilder,provider),contractToken3=new ethers.Contract(contractTokenBuilder3,abiTokenBuilder,provider),contractToken4=new ethers.Contract(contractTokenBuilder4,abiTokenBuilder,
provider),contractToken5=new ethers.Contract(contractTokenBuilder5,abiTokenBuilder,provider),a="",l.yield(contractToken1.myTokens({from:myAddress}),2);case 2:b=l.yieldResult;if(b==[]){l.jumpTo(3);break}c=b;f=0;case 4:if(!(f<c.length)){l.jumpTo(3);break}e=c[f];g=new ethers.Contract(e,abiToken,provider);return l.yield(g.name(),7);case 7:return d=l.yieldResult,l.yield(g.symbol(),8);case 8:h=l.yieldResult;a=a+'<tr><td><a title="View on explorer" target="_blank" href="'+tracker+"token/"+e+'">'+e+"</a></td><td>"+
d+"</td><td>"+h+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+e+"')\">choose</span></td>";a+="</tr>";f++;l.jumpTo(4);break;case 3:return l.yield(contractToken2.myTokens({from:myAddress}),9);case 9:n=l.yieldResult;if(n==[]){l.jumpTo(10);break}c=n;f=0;case 11:if(!(f<c.length)){l.jumpTo(10);break}e=c[f];g=new ethers.Contract(e,abiToken,provider);return l.yield(g.name(),14);case 14:return d=l.yieldResult,l.yield(g.symbol(),15);case 15:h=l.yieldResult;a=a+'<tr><td><a title="View on explorer" target="_blank" href="'+
tracker+"token/"+e+'">'+e+"</a></td><td>"+d+"</td><td>"+h+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+e+"')\">choose</span></td>";a+="</tr>";f++;l.jumpTo(11);break;case 10:return l.yield(contractToken3.myTokens({from:myAddress}),16);case 16:q=l.yieldResult;if(q==[]){l.jumpTo(17);break}c=q;f=0;case 18:if(!(f<c.length)){l.jumpTo(17);break}e=c[f];g=new ethers.Contract(e,abiToken,provider);return l.yield(g.name(),21);case 21:return d=l.yieldResult,l.yield(g.symbol(),
22);case 22:h=l.yieldResult;a=a+'<tr><td><a title="View on explorer" target="_blank" href="'+tracker+"token/"+e+'">'+e+"</a></td><td>"+d+"</td><td>"+h+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+e+"')\">choose</span></td>";a+="</tr>";f++;l.jumpTo(18);break;case 17:return l.yield(contractToken4.myTokens({from:myAddress}),23);case 23:t=l.yieldResult;if(t==[]){l.jumpTo(24);break}c=t;f=0;case 25:if(!(f<c.length)){l.jumpTo(24);break}e=c[f];g=new ethers.Contract(e,abiToken,
provider);return l.yield(g.name(),28);case 28:return d=l.yieldResult,l.yield(g.symbol(),29);case 29:h=l.yieldResult;a=a+'<tr><td><a title="View on explorer" target="_blank" href="'+tracker+"token/"+e+'">'+e+"</a></td><td>"+d+"</td><td>"+h+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+e+"')\">choose</span></td>";a+="</tr>";f++;l.jumpTo(25);break;case 24:return l.yield(contractToken5.myTokens({from:myAddress}),30);case 30:w=l.yieldResult;if(w==[]){l.jumpTo(31);break}c=
w;f=0;case 32:if(!(f<c.length)){l.jumpTo(31);break}e=c[f];g=new ethers.Contract(e,abiToken,provider);return l.yield(g.name(),35);case 35:return d=l.yieldResult,l.yield(g.symbol(),36);case 36:h=l.yieldResult;a=a+'<tr><td><a title="View on explorer" target="_blank" href="'+tracker+"token/"+e+'">'+e+"</a></td><td>"+d+"</td><td>"+h+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+e+"')\">choose</span></td>";a+="</tr>";f++;l.jumpTo(32);break;case 31:$.ajax({type:"get",url:"/bsc/tokenwithbuyback/php/load.php",
data:{net:curnet,wallet:myAddress},contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,success:function(v){return $jscomp.asyncExecutePromiseGeneratorProgram(function(r){$.each(v,function(u,y){var z,x,A;return $jscomp.asyncExecutePromiseGeneratorProgram(function(p){if(1==p.nextAddress)return z=new ethers.Contract(y.contract,abiToken,provider),p.yield(z.name(),2);if(3!=p.nextAddress)return x=p.yieldResult,p.yield(z.symbol(),3);A=p.yieldResult;console.log(x,A);a=a+'<tr><td><a title="View on explorer" target="_blank" href="'+
tracker+"token/"+y.contract+'">'+y.contract+"</a></td><td>"+x+"</td><td>"+A+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+y.contract+"')\">choose</span></td>";a+="</tr>";$("#strHtmlTokens").html(a);p.jumpToEnd()})});r.jumpToEnd()})},error:function(v){}}),$("#strHtmlTokens").html(a),l.jumpToEnd()}})});function choose(a){$("#newtknaddress").val(a);$("#mytoks").hide();checkToken()}$("#newtknaddress").on("keyup input",checkToken);
function checkToken(){var a,b,c,f,e;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){switch(g.nextAddress){case 1:$("#tokendata").html("");$("#tokens").html("tokens");a=$("#newtknaddress").val();if(""==a||!ethers.utils.isAddress(a))return""==a?$("#tokendata").html(""):$("#tokendata").html('<span class="err">Error: check token address!</span>'),$("#tokens").html("tokens"),g["return"](!1);$("#errors").html("");g.setCatchFinallyBlocks(3);b=new ethers.Contract(a,abiToken,provider);return g.yield(b.name(),
5);case 5:return c=g.yieldResult,g.yield(b.symbol(),6);case 6:f=g.yieldResult;if(c&&f)return $("#tokendata").html('<span style="color: green">'+c+" ("+f+")</span>"),$("#tokens").html(f),g["return"](!0);$("#tokendata").html('<span class="err">Error: check token address!</span>');$("#tokens").html("tokens");return g["return"](!1);case 3:return e=g.enterCatchBlock(),console.log(e),$("#tokendata").html('<span class="err">Error: check token address!</span>'),$("#tokens").html("tokens"),g["return"](!1)}})}
$("#newstartdate").on("keyup input",checkTime);$("#newenddate").on("keyup input",checkTime);
function checkTime(){$("#duration").html("");var a=new Date($("#newstartdate").val()),b=new Date($("#newenddate").val());if(a&&b){if(b>=a&&b>=Date.now())return a=Number(b)-Number(a),$("#duration").html('<span style="color:green">Duration: '+dhm(a)+"</span>"),!0;b>=a&&b<Date.now()?$("#duration").html('<span class="err">End date must be in the future!</span>'):b<a&&b>Date.now()?$("#duration").html('<span class="err">End date must be later than start date!</span>'):b<a&&b<Date.now()?$("#duration").html('<span class="err">End date must be later than start date and in the future!</span>'):
$("#duration").html("");return!1}$("#duration").html("");return!1}function dhm(a){days=Math.floor(a/864E5);daysms=a%864E5;hours=Math.floor(daysms/36E5);hoursms=a%36E5;minutes=Math.floor(hoursms/6E4);minutesms=a%6E4;return days+" days "+hours+" hours "+minutes+" minutes"}$("#afterend").on("change",function(){$("#afterend").is(":checked")?$("#newunlockdate").hide():$("#newunlockdate").show()});$("#unlimited").on("change",function(){$("#unlimited").is(":checked")?$("#limits").hide():$("#limits").show()});
$("#newbeneficiary").on("keyup input",checkBen);function checkBen(){$("#isben").html("");var a=$("#newbeneficiary").val();if(a&&""!=a){if(ethers.utils.isAddress(a))return a==myAddress?$("#isben").html('<span style="color:green">Beneficiary is you</span>'):$("#isben").html(""),!0;$("#isben").html('<span class="err">Please check beneficiary address!</span>');return!1}$("#isben").html("");return!1}$("#benme").click(function(){myAddress&&($("#newbeneficiary").val(myAddress),checkBen())});
function admin(a){var b,c,f,e,g,d,h,n,q,t,w,l,v,r,u,y,z,x,A,p,C,m,E,F,H,I,D,J,K,L,M,N,O,P,Q,R,S,T,G,B;return $jscomp.asyncExecutePromiseGeneratorProgram(function(k){switch(k.nextAddress){case 1:return $("#admin").show(),$("#todo").html(""),$("#supplyTokens").hide(),$("#thisAddr").html(a),$(".uiAddr").html(a),$("#uiAddrLnk").html(tracker+"address/"+a),$("#thisSaleAddress").html(a),$("#thisSaleAddress").attr("href",tracker+"address/"+a),$("#thisSaleAddress2").html(a),$("#thisSaleAddress2").attr("href",
tracker+"address/"+a),thisAddress=a,contractThis=new ethers.Contract(a,abiSale,provider),contractThisSign=contractThis.connect(signer),k.yield(contractThis.tokenAddress(),2);case 2:return thisTokenAddress=k.yieldResult,$("#thisTokenAddress").html(thisTokenAddress),$("#thisTokenAddress").attr("href",tracker+"token/"+thisTokenAddress),$(".tokenAddressUI").html(thisTokenAddress),$("#tokenAddressUIlnk").html(tracker+"token/"+thisTokenAddress),contractThisToken=new ethers.Contract(thisTokenAddress,abiToken,
provider),contractThisTokenSign=contractThisToken.connect(signer),k.yield(contractThisToken.name(),3);case 3:return b=k.yieldResult,$("#thisName").html(b),$("#tokenNameUI").html(b),k.yield(contractThisToken.symbol(),4);case 4:return thisSymbol=k.yieldResult,$(".thisSymbol").html(thisSymbol),k.yield(contractThisToken.decimals(),5);case 5:return thisDecimals=k.yieldResult,$("#thisDec").html(Number(thisDecimals)),$("#tokenDecimalsUI").html(Number(thisDecimals)),k.yield(contractThisToken.totalSupply(),
6);case 6:return c=k.yieldResult,$("#tokenSupplyUI").html(Number(ethers.utils.formatUnits(c,thisDecimals))),k.yield(contractThisToken.balanceOf(thisAddress),7);case 7:return f=k.yieldResult,$("#tokenbalance").html(Number(ethers.utils.formatUnits(f,thisDecimals))),k.yield(contractThis.owner(),8);case 8:return e=k.yieldResult,$("#thisOwner").html(e),k.yield(contractThis.beneficiary(),9);case 9:return g=k.yieldResult,$("#thisBen").html(g),k.yield(contractThis.rate(),10);case 10:return d=k.yieldResult,
h=ethers.utils.formatUnits(d,thisDecimals),$("#thisRate").html(h),n=1/Number(h),$("#thisPrice").html(n),k.yield(contractThis.hardcap(),11);case 11:return thisHardcap=k.yieldResult,$(".thisHardcap").html(ethers.utils.formatEther(thisHardcap)),k.yield(contractThis.checkQty(thisHardcap),12);case 12:return q=k.yieldResult,$(".thisQty").html(ethers.utils.formatUnits(q,thisDecimals)),k.yield(contractThis.purchaseLimit(),13);case 13:return t=k.yieldResult,$("#thisMax").html(ethers.utils.formatEther(t)),
k.yield(contractThis.refPercent(),14);case 14:return w=k.yieldResult,$("#thisRef").html(Number(w)/10),k.yield(contractThis.refTotal(),15);case 15:return l=k.yieldResult,$("#thisRefTotal").html(ethers.utils.formatEther(l)),k.yield(contractThis.totalSold(),16);case 16:return v=k.yieldResult,$("#thisSold").html(ethers.utils.formatUnits(v,thisDecimals)),k.yield(contractThis.totalRaised(),17);case 17:return r=k.yieldResult,$("#thisRaised").html(ethers.utils.formatEther(r)),k.yield(contractThis.remaining(),
18);case 18:return u=k.yieldResult,$("#thisRemaining").html(ethers.utils.formatEther(u)),$("#progress").attr("max",thisHardcap),$("#progress").attr("value",r),k.yield(contractThis.checkQty(u),19);case 19:return thisUnsoldQty=k.yieldResult,$("#thisUnsoldQty").html(ethers.utils.formatUnits(thisUnsoldQty,thisDecimals)),k.yield(provider.getBalance(a),20);case 20:return thisBalance=k.yieldResult,available=ethers.utils.formatEther(thisBalance),$("#thisBalance").html(available),k.yield(contractThis.startTime(),
21);case 21:return y=k.yieldResult,z=new Date(1E3*Number(y)),$("#thisStart").html(z),k.yield(contractThis.endTime(),22);case 22:return x=k.yieldResult,A=new Date(1E3*Number(x)),$("#thisEnd").html(A),p=Number(A)-Number(z),$("#thisDuration").html(dhm(p)),k.yield(contractThis.claimTime(),23);case 23:return C=k.yieldResult,m=new Date(1E3*Number(C)),$("#thisClaim").html(m),k.yield(contractThis.claimAfterHCAllowed(),24);case 24:return E=k.yieldResult,k.yield(contractThis.delay(),25);case 25:return F=k.yieldResult,
E?(0<F?$("#thisClaimAfterHC").html("Can be claimed after hardcap is reached +"+dhm(1E3*Number(F))):$("#thisClaimAfterHC").html("Can be claimed immediately after hardcap is reached"),$("#allowClaim").hide(),$("#disallowClaim").show()):($("#thisClaimAfterHC").html("Can be claimed only when unlock time comes"),$("#allowClaim").show(),$("#disallowClaim").hide()),k.yield(contractThis.ended(),26);case 26:return H=k.yieldResult,I=new Date(1E3*Number(H)),$("#endedUI").html(I),k.yield(contractThis.unclaimed(),
27);case 27:return D=k.yieldResult,$("#thisUnclaimed").html(ethers.utils.formatUnits(D,thisDecimals)),J=ethers.utils.formatUnits(f,thisDecimals),K=ethers.utils.formatUnits(D,thisDecimals),L=Number(J)-Number(K),$("#availableTok").html(L),k.yield(contractThis.canClaim(),28);case 28:return(M=k.yieldResult)?$("#canClaim").html('<span style="color:green">Tokens are unlocked and can be claimed</span>'):$("#canClaim").html('<span style="color:red">Tokens are locked</span>'),k.yield(contractThis.hardCapFixed(),
29);case 29:return(N=k.yieldResult)?($("#hardCapFixed").html('<span style="color:red">Hardcap is fixed and can not be changed</span>'),$("#fixHardCap").hide(),$("#admHardcap").hide()):($("#hardCapFixed").html('<span style="color:green">Hardcap can be changed</span>'),$("#fixHardCap").show(),$("#admHardcap").show()),k.yield(contractThis.purchaseLimitFixed(),30);case 30:return(O=k.yieldResult)?($("#purchaseLimitFixed").html('<span style="color:red">Purchase limit is fixed and can not be changed</span>'),
$("#fixPurchaseLimit").hide(),$("#admMax").hide()):($("#purchaseLimitFixed").html('<span style="color:green">Purchase limit can be changed</span>'),$("#fixPurchaseLimit").show(),$("#admMax").show()),k.yield(contractThis.rateFixed(),31);case 31:return(P=k.yieldResult)?($("#rateFixed").html('<span style="color:red">Rate is fixed and can not be changed</span>'),$("#fixRate").hide(),$("#admRate").hide()):($("#rateFixed").html('<span style="color:green">Rate can be changed</span>'),$("#fixRate").show(),
$("#admRate").show()),k.yield(contractThis.refPercentFixed(),32);case 32:return(Q=k.yieldResult)?($("#refPercentFixed").html('<span style="color:red">Referral commission is fixed and can not be changed</span>'),$("#fixRefPercent").hide(),$("#admRef").hide()):($("#refPercentFixed").html('<span style="color:green">Referral commission can be changed</span>'),$("#fixRefPercent").show(),$("#admRef").show()),k.yield(contractThis.saleTimeFixed(),33);case 33:return(R=k.yieldResult)?($("#saleTimeFixed").html('<span style="color:red">Sale time is fixed and can not be changed</span>'),
$("#fixSaleTime").hide(),$(".admTime").hide()):($("#saleTimeFixed").html('<span style="color:green">Sale time can be changed</span>'),$("#fixSaleTime").show(),$(".admTime").show()),k.yield(contractThis.claimTermsFixed(),34);case 34:return(S=k.yieldResult)?($("#claimTermsFixed").html('<span style="color:red">Terms of token claim is fixed and can not be changed</span>'),$("#fixClaimTerms").hide(),$("#admClaim").hide()):($("#claimTermsFixed").html('<span style="color:green">Terms of token claim can be changed</span>'),
$("#fixClaimTerms").show(),$("#admClaim").show()),k.yield(contractThis.pausable(),35);case 35:return(T=k.yieldResult)?($("#pausable").html('<span style="color:green">The contract is pausable</span>'),$("#makeUnpausable").show(),$("#admPause").show()):($("#pausable").html('<span style="color:red">Contract can not be paused</span>'),$("#makeUnpausable").hide(),$("#admPause").hide()),k.yield(contractThis.saleOn(),36);case 36:(G=k.yieldResult)?($("#saleOn").hide(),$("#saleOff").show()):($("#saleOn").show(),
$("#saleOff").hide()),Date.now()>1E3*Number(x)||0==Number(thisUnsoldQty)?(B="Finished",B=E?B+"<br>Claim unlocked":B+"<br>Claim locked",Number(f)<Number(D)&&(B+='<br><span class="err">Add tokens to sale contract</span>',$("#addToPresaleQty").val(Number(ethers.utils.formatUnits(D,thisDecimals))),$("#supplyTokens").show())):Date.now()<1E3*Number(y)?(B="Upcoming",Number(f)<Number(thisUnsoldQty)&&(B+='<br><span class="err">Add tokens to sale contract</span>',$("#addToPresaleQty").val(Number(ethers.utils.formatUnits(thisUnsoldQty,
thisDecimals))),$("#supplyTokens").show()),G||(B+='<br><span class="err">Paused</span>')):Date.now()>1E3*Number(y)&&Date.now()<1E3*Number(x)&&(B=G?"Active":'<span class="err">Paused</span>',Number(f)<Number(thisUnsoldQty)&&(B+=' <span class="err">Add tokens to sale contract</span>',$("#addToPresaleQty").val(Number(ethers.utils.formatUnits(thisUnsoldQty,thisDecimals))),$("#supplyTokens").show())),$("#thisStatus").html(B),curnet==testnet?($("#istest").html("true"),$("#switchbtnid").html("addTestBSC"),
$("#switchbtn").html("To BSC Testnet")):($("#istest").html("false"),$("#switchbtnid").html("addMainBSC"),$("#switchbtn").html("To BSC Mainnet")),getQR(a),$("#uiAddr").attr("href","https://create.metaexchange.finance/bsc/tokensaleclaimtimeref/tokensale.html?id="+thisAddress+"&net="+curnet),$("#uiAddr").html("https://create.metaexchange.finance/bsc/tokensaleclaimtimeref/tokensale.html?id="+thisAddress+"&net="+curnet),k.jumpToEnd()}})}$("#setnewrate").click(setRate);
function setRate(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return(a=$("#thisnewrate").val())?b.yield(contractThisSign.setRate(String(ethers.utils.parseUnits(a,thisDecimals))),3):b.jumpTo(0);if(4!=b.nextAddress)return tx=b.yieldResult,b.yield(tx.wait(),4);admin(thisAddress);b.jumpToEnd()})}$("#setnewhc").click(setHardcap);
function setHardcap(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return(a=$("#thisnewhc").val())?b.yield(contractThisSign.setHardcap(String(ethers.utils.parseEther(a))),3):b.jumpTo(0);if(4!=b.nextAddress)return tx=b.yieldResult,b.yield(tx.wait(),4);admin(thisAddress);b.jumpToEnd()})}$("#setnewmax").click(setLimit);
function setLimit(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return(a=$("#thisnewmax").val())?b.yield(contractThisSign.setLimit(String(ethers.utils.parseEther(a))),3):b.jumpTo(0);if(4!=b.nextAddress)return tx=b.yieldResult,b.yield(tx.wait(),4);admin(thisAddress);b.jumpToEnd()})}$("#setnewmax1").click(setLimit1);
function setLimit1(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return(a=thisHardcap)?b.yield(contractThisSign.setLimit(String(a)),3):b.jumpTo(0);if(4!=b.nextAddress)return tx=b.yieldResult,b.yield(tx.wait(),4);admin(thisAddress);b.jumpToEnd()})}$("#setnewstart").click(setStartTime);
function setStartTime(){var a,b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress){a=$("#thisnewstart").val();if(!a)return c.jumpTo(0);b=Date.parse(a);return c.yield(contractThisSign.setStartTime(String(Number(b)/1E3)),3)}if(4!=c.nextAddress)return tx=c.yieldResult,c.yield(tx.wait(),4);admin(thisAddress);c.jumpToEnd()})}$("#setnewend").click(setEndTime);
function setEndTime(){var a,b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress){a=$("#thisnewend").val();if(!a)return c.jumpTo(0);b=Date.parse(a);return c.yield(contractThisSign.setEndTime(String(Number(b)/1E3)),3)}if(4!=c.nextAddress)return tx=c.yieldResult,c.yield(tx.wait(),4);admin(thisAddress);c.jumpToEnd()})}$("#setnewclaim").click(setClaimTime);
function setClaimTime(){var a,b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress){a=$("#thisnewclaim").val();if(!a)return c.jumpTo(0);b=Date.parse(a);return c.yield(contractThisSign.setClaimTime(String(Number(b)/1E3)),3)}if(4!=c.nextAddress)return tx=c.yieldResult,c.yield(tx.wait(),4);admin(thisAddress);c.jumpToEnd()})}$("#allowClaim").click(allowClaim);
function allowClaim(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return a.yield(contractThisSign.allowClaimAfterHC(!0),2);if(3!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),3);admin(thisAddress);a.jumpToEnd()})}$("#disallowClaim").click(disallowClaim);
function disallowClaim(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return a.yield(contractThisSign.allowClaimAfterHC(!1),2);if(3!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),3);admin(thisAddress);a.jumpToEnd()})}$("#setnewdelay").click(lockAfterHC);
function lockAfterHC(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return(a=$("#thisnewdelay").val())?b.yield(contractThisSign.lockAfterHC(String(Number(a)*hourms)),3):b.jumpTo(0);if(4!=b.nextAddress)return tx=b.yieldResult,b.yield(tx.wait(),4);admin(thisAddress);b.jumpToEnd()})}$("#setnewref").click(setRefPercent);
function setRefPercent(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return(a=$("#thisnewref").val())?b.yield(contractThisSign.setRefPercent(String(10*Number(a))),3):b.jumpTo(0);if(4!=b.nextAddress)return tx=b.yieldResult,b.yield(tx.wait(),4);admin(thisAddress);b.jumpToEnd()})}$("#saleOn").click(saleOn);
function saleOn(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return $("#todo").html(""),0<Number(thisUnsoldQty)?a.yield(contractThisSign.saleOnOff(!0),3):($("#todo").html('<span class="err">Hard cap has been reached!</span>'),a.jumpTo(0));if(4!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),4);admin(thisAddress);a.jumpToEnd()})}$("#saleOff").click(saleOff);
function saleOff(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return a.yield(contractThisSign.saleOnOff(!1),2);if(3!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),3);admin(thisAddress);a.jumpToEnd()})}$("#fixHardCap").click(fixHardCap);
function fixHardCap(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return a.yield(contractThisSign.fixHardCap(),2);if(3!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),3);admin(thisAddress);a.jumpToEnd()})}$("#fixPurchaseLimit").click(fixPurchaseLimit);
function fixPurchaseLimit(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return a.yield(contractThisSign.fixPurchaseLimit(),2);if(3!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),3);admin(thisAddress);a.jumpToEnd()})}$("#fixRate").click(fixRate);
function fixRate(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return a.yield(contractThisSign.fixRate(),2);if(3!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),3);admin(thisAddress);a.jumpToEnd()})}$("#fixRefPercent").click(fixRefPercent);
function fixRefPercent(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return a.yield(contractThisSign.fixRefPercent(),2);if(3!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),3);admin(thisAddress);a.jumpToEnd()})}$("#fixSaleTime").click(fixSaleTime);
function fixSaleTime(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return a.yield(contractThisSign.fixSaleTime(),2);if(3!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),3);admin(thisAddress);a.jumpToEnd()})}$("#fixClaimTerms").click(fixClaimTerms);
function fixClaimTerms(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return a.yield(contractThisSign.fixClaimTerms(),2);if(3!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),3);admin(thisAddress);a.jumpToEnd()})}$("#makeUnpausable").click(makeUnpausable);
function makeUnpausable(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return a.yield(contractThisSign.makeUnpausable(),2);if(3!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),3);admin(thisAddress);a.jumpToEnd()})}$("#withdrawTok").click(withdrawTokens);
function withdrawTokens(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return(a=$("#toWithdrawTok").val())?b.yield(contractThisSign.withdrawTokens(String(ethers.utils.parseUnits(a,thisDecimals))),3):b.jumpTo(0);if(4!=b.nextAddress)return tx=b.yieldResult,b.yield(tx.wait(),4);admin(thisAddress);b.jumpToEnd()})}$("#thisnewowner").on("keyup input",checkOwner);
function checkOwner(){$("#checkthisowner").html("");var a=$("#thisnewowner").val();if(a&&""!=a&&ethers.utils.isAddress(a))return $("#checkthisowner").html(""),!0;a&&""!=a&&!ethers.utils.isAddress(a)?$("#checkthisowner").html('<span class="err">Incorrect address!</span>'):$("#checkthisowner").html("");return!1}$("#setnewowner").click(setOwner);
function setOwner(){var a,b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress)return $("#checkthisowner").html(""),a=checkOwner(),b=$("#thisnewowner").val(),a?c.yield(contractThisSign.setOwner(String(b)),3):($("#checkthisowner").html('<span class="err">Incorrect address!</span>'),c.jumpTo(0));if(4!=c.nextAddress)return tx=c.yieldResult,c.yield(tx.wait(),4);admin(thisAddress);c.jumpToEnd()})}$("#thisnewben").on("keyup input",checkThisBen);
function checkThisBen(){$("#checkthisben").html("");var a=$("#thisnewben").val();if(a&&""!=a&&ethers.utils.isAddress(a))return $("#checkthisben").html(""),!0;a&&""!=a&&!ethers.utils.isAddress(a)?$("#checkthisben").html('<span class="err">Incorrect address!</span>'):$("#checkthisben").html("");return!1}$("#setnewben").click(setBen);
function setBen(){var a,b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress)return $("#checkthisben").html(""),a=checkBen(),b=$("#thisnewben").val(),a?c.yield(contractThisSign.setBeneficiary(String(b)),3):($("#checkthisben").html('<span class="err">Incorrect address!</span>'),c.jumpTo(0));if(4!=c.nextAddress)return tx=c.yieldResult,c.yield(tx.wait(),4);admin(thisAddress);c.jumpToEnd()})}
$("#withdrawBnb").click(function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return 0<Number(thisBalance)?a.yield(contractThisSign.withdrawBNB(),3):a.jumpTo(0);if(4!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),4);admin(thisAddress);a.jumpToEnd()})});$("#addToken").click(function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){watchToken(thisTokenAddress,thisSymbol,thisDecimals);a.jumpToEnd()})});
function watchToken(a,b,c){return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){ethereum.request({method:"wallet_watchAsset",params:{type:"ERC20",options:{address:String(a),symbol:String(b),decimals:String(c)}}});f.jumpToEnd()})}
$("#buildbtnflat").click(function(){var a,b,c,f,e,g,d,h,n,q,t,w,l,v,r,u,y,z,x,A;return $jscomp.asyncExecutePromiseGeneratorProgram(function(p){switch(p.nextAddress){case 1:$("#errors").html("");if(!myAddress){p.jumpTo(0);break}return p.yield(provider.getBalance(myAddress),3);case 3:a=p.yieldResult;if(!(Number(a)>Number(builderCost))){$("#errors").html("Insufficient balance in your wallet! Contract creation cost is "+ethers.utils.formatEther(builderCost)+" BNB + network fees (gas)!");p.jumpTo(0);break}return p.yield(checkToken(),
5);case 5:b=p.yieldResult;c=checkTime();f=checkBen();e=$("#newrate").val();g=$("#newhardcap").val();d=$("#newmax").val();$("#unlimited").is(":checked")&&(d=g);if(!(b&&c&&f&&e&&0<Number(e)&&10>=Number(e)^18&&g&&0<Number(g)&&d)){checkToken();checkTime();checkBen();$("#errors").html("Error: fields are empty or incorrect!");p.jumpTo(0);break}$("#errors").html("");y=$("#newtknaddress").val();z=new ethers.Contract(y,abiToken,provider);return p.yield(z.decimals(),7);case 7:return x=p.yieldResult,w=$("#newstartdate").val(),
l=Date.parse(w),v=$("#newenddate").val(),r=Date.parse(v),(h=$("#afterend").is(":checked")?r:Date.parse($("#newunlockdate").val()))&&""!=h||(h=r),n=$("#allow").is(":checked")?!0:!1,(q=$("#newafterhc").val())&&""!=q||(q=0),(t=$("#newref").val())&&""!=t||(t=0),u=$("#newbeneficiary").val(),u&&""!=u||(u=myAddress,$("#newbeneficiary").val(u)),console.log(b,c,f,e,g,d,h,n,q,t,w,v),A=[String(ethers.utils.parseUnits(e,x)),String(ethers.utils.parseEther(g)),String(ethers.utils.parseEther(d)),String(10*Number(t)),
String(Number(l)/1E3),String(Number(r)/1E3),String(Number(h)/1E3),String(Number(q)*hourms)],p.yield(contractSign.createTokenSale(String(y),A,String(u),n,!1,{value:builderCost}),8);case 8:return tx=p.yieldResult,p.yield(tx.wait(),9);case 9:init(),p.jumpToEnd()}})});
$("#buildbtnroyalty").click(function(){var a,b,c,f,e,g,d,h,n,q,t,w,l,v,r,u,y,z,x,A;return $jscomp.asyncExecutePromiseGeneratorProgram(function(p){switch(p.nextAddress){case 1:$("#errors").html("");if(!myAddress){p.jumpTo(0);break}return p.yield(provider.getBalance(myAddress),3);case 3:a=p.yieldResult;if(!(0<Number(a))){$("#errors").html("Insufficient balance in your wallet! Contract creation is free but you need some small amount to pay network fees (gas)!");p.jumpTo(0);break}return p.yield(checkToken(),
5);case 5:b=p.yieldResult;c=checkTime();f=checkBen();e=$("#newrate").val();g=$("#newhardcap").val();d=$("#newmax").val();$("#unlimited").is(":checked")&&(d=g);if(!(b&&c&&f&&e&&0<Number(e)&&g&&0<Number(g)&&d)){checkToken();checkTime();checkBen();$("#errors").html("Error: fields are empty or incorrect!");p.jumpTo(0);break}$("#errors").html("");y=$("#newtknaddress").val();z=new ethers.Contract(y,abiToken,provider);return p.yield(z.decimals(),7);case 7:return x=p.yieldResult,w=$("#newstartdate").val(),
l=Date.parse(w),v=$("#newenddate").val(),r=Date.parse(v),(h=$("#afterend").is(":checked")?r:Date.parse($("#newunlockdate").val()))&&""!=h||(h=r),n=$("#allow").is(":checked")?!0:!1,(q=$("#newafterhc").val())&&""!=q||(q=0),(t=$("#newref").val())&&""!=t||(t=0),u=$("#newbeneficiary").val(),u&&""!=u||(u=myAddress,$("#newbeneficiary").val(u)),console.log(b,c,f,e,g,d,h,n,q,t,w,v),A=[String(ethers.utils.parseUnits(e,x)),String(ethers.utils.parseEther(g)),String(ethers.utils.parseEther(d)),String(10*Number(t)),
String(Number(l)/1E3),String(Number(r)/1E3),String(Number(h)/1E3),String(Number(q)*hourms)],p.yield(contractSign.createTokenSale(String(y),A,String(u),n,!0),8);case 8:return tx=p.yieldResult,p.yield(tx.wait(),9);case 9:init(),p.jumpToEnd()}})});$("#newrate").on("keyup input",function(){$("#tokenprice").html("");var a=$("#newrate").val();a&&""!=a&&0<Number(a)&&(a=1/Number(a),$("#tokenprice").html('<span style="color: green">1 token = '+Number(a)+"BNB</span>"));getQty()});
$("#newhardcap").on("keyup input",getQty);function getQty(){$("#quantity").html("");var a=$("#newhardcap").val(),b=$("#newrate").val();a&&""!=a&&b&&""!=b&&(a=Number(a)*Number(b),$("#quantity").html('<span style="color: green"> ~ '+Number(a)+"tokens</span>"))}function getQR(a){a=encodeURIComponent(a);$("#refqr").html('<img style="max-width: 80%" src="https://create.metaexchange.finance/php/qr.php?data='+a+'">');$("#refd").attr("href","https://create.metaexchange.finance/php/qr.php?data="+a)}
$("#copyaddress").on("click",function(){var a=$("<textarea>");$("body").append(a);a.val($("#thisTokenAddress").html()).select();document.execCommand("copy");a.remove()});$("#copysaleaddress").on("click",function(){var a=$("<textarea>");$("body").append(a);a.val($("#thisSaleAddress").html()).select();document.execCommand("copy");a.remove()});
$("#copysaleaddress2").on("click",function(){var a=$("<textarea>");$("body").append(a);a.val($("#thisSaleAddress2").html()).select();document.execCommand("copy");a.remove()});$("#copyUIlink").on("click",function(){var a=$("<textarea>");$("body").append(a);a.val($("#uiAddr").text()).select();document.execCommand("copy");a.remove()});
$("#addToPresale").click(function(){var a,b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress){a=$("#addToPresaleQty").val();if(!(a&&0<Number(a)))return c.jumpTo(0);b=ethers.utils.parseUnits(a,thisDecimals);return c.yield(contractThisTokenSign.transfer(String(thisAddress),String(b)),3)}if(4!=c.nextAddress)return tx=c.yieldResult,c.yield(tx.wait(),4);admin(thisAddress);c.jumpToEnd()})});