var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(a==Array.prototype||a==Object.prototype)return a;a[b]=d.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var d=$jscomp.propertyToPolyfillSymbol[b];if(null==d)return a[b];d=a[d];return void 0!==d?d:a[b]};
$jscomp.polyfill=function(a,b,d,f){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,d,f):$jscomp.polyfillUnisolated(a,b,d,f))};$jscomp.polyfillUnisolated=function(a,b,d,f){d=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var e=a[f];if(!(e in d))return;d=d[e]}a=a[a.length-1];f=d[a];b=b(f);b!=f&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,d,f){var e=a.split(".");a=1===e.length;f=e[0];f=!a&&f in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var h=0;h<e.length-1;h++){var c=e[h];if(!(c in f))return;f=f[c]}e=e[e.length-1];d=$jscomp.IS_SYMBOL_NATIVE&&"es6"===d?f[e]:null;b=b(d);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==d&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&(d=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+d+"$"+e),$jscomp.defineProperty(f,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(d){}return!1};
$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};
$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){var d=$jscomp.makeIterator(a),f=d.next();$jscomp.generator.ensureIteratorResultIsObject_(f);if(f.done)this.yieldResult=f.value,this.nextAddress=b;else return this.yieldAllIterator_=d,this.yield(f.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,d){d?this.finallyContexts_[d]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var d=this.finallyContexts_.splice(b||0)[0];if(d=this.abruptCompletion_=this.abruptCompletion_||d){if(d.isException)return this.jumpToErrorHandler_();void 0!=d.jumpTo&&this.finallyAddress_<d.jumpTo?(this.nextAddress=d.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(d){return{value:d,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,d){try{var f=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(f);if(!f.done)return this.context_.stop_(),f;var e=f.value}catch(h){return this.context_.yieldAllIterator_=null,this.context_.throw_(h),this.nextStep_()}this.context_.yieldAllIterator_=null;d.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var d=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(d,a.prototype);return d};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(f){return a.next(f)}function d(f){return a["throw"](f)}return new Promise(function(f,e){function h(c){c.done?f(c.value):Promise.resolve(c.value).then(b,d).then(h,e)}h(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.initSymbol=function(){};$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(h,c){this.$jscomp$symbol$id_=h;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:c})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",f=0,e=function(h){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(d+(h||"")+"_"+f++,h)};return e},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),d=0;d<b.length;d++){var f=$jscomp.global[b[d]];"function"===typeof f&&"function"!=typeof f.prototype[a]&&$jscomp.defineProperty(f.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function d(c){return c instanceof e?c:new e(function(g,l){g(c)})}if(a&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&"undefined"===typeof $jscomp.global.PromiseRejectionEvent)||!$jscomp.global.Promise||-1===$jscomp.global.Promise.toString().indexOf("[native code]")))return a;b.prototype.asyncExecute=function(c){if(null==this.batch_){this.batch_=[];var g=this;this.asyncExecuteFunction(function(){g.executeBatch_()})}this.batch_.push(c)};
var f=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(c){f(c,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var c=this.batch_;this.batch_=[];for(var g=0;g<c.length;++g){var l=c[g];c[g]=null;try{l()}catch(n){this.asyncThrow_(n)}}}this.batch_=null};b.prototype.asyncThrow_=function(c){this.asyncExecuteFunction(function(){throw c;})};var e=function(c){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var g=this.createResolveAndReject_();
try{c(g.resolve,g.reject)}catch(l){g.reject(l)}};e.prototype.createResolveAndReject_=function(){function c(n){return function(p){l||(l=!0,n.call(g,p))}}var g=this,l=!1;return{resolve:c(this.resolveTo_),reject:c(this.reject_)}};e.prototype.resolveTo_=function(c){if(c===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(c instanceof e)this.settleSameAsPromise_(c);else{a:switch(typeof c){case "object":var g=null!=c;break a;case "function":g=!0;break a;default:g=!1}g?this.resolveToNonPromiseObj_(c):
this.fulfill_(c)}};e.prototype.resolveToNonPromiseObj_=function(c){var g=void 0;try{g=c.then}catch(l){this.reject_(l);return}"function"==typeof g?this.settleSameAsThenable_(g,c):this.fulfill_(c)};e.prototype.reject_=function(c){this.settle_(2,c)};e.prototype.fulfill_=function(c){this.settle_(1,c)};e.prototype.settle_=function(c,g){if(0!=this.state_)throw Error("Cannot settle("+c+", "+g+"): Promise already settled in state"+this.state_);this.state_=c;this.result_=g;2===this.state_&&this.scheduleUnhandledRejectionCheck_();
this.executeOnSettledCallbacks_()};e.prototype.scheduleUnhandledRejectionCheck_=function(){var c=this;f(function(){if(c.notifyUnhandledRejection_()){var g=$jscomp.global.console;"undefined"!==typeof g&&g.error(c.result_)}},1)};e.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var c=$jscomp.global.CustomEvent,g=$jscomp.global.Event,l=$jscomp.global.dispatchEvent;if("undefined"===typeof l)return!0;"function"===typeof c?c=new c("unhandledrejection",{cancelable:!0}):
"function"===typeof g?c=new g("unhandledrejection",{cancelable:!0}):(c=$jscomp.global.document.createEvent("CustomEvent"),c.initCustomEvent("unhandledrejection",!1,!0,c));c.promise=this;c.reason=this.result_;return l(c)};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var c=0;c<this.onSettledCallbacks_.length;++c)h.asyncExecute(this.onSettledCallbacks_[c]);this.onSettledCallbacks_=null}};var h=new b;e.prototype.settleSameAsPromise_=function(c){var g=this.createResolveAndReject_();
c.callWhenSettled_(g.resolve,g.reject)};e.prototype.settleSameAsThenable_=function(c,g){var l=this.createResolveAndReject_();try{c.call(g,l.resolve,l.reject)}catch(n){l.reject(n)}};e.prototype.then=function(c,g){function l(r,k){return"function"==typeof r?function(m){try{n(r(m))}catch(u){p(u)}}:k}var n,p,t=new e(function(r,k){n=r;p=k});this.callWhenSettled_(l(c,n),l(g,p));return t};e.prototype["catch"]=function(c){return this.then(void 0,c)};e.prototype.callWhenSettled_=function(c,g){function l(){switch(n.state_){case 1:c(n.result_);
break;case 2:g(n.result_);break;default:throw Error("Unexpected state: "+n.state_);}}var n=this;null==this.onSettledCallbacks_?h.asyncExecute(l):this.onSettledCallbacks_.push(l);this.isRejectionHandled_=!0};e.resolve=d;e.reject=function(c){return new e(function(g,l){l(c)})};e.race=function(c){return new e(function(g,l){for(var n=$jscomp.makeIterator(c),p=n.next();!p.done;p=n.next())d(p.value).callWhenSettled_(g,l)})};e.all=function(c){var g=$jscomp.makeIterator(c),l=g.next();return l.done?d([]):new e(function(n,
p){function t(m){return function(u){r[m]=u;k--;0==k&&n(r)}}var r=[],k=0;do r.push(void 0),k++,d(l.value).callWhenSettled_(t(r.length-1),p),l=g.next();while(!l.done)})};return e},"es6","es3");$(".erc").html(" (BEP-20)");$(".changenet").each(function(){this.href+="tokensalerestartable/"});
var contractAddressMain="0x8FA379bb33e47D131F487a863f6A326b076F1c63",contractAddressTest="0xC7C2Ab26E23527Ebc05E15e6016B2500C3E6eFd0",contractTokenBuilder1Main="0x32D332487C8703D94C46F99E55b12D3BaAB45190",contractTokenBuilder1Test="0x32D332487C8703D94C46F99E55b12D3BaAB45190",contractTokenBuilder2Main="0x76079d9098b84cb28F2045c4fbC44EF6AAf5b0e7",contractTokenBuilder2Test="0xA61Bc01643CC20e722761E35e4C270BbF4c36A03",contractTokenBuilder3Main="0xeE4B8458741492455d7B9929F87342Aed9D4eF4b",contractTokenBuilder3Test=
"0xBFFEfDCC6275bd0D6703fCe006bB69e2a06Fb4B6",contractTokenBuilder4Main="0x592173bc112099c812216b62504a20aaeb38c679",contractTokenBuilder4Test="0x34e18d89B43d0Ef859896D54D024072785D8C48f",contractTokenBuilder5Main="0xF74A3016E6cb9C0f112F6F6ACf5e9A5dcFB13C66",contractTokenBuilder5Test="0xA56750825ad3c76b53731AFaa7C9Eb982Fb7F0C3",contractTokenBuilder1,contractTokenBuilder2,contractTokenBuilder3,contractTokenBuilder4,contractTokenBuilder5,builderCost,contractThis,contractThisSign,contractThisToken,contractThisTokenSign,
balanceEth,thisDecimals,thisTokenAddress,thisAddress,thisSymbol,thisUnsold,available,maxDecimals=18,abi=[{inputs:[{internalType:"uint256",name:"_cost",type:"uint256"}],stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"oldBeneficiary",type:"address"},{indexed:!0,internalType:"address",name:"newBeneficiary",type:"address"}],name:"BeneficiarySet",type:"event"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"contractCreator",
type:"address"},{indexed:!0,internalType:"address",name:"contractAddress",type:"address"},{indexed:!1,internalType:"address",name:"tokenAddress",type:"address"},{indexed:!1,internalType:"uint256",name:"tokenQuantity",type:"uint256"},{indexed:!1,internalType:"uint256",name:"salePrice",type:"uint256"}],name:"ContractCreated",type:"event"},{anonymous:!1,inputs:[{indexed:!1,internalType:"uint256",name:"newCost",type:"uint256"}],name:"Cost",type:"event"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",
name:"oldOwner",type:"address"},{indexed:!0,internalType:"address",name:"newOwner",type:"address"}],name:"OwnerSet",type:"event"},{inputs:[],name:"beneficiary",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"newBeneficiary",type:"address"}],name:"changeBeneficiary",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_newcost",type:"uint256"}],name:"changeCost",outputs:[],
stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"newOwner",type:"address"}],name:"changeOwner",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"cost",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"tokenAddress",type:"address"},{internalType:"uint256",name:"saleQty",type:"uint256"},{internalType:"uint256",name:"salePrice",type:"uint256"}],name:"createContract",
outputs:[{internalType:"address",name:"contractAddress",type:"address"}],stateMutability:"payable",type:"function"},{inputs:[],name:"myContracts",outputs:[{internalType:"address[]",name:"",type:"address[]"}],stateMutability:"view",type:"function"},{inputs:[],name:"owner",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalBuilt",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],
name:"withdraw",outputs:[],stateMutability:"nonpayable",type:"function"}],abiSale=[{inputs:[{internalType:"address",name:"_tokenAddress",type:"address"},{internalType:"uint256",name:"_saleQuantity",type:"uint256"},{internalType:"uint256",name:"_salePrice",type:"uint256"}],stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,inputs:[{indexed:!1,internalType:"address",name:"buyer",type:"address"},{indexed:!1,internalType:"uint256",name:"quantity",type:"uint256"}],name:"TokenSold",type:"event"},
{inputs:[],name:"allRaised",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"allSold",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"buyToken",outputs:[],stateMutability:"payable",type:"function"},{inputs:[],name:"owner",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"uint256",name:"_qty",type:"uint256"},
{internalType:"uint256",name:"_price",type:"uint256"}],name:"restartSale",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"saleOn",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[],name:"saleQuantity",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"tokenAddress",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},
{inputs:[],name:"tokenPrice",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalRaised",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalSold",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"unsoldQuantity",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},
{inputs:[{internalType:"uint256",name:"_amount",type:"uint256"}],name:"withdraw",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"withdrawAll",outputs:[],stateMutability:"nonpayable",type:"function"},{stateMutability:"payable",type:"receive"}],abiToken=[{inputs:[{internalType:"string",name:"_name",type:"string"},{internalType:"string",name:"_symbol",type:"string"},{internalType:"uint256",name:"_dec",type:"uint256"},{internalType:"uint256",name:"_supply",type:"uint256"},{internalType:"uint256",
name:"_tax1",type:"uint256"},{internalType:"address",name:"_address1",type:"address"},{internalType:"uint256",name:"_tax2",type:"uint256"},{internalType:"address",name:"_address2",type:"address"},{internalType:"uint256",name:"_deflation",type:"uint256"},{internalType:"uint256",name:"_minSupply",type:"uint256"},{internalType:"address",name:"_owner",type:"address"}],stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"owner",type:"address"},
{indexed:!0,internalType:"address",name:"spender",type:"address"},{indexed:!1,internalType:"uint256",name:"value",type:"uint256"}],name:"Approval",type:"event"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"from",type:"address"},{indexed:!0,internalType:"address",name:"to",type:"address"},{indexed:!1,internalType:"uint256",name:"value",type:"uint256"}],name:"Transfer",type:"event"},{inputs:[],name:"addressTax1",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",
type:"function"},{inputs:[],name:"addressTax2",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"owner",type:"address"},{internalType:"address",name:"spender",type:"address"}],name:"allowance",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"spender",type:"address"},{internalType:"uint256",name:"value",type:"uint256"}],name:"approve",
outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"owner",type:"address"}],name:"balanceOf",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"burnt",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"decimals",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",
type:"function"},{inputs:[],name:"deflation",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"initialSupply",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"minSupply",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"name",outputs:[{internalType:"string",name:"",type:"string"}],stateMutability:"view",
type:"function"},{inputs:[],name:"symbol",outputs:[{internalType:"string",name:"",type:"string"}],stateMutability:"view",type:"function"},{inputs:[],name:"tax1",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"tax2",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalSupply",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},
{inputs:[],name:"totalTax1",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalTax2",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"to",type:"address"},{internalType:"uint256",name:"value",type:"uint256"}],name:"transfer",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",
name:"from",type:"address"},{internalType:"address",name:"to",type:"address"},{internalType:"uint256",name:"value",type:"uint256"}],name:"transferFrom",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"nonpayable",type:"function"}],abiTokenBuilder=[{inputs:[{internalType:"uint256",name:"_cost",type:"uint256"}],stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"oldBeneficiary",type:"address"},{indexed:!0,internalType:"address",
name:"newBeneficiary",type:"address"}],name:"BeneficiarySet",type:"event"},{anonymous:!1,inputs:[{indexed:!1,internalType:"uint256",name:"newCost",type:"uint256"}],name:"Cost",type:"event"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"oldOwner",type:"address"},{indexed:!0,internalType:"address",name:"newOwner",type:"address"}],name:"OwnerSet",type:"event"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"tokenCreator",type:"address"},{indexed:!0,internalType:"address",
name:"tokenAddress",type:"address"},{indexed:!1,internalType:"string",name:"name",type:"string"},{indexed:!1,internalType:"string",name:"symbol",type:"string"},{indexed:!1,internalType:"uint256",name:"totalSupply",type:"uint256"},{indexed:!1,internalType:"uint8",name:"decimals",type:"uint8"}],name:"TokenCreated",type:"event"},{inputs:[],name:"beneficiary",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"newBeneficiary",
type:"address"}],name:"changeBeneficiary",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_newcost",type:"uint256"}],name:"changeCost",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"newOwner",type:"address"}],name:"changeOwner",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"cost",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},
{inputs:[{internalType:"string",name:"name",type:"string"},{internalType:"string",name:"symbol",type:"string"},{internalType:"uint256",name:"totalSupply",type:"uint256"},{internalType:"uint8",name:"decimals",type:"uint8"},{internalType:"address",name:"to",type:"address"}],name:"createToken",outputs:[{internalType:"address",name:"tokenAddress",type:"address"}],stateMutability:"payable",type:"function"},{inputs:[{internalType:"address",name:"tokenAddress",type:"address"}],name:"getTokenData",outputs:[{internalType:"string",
name:"name",type:"string"},{internalType:"string",name:"symbol",type:"string"},{internalType:"uint256",name:"totalSupply",type:"uint256"},{internalType:"uint256",name:"decimals",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"myTokens",outputs:[{internalType:"address[]",name:"",type:"address[]"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"",type:"address"},{internalType:"uint256",name:"",type:"uint256"}],name:"mytokens",outputs:[{internalType:"address",
name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"owner",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"",type:"address"}],name:"tokens",outputs:[{internalType:"string",name:"name",type:"string"},{internalType:"string",name:"symbol",type:"string"},{internalType:"uint256",name:"totalSupply",type:"uint256"},{internalType:"uint8",name:"decimals",type:"uint8"}],stateMutability:"view",
type:"function"},{inputs:[],name:"totalBuilt",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"withdraw",outputs:[],stateMutability:"nonpayable",type:"function"}];
function init(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return contract=new ethers.Contract(contractAddress,abi,provider),contractSign=contract.connect(signer),a.yield(contract.cost(),2);builderCost=a.yieldResult;$("#buildercost").html(ethers.utils.formatEther(builderCost));filter=contract.filters.ContractCreated(myAddress);contract.on(filter,function(b,d,f,e,h){console.log("New sale contract for token "+f+", sale quantity "+e+", price "+h+" - created at address "+
d+".");makeTable()});makeTable();a.jumpToEnd()})}
function makeTable(){var a,b,d,f,e,h,c,g,l,n,p,t,r,k,m,u;return $jscomp.asyncExecutePromiseGeneratorProgram(function(q){switch(q.nextAddress){case 1:return a="",q.yield(contract.myContracts({from:myAddress}),2);case 2:b=q.yieldResult;if(!(0<b.length)){a="Not found";q.jumpTo(3);break}d=b;f=0;case 4:if(!(f<d.length)){q.jumpTo(3);break}e=d[f];h=new ethers.Contract(e,abiSale,provider);return q.yield(h.tokenAddress(),7);case 7:return c=q.yieldResult,q.yield(h.unsoldQuantity(),8);case 8:return g=q.yieldResult,
q.yield(h.saleOn(),9);case 9:return l=q.yieldResult,p=new ethers.Contract(c,abiToken,provider),q.yield(p.name(),10);case 10:return t=q.yieldResult,q.yield(p.symbol(),11);case 11:return r=q.yieldResult,q.yield(p.allowance(myAddress,e),12);case 12:return k=q.yieldResult,q.yield(p.balanceOf(myAddress),13);case 13:m=q.yieldResult;n=Number(k)<Number(g)?'<span style="color: red">Approve!</span>':Number(m)<Number(g)?'<span style="color: red">Add balance!</span>':l?"Active":"Finished";u=Number(f+1);a=a+'<div class="salerow" title="Click to open admin panel" onclick="admin(\''+
e+'\')"><div class="saleno">'+u+'</div><div class="saleaddress">'+e+'</div><div class="saletoken">'+t+"("+r+')</div><div class="salestatus">'+n+"</div>";a+="</div>";f++;q.jumpTo(4);break;case 3:$("#mycontr").html(a),q.jumpToEnd()}})}
$("#mytokens").click(function(){var a,b,d,f,e,h,c,g,l,n,p,t,r;return $jscomp.asyncExecutePromiseGeneratorProgram(function(k){switch(k.nextAddress){case 1:return $("#mytoks").show(),curnet==mainnet||curnet==mainnetAlt?(contractTokenBuilder1=contractTokenBuilder1Main,contractTokenBuilder2=contractTokenBuilder2Main,contractTokenBuilder3=contractTokenBuilder3Main,contractTokenBuilder4=contractTokenBuilder4Main,contractTokenBuilder5=contractTokenBuilder5Main):curnet==testnet&&(contractTokenBuilder1=contractTokenBuilder1Test,
contractTokenBuilder2=contractTokenBuilder2Test,contractTokenBuilder3=contractTokenBuilder3Test,contractTokenBuilder4=contractTokenBuilder4Test,contractTokenBuilder5=contractTokenBuilder5Test),contractToken1=new ethers.Contract(contractTokenBuilder1,abiTokenBuilder,provider),contractToken2=new ethers.Contract(contractTokenBuilder2,abiTokenBuilder,provider),contractToken3=new ethers.Contract(contractTokenBuilder3,abiTokenBuilder,provider),contractToken4=new ethers.Contract(contractTokenBuilder4,abiTokenBuilder,
provider),contractToken5=new ethers.Contract(contractTokenBuilder5,abiTokenBuilder,provider),a="",b=0,k.yield(contractToken1.myTokens({from:myAddress}),2);case 2:d=k.yieldResult;if(d==[]){k.jumpTo(3);break}f=d;e=0;case 4:if(!(e<f.length)){k.jumpTo(3);break}h=f[e];c=new ethers.Contract(h,abiToken,provider);return k.yield(c.name(),7);case 7:return g=k.yieldResult,k.yield(c.symbol(),8);case 8:l=k.yieldResult;b=Number(b+1);a=a+"<tr><td>"+b+'</td><td><a title="View on explorer" target="_blank" href="'+
tracker+"token/"+h+'">'+h+"</a></td><td>"+g+"</td><td>"+l+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+h+"')\">choose</span></td>";a+="</tr>";e++;k.jumpTo(4);break;case 3:return k.yield(contractToken2.myTokens({from:myAddress}),9);case 9:n=k.yieldResult;if(n==[]){k.jumpTo(10);break}f=n;e=0;case 11:if(!(e<f.length)){k.jumpTo(10);break}h=f[e];c=new ethers.Contract(h,abiToken,provider);return k.yield(c.name(),14);case 14:return g=k.yieldResult,k.yield(c.symbol(),15);
case 15:l=k.yieldResult;b=Number(b+1);a=a+"<tr><td>"+b+'</td><td><a title="View on explorer" target="_blank" href="'+tracker+"token/"+h+'">'+h+"</a></td><td>"+g+"</td><td>"+l+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+h+"')\">choose</span></td>";a+="</tr>";e++;k.jumpTo(11);break;case 10:return k.yield(contractToken3.myTokens({from:myAddress}),16);case 16:p=k.yieldResult;if(p==[]){k.jumpTo(17);break}f=p;e=0;case 18:if(!(e<f.length)){k.jumpTo(17);break}h=f[e];c=
new ethers.Contract(h,abiToken,provider);return k.yield(c.name(),21);case 21:return g=k.yieldResult,k.yield(c.symbol(),22);case 22:l=k.yieldResult;b=Number(b+1);a=a+"<tr><td>"+b+'</td><td><a title="View on explorer" target="_blank" href="'+tracker+"token/"+h+'">'+h+"</a></td><td>"+g+"</td><td>"+l+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+h+"')\">choose</span></td>";a+="</tr>";e++;k.jumpTo(18);break;case 17:return k.yield(contractToken4.myTokens({from:myAddress}),
23);case 23:t=k.yieldResult;if(t==[]){k.jumpTo(24);break}f=t;e=0;case 25:if(!(e<f.length)){k.jumpTo(24);break}h=f[e];c=new ethers.Contract(h,abiToken,provider);return k.yield(c.name(),28);case 28:return g=k.yieldResult,k.yield(c.symbol(),29);case 29:l=k.yieldResult;b=Number(b+1);a=a+"<tr><td>"+b+'</td><td><a title="View on explorer" target="_blank" href="'+tracker+"token/"+h+'">'+h+"</a></td><td>"+g+"</td><td>"+l+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+h+"')\">choose</span></td>";
a+="</tr>";e++;k.jumpTo(25);break;case 24:return k.yield(contractToken5.myTokens({from:myAddress}),30);case 30:r=k.yieldResult;if(r==[]){k.jumpTo(31);break}f=r;e=0;case 32:if(!(e<f.length)){k.jumpTo(31);break}h=f[e];c=new ethers.Contract(h,abiToken,provider);return k.yield(c.name(),35);case 35:return g=k.yieldResult,k.yield(c.symbol(),36);case 36:l=k.yieldResult;b=Number(b+1);a=a+"<tr><td>"+b+'</td><td><a title="View on explorer" target="_blank" href="'+tracker+"token/"+h+'">'+h+"</a></td><td>"+g+
"</td><td>"+l+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+h+"')\">choose</span></td>";a+="</tr>";e++;k.jumpTo(32);break;case 31:$("#strHtmlTokens").html(a),k.jumpToEnd()}})});function choose(a){$("#newtknaddress").val(a);$("#mytoks").hide();checkToken()}$("#newtknaddress").on("keyup input",checkToken);
function checkToken(){var a,b,d,f,e;return $jscomp.asyncExecutePromiseGeneratorProgram(function(h){switch(h.nextAddress){case 1:$("#tokendata").html("");a=$("#newtknaddress").val();if(""==a||!ethers.utils.isAddress(a))return""==a?$("#tokendata").html(""):$("#tokendata").html('<span class="err">Error: check token address!</span>'),h["return"](!1);$("#errors").html("");h.setCatchFinallyBlocks(3);b=new ethers.Contract(a,abiToken,provider);return h.yield(b.name(),5);case 5:return d=h.yieldResult,h.yield(b.symbol(),
6);case 6:f=h.yieldResult;if(d&&f)return $("#tokendata").html('<span style="color: green">'+d+" ("+f+")</span>"),h["return"](!0);$("#tokendata").html('<span class="err">Error: check token address!</span>');return h["return"](!1);case 3:return e=h.enterCatchBlock(),console.log(e),$("#tokendata").html('<span class="err">Error: check token address!</span>'),h["return"](!1)}})}
function admin(a){var b,d,f,e,h,c,g,l,n,p,t,r,k;return $jscomp.asyncExecutePromiseGeneratorProgram(function(m){switch(m.nextAddress){case 1:return $("#admin").show(),$("#thisAddr").html(a),$(".uiAddr").html(a),$("#uiAddrLnk").html(tracker+"address/"+a),$("#viewThis").html('<a title="View on explorer" target="_blank" href="'+tracker+"address/"+a+'">'+a+"</a>"),thisAddress=a,contractThis=new ethers.Contract(a,abiSale,provider),contractThisSign=contractThis.connect(signer),m.yield(contractThis.tokenAddress(),
2);case 2:return thisTokenAddress=m.yieldResult,$("#thisTokenAddress").html(thisTokenAddress),$("#viewThisToken").html('<a title="View on explorer" target="_blank" href="'+tracker+"token/"+thisTokenAddress+'">'+thisTokenAddress+"</a>"),$(".tokenAddressUI").html(thisTokenAddress),$("#tokenAddressUIlnk").html(tracker+"token/"+thisTokenAddress),contractThisToken=new ethers.Contract(thisTokenAddress,abiToken,provider),contractThisTokenSign=contractThisToken.connect(signer),m.yield(contractThisToken.name(),
3);case 3:return b=m.yieldResult,$("#thisName").html(b),$("#tokenNameUI").html(b),m.yield(contractThisToken.symbol(),4);case 4:return thisSymbol=m.yieldResult,$("#thisSymbol").html(thisSymbol),$("#tokenSymbolUI").html(thisSymbol),m.yield(contractThisToken.decimals(),5);case 5:return thisDecimals=m.yieldResult,$("#thisDec").html(Number(thisDecimals)),$("#tokenDecimalsUI").html(Number(thisDecimals)),m.yield(contractThisToken.totalSupply(),6);case 6:return d=m.yieldResult,$("#tokenSupplyUI").html(Number(ethers.utils.formatUnits(d,
thisDecimals))),m.yield(contractThisToken.allowance(myAddress,a),7);case 7:return f=m.yieldResult,m.yield(contractThisToken.balanceOf(myAddress),8);case 8:return e=m.yieldResult,m.yield(contractThis.saleQuantity(),9);case 9:return h=m.yieldResult,$("#thisSaleQty").html(ethers.utils.formatUnits(h,thisDecimals)),m.yield(contractThis.tokenPrice(),10);case 10:return c=m.yieldResult,$("#thisTokenPrice").html(ethers.utils.formatEther(c)),m.yield(contractThis.totalSold(),11);case 11:return g=m.yieldResult,
$("#thisSold").html(ethers.utils.formatUnits(g,thisDecimals)),m.yield(contractThis.totalRaised(),12);case 12:return l=m.yieldResult,$("#thisRaised").html(ethers.utils.formatEther(l)),m.yield(contractThis.allSold(),13);case 13:return n=m.yieldResult,$("#allSold").html(ethers.utils.formatUnits(n,thisDecimals)),m.yield(contractThis.allRaised(),14);case 14:return p=m.yieldResult,$("#allRaised").html(ethers.utils.formatEther(p)),m.yield(contractThis.unsoldQuantity(),15);case 15:return thisUnsold=m.yieldResult,
$("#thisUnsold").html(ethers.utils.formatUnits(thisUnsold,thisDecimals)),m.yield(provider.getBalance(a),16);case 16:return t=m.yieldResult,available=ethers.utils.formatEther(t),$("#thisBalance").html(available),m.yield(contractThis.saleOn(),17);case 17:r=m.yieldResult,Number(f)<Number(thisUnsold)&&Number(e)>=Number(thisUnsold)?(k='<span style="color: red">Approve!</span>',$("#thisApprove").show()):(k=Number(e)<Number(thisUnsold)?'<span style="color: red">Add balance!</span>':r?'<span style="color: green">OK</span>':
"Finished",$("#thisApprove").hide()),$("#thisStatus").html(k),curnet==testnet?$("#istest").html("true"):$("#istest").html("false"),getQR(a),$("#addToken").click(function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(u){watchToken(thisTokenAddress,thisSymbol,thisDecimals);u.jumpToEnd()})}),m.jumpToEnd()}})}
$("#thisApprove").click(function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return thisAddress&&thisUnsold?a.yield(contractThisTokenSign.approve(String(thisAddress),String(thisUnsold),{gasLimit:1E5}),3):a.jumpTo(0);if(4!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),4);init();admin(thisAddress);a.jumpToEnd()})});
$("#restart").click(function(){var a,b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(d){if(1==d.nextAddress)return a=$("#restartQty").val(),b=$("#restartPrice").val(),""!=a&&0<a&&""!=b?d.yield(contractThisSign.restartSale(String(ethers.utils.parseUnits(a,thisDecimals)),String(ethers.utils.parseEther(b)),{gasLimit:2E5}),3):d.jumpTo(0);if(4!=d.nextAddress)return tx=d.yieldResult,d.yield(tx.wait(),4);admin(thisAddress);makeTable();d.jumpToEnd()})});
$("#thisWithdraw").click(function(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return a=$("#thisWithdrawAmount").val(),""!=a&&0<a?b.yield(contractThisSign.withdraw(ethers.utils.parseEther(a),{gasLimit:1E5}),3):b.jumpTo(0);if(4!=b.nextAddress)return tx=b.yieldResult,b.yield(tx.wait(),4);admin(thisAddress);b.jumpToEnd()})});
$("#thisWithdrawAll").click(function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return 0<available?a.yield(contractThisSign.withdrawAll({gasLimit:1E5}),3):a.jumpTo(0);if(4!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),4);admin(thisAddress);a.jumpToEnd()})});
function watchToken(a,b,d){return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){ethereum.request({method:"wallet_watchAsset",params:{type:"ERC20",options:{address:String(a),symbol:String(b),decimals:String(d)}}});f.jumpToEnd()})}
$("#buildbtn").click(function(){var a,b,d,f,e,h,c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){switch(g.nextAddress){case 1:if(!myAddress){g.jumpTo(0);break}return g.yield(provider.getBalance(myAddress),3);case 3:a=g.yieldResult;if(!(Number(a)>Number(builderCost))){$("#errors").html("Insufficient balance in your wallet! Contract creation cost is "+ethers.utils.formatEther(builderCost)+" BNB + network fees (gas)!");g.jumpTo(0);break}return g.yield(checkToken(),5);case 5:b=g.yieldResult;
d=$("#newtknaddress").val();f=$("#newprice").val();e=$("#newqty").val();if(!(""!=d&&0<e&&f&&1E-18<=Number(f)&&b)){f&&1E-18>Number(f)?$("#errors").html("Error: too low token price!"):b?(checkToken(),$("#errors").html("Error: fields are empty or incorrect!")):(checkToken(),$("#errors").html("Error: check token address!"));g.jumpTo(0);break}$("#errors").html("");h=new ethers.Contract(d,abiToken,provider);return g.yield(h.decimals(),7);case 7:return c=g.yieldResult,g.yield(contractSign.createContract(String(d),
String(ethers.utils.parseUnits(e,c)),String(ethers.utils.parseEther(f)),{value:builderCost}),8);case 8:return tx=g.yieldResult,g.yield(tx.wait(),9);case 9:init(),g.jumpToEnd()}})});$("#newprice").on("keyup input",function(){var a=$("#newprice").val();a=1/Number(a);$("#tokperbnb").html(Number(a))});$("#thisWithdrawAmount").change(function(){var a=$("#thisWithdrawAmount").val();0>a?a=0:a>available&&(a=available);$("#thisWithdrawAmount").val(Number(a))});
function getQR(a){a=encodeURIComponent(a);$("#refqr").html('<img style="max-width: 80%" src="https://create.metaexchange.finance/php/qr.php?data='+a+'">');$("#refd").attr("href","https://create.metaexchange.finance/php/qr.php?data="+a)};