$('.ethereum').html('ThunderCore (TT)');
$('.eth').html('TT');
$('.short').html('ThunderCore');
$('.ethhref').attr('href','https://dappbuilder.org/thundercore/');
//$('.dappbrowser').html('<a target="_blank" href="https://metamask.io">Metamask</a>');
var trackerMain = 'https://viewblock.io/thundercore/address/';
var trackerTest = 'https://scan-testnet.thundercore.com/address/';
var tokentracker;
var mainnet = 108;
var mainnetAlt = 264;
var testnet = 18;
var mainnetname = 'ThunderCore (TT) Mainnet';
var testnetname = 'ThunderCore (TT) Testnet';
var wrongnet = '<span class="err">Please use ThunderCore (TT) Mainnet or Testnet</span>';