$('.ethereum').html('Binance Smart Chain (BSC)');
$('.eth').html('BNB');
$('.short').html('Binance Smart Chain (BSC)');
$('.ethhref').attr('href','https://create.metaexchange.finance/bsc/');
//$('.dappbrowser').html('<a target="_blank" href="https://metamask.io">Metamask</a>');
var trackerMain = 'https://bscscan.com/';
var trackerTest = 'https://testnet.bscscan.com/';
var tokentracker;
var mainnet = 56;
var mainnetAlt = 56;
var testnet = 97;
var mainnetname = 'Binance Smart Chain (BSC) Mainnet';
var testnetname = 'Binance Smart Chain (BSC) Testnet';
var wrongnet = '<span class="err">Please use Binance Smart Chain (BSC) Mainnet or Testnet</span>';