var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,f){if(a==Array.prototype||a==Object.prototype)return a;a[b]=f.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var f=a[b];if(f&&f.Math==Math)return f}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var f=$jscomp.propertyToPolyfillSymbol[b];if(null==f)return a[b];f=a[f];return void 0!==f?f:a[b]};
$jscomp.polyfill=function(a,b,f,g){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,f,g):$jscomp.polyfillUnisolated(a,b,f,g))};$jscomp.polyfillUnisolated=function(a,b,f,g){f=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var e=a[g];if(!(e in f))return;f=f[e]}a=a[a.length-1];g=f[a];b=b(g);b!=g&&null!=b&&$jscomp.defineProperty(f,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,f,g){var e=a.split(".");a=1===e.length;g=e[0];g=!a&&g in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var l=0;l<e.length-1;l++){var c=e[l];if(!(c in g))return;g=g[c]}e=e[e.length-1];f=$jscomp.IS_SYMBOL_NATIVE&&"es6"===f?g[e]:null;b=b(f);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==f&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&(f=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+f+"$"+e),$jscomp.defineProperty(g,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(f){}return!1};
$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};
$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){var f=$jscomp.makeIterator(a),g=f.next();$jscomp.generator.ensureIteratorResultIsObject_(g);if(g.done)this.yieldResult=g.value,this.nextAddress=b;else return this.yieldAllIterator_=f,this.yield(g.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,f){f?this.finallyContexts_[f]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var f=this.finallyContexts_.splice(b||0)[0];if(f=this.abruptCompletion_=this.abruptCompletion_||f){if(f.isException)return this.jumpToErrorHandler_();void 0!=f.jumpTo&&this.finallyAddress_<f.jumpTo?(this.nextAddress=f.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(f){return{value:f,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,f){try{var g=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(g);if(!g.done)return this.context_.stop_(),g;var e=g.value}catch(l){return this.context_.yieldAllIterator_=null,this.context_.throw_(l),this.nextStep_()}this.context_.yieldAllIterator_=null;f.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var f=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(f,a.prototype);return f};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(g){return a.next(g)}function f(g){return a["throw"](g)}return new Promise(function(g,e){function l(c){c.done?g(c.value):Promise.resolve(c.value).then(b,f).then(l,e)}l(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.initSymbol=function(){};$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(l,c){this.$jscomp$symbol$id_=l;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:c})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var f="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",g=0,e=function(l){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(f+(l||"")+"_"+g++,l)};return e},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),f=0;f<b.length;f++){var g=$jscomp.global[b[f]];"function"===typeof g&&"function"!=typeof g.prototype[a]&&$jscomp.defineProperty(g.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function f(c){return c instanceof e?c:new e(function(k,h){k(c)})}if(a&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&"undefined"===typeof $jscomp.global.PromiseRejectionEvent)||!$jscomp.global.Promise||-1===$jscomp.global.Promise.toString().indexOf("[native code]")))return a;b.prototype.asyncExecute=function(c){if(null==this.batch_){this.batch_=[];var k=this;this.asyncExecuteFunction(function(){k.executeBatch_()})}this.batch_.push(c)};
var g=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(c){g(c,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var c=this.batch_;this.batch_=[];for(var k=0;k<c.length;++k){var h=c[k];c[k]=null;try{h()}catch(n){this.asyncThrow_(n)}}}this.batch_=null};b.prototype.asyncThrow_=function(c){this.asyncExecuteFunction(function(){throw c;})};var e=function(c){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var k=this.createResolveAndReject_();
try{c(k.resolve,k.reject)}catch(h){k.reject(h)}};e.prototype.createResolveAndReject_=function(){function c(n){return function(p){h||(h=!0,n.call(k,p))}}var k=this,h=!1;return{resolve:c(this.resolveTo_),reject:c(this.reject_)}};e.prototype.resolveTo_=function(c){if(c===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(c instanceof e)this.settleSameAsPromise_(c);else{a:switch(typeof c){case "object":var k=null!=c;break a;case "function":k=!0;break a;default:k=!1}k?this.resolveToNonPromiseObj_(c):
this.fulfill_(c)}};e.prototype.resolveToNonPromiseObj_=function(c){var k=void 0;try{k=c.then}catch(h){this.reject_(h);return}"function"==typeof k?this.settleSameAsThenable_(k,c):this.fulfill_(c)};e.prototype.reject_=function(c){this.settle_(2,c)};e.prototype.fulfill_=function(c){this.settle_(1,c)};e.prototype.settle_=function(c,k){if(0!=this.state_)throw Error("Cannot settle("+c+", "+k+"): Promise already settled in state"+this.state_);this.state_=c;this.result_=k;2===this.state_&&this.scheduleUnhandledRejectionCheck_();
this.executeOnSettledCallbacks_()};e.prototype.scheduleUnhandledRejectionCheck_=function(){var c=this;g(function(){if(c.notifyUnhandledRejection_()){var k=$jscomp.global.console;"undefined"!==typeof k&&k.error(c.result_)}},1)};e.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var c=$jscomp.global.CustomEvent,k=$jscomp.global.Event,h=$jscomp.global.dispatchEvent;if("undefined"===typeof h)return!0;"function"===typeof c?c=new c("unhandledrejection",{cancelable:!0}):
"function"===typeof k?c=new k("unhandledrejection",{cancelable:!0}):(c=$jscomp.global.document.createEvent("CustomEvent"),c.initCustomEvent("unhandledrejection",!1,!0,c));c.promise=this;c.reason=this.result_;return h(c)};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var c=0;c<this.onSettledCallbacks_.length;++c)l.asyncExecute(this.onSettledCallbacks_[c]);this.onSettledCallbacks_=null}};var l=new b;e.prototype.settleSameAsPromise_=function(c){var k=this.createResolveAndReject_();
c.callWhenSettled_(k.resolve,k.reject)};e.prototype.settleSameAsThenable_=function(c,k){var h=this.createResolveAndReject_();try{c.call(k,h.resolve,h.reject)}catch(n){h.reject(n)}};e.prototype.then=function(c,k){function h(q,d){return"function"==typeof q?function(t){try{n(q(t))}catch(u){p(u)}}:d}var n,p,r=new e(function(q,d){n=q;p=d});this.callWhenSettled_(h(c,n),h(k,p));return r};e.prototype["catch"]=function(c){return this.then(void 0,c)};e.prototype.callWhenSettled_=function(c,k){function h(){switch(n.state_){case 1:c(n.result_);
break;case 2:k(n.result_);break;default:throw Error("Unexpected state: "+n.state_);}}var n=this;null==this.onSettledCallbacks_?l.asyncExecute(h):this.onSettledCallbacks_.push(h);this.isRejectionHandled_=!0};e.resolve=f;e.reject=function(c){return new e(function(k,h){h(c)})};e.race=function(c){return new e(function(k,h){for(var n=$jscomp.makeIterator(c),p=n.next();!p.done;p=n.next())f(p.value).callWhenSettled_(k,h)})};e.all=function(c){var k=$jscomp.makeIterator(c),h=k.next();return h.done?f([]):new e(function(n,
p){function r(t){return function(u){q[t]=u;d--;0==d&&n(q)}}var q=[],d=0;do q.push(void 0),d++,f(h.value).callWhenSettled_(r(q.length-1),p),h=k.next();while(!h.done)})};return e},"es6","es3");$(".erc").html(" (ERC-20)");$(".changenet").each(function(){this.href+="tokensalewithreferral/"});trackerMain="https://explorer-mainnet.maticvigil.com/";trackerTest="https://explorer-mumbai.maticvigil.com/";
var contractAddressMain="0xB0BFB481Da81b610541B6881D36646310A530B64",contractAddressTest="0x592173bc112099c812216b62504a20aaeb38c679",contractTokenBuilder1Main="0xA281713f54CdC6af205BaE122bafA9712CB97BdA",contractTokenBuilder1Test="0x040790ED2c404004A5b2DC31D6c799d12D655055",contractTokenBuilder2Main="0xfC36e31c4facD0fbe36af60F2d6079Ba07d59c95",contractTokenBuilder2Test="0xf3c1B97Ba716DD79076369a25036Ba966B3eD284",contractTokenBuilder3Main="0x32D332487C8703D94C46F99E55b12D3BaAB45190",contractTokenBuilder3Test=
"0x32D332487C8703D94C46F99E55b12D3BaAB45190",contractTokenBuilder4Main="0x1A3Bd3b5F46C429D7d06d0B01F6F97D5698Ba1E2",contractTokenBuilder4Test="0xBFFEfDCC6275bd0D6703fCe006bB69e2a06Fb4B6",contractTokenBuilder5Main="0x592173bc112099c812216b62504a20aaeb38c679",contractTokenBuilder5Test="0x34e18d89B43d0Ef859896D54D024072785D8C48f",contractTokenBuilder1,contractTokenBuilder2,contractTokenBuilder3,contractTokenBuilder4,contractTokenBuilder5,builderCost,contractThis,contractThisSign,contractThisToken,contractThisTokenSign,
balanceEth,thisDecimals,thisTokenAddress,thisAddress,thisSymbol,thisUnsold,available,maxDecimals=18,abi=[{inputs:[{internalType:"uint256",name:"_cost",type:"uint256"}],stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"oldBeneficiary",type:"address"},{indexed:!0,internalType:"address",name:"newBeneficiary",type:"address"}],name:"BeneficiarySet",type:"event"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"contractCreator",
type:"address"},{indexed:!0,internalType:"address",name:"contractAddress",type:"address"},{indexed:!1,internalType:"address",name:"tokenAddress",type:"address"},{indexed:!1,internalType:"uint256",name:"tokenQuantity",type:"uint256"},{indexed:!1,internalType:"uint256",name:"salePrice",type:"uint256"},{indexed:!1,internalType:"uint256",name:"refPercent",type:"uint256"}],name:"ContractCreated",type:"event"},{anonymous:!1,inputs:[{indexed:!1,internalType:"uint256",name:"newCost",type:"uint256"}],name:"Cost",
type:"event"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"oldOwner",type:"address"},{indexed:!0,internalType:"address",name:"newOwner",type:"address"}],name:"OwnerSet",type:"event"},{inputs:[],name:"beneficiary",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"newBeneficiary",type:"address"}],name:"changeBeneficiary",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",
name:"_newcost",type:"uint256"}],name:"changeCost",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"newOwner",type:"address"}],name:"changeOwner",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"cost",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"tokenAddress",type:"address"},{internalType:"uint256",name:"saleQty",type:"uint256"},{internalType:"uint256",
name:"salePrice",type:"uint256"},{internalType:"uint256",name:"refPercent",type:"uint256"}],name:"createContract",outputs:[{internalType:"address",name:"contractAddress",type:"address"}],stateMutability:"payable",type:"function"},{inputs:[],name:"myContracts",outputs:[{internalType:"address[]",name:"",type:"address[]"}],stateMutability:"view",type:"function"},{inputs:[],name:"owner",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalBuilt",
outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"withdraw",outputs:[],stateMutability:"nonpayable",type:"function"}],abiSale=[{inputs:[{internalType:"address",name:"_tokenAddress",type:"address"},{internalType:"uint256",name:"_saleQuantity",type:"uint256"},{internalType:"uint256",name:"_salePrice",type:"uint256"},{internalType:"uint256",name:"_refPercent",type:"uint256"}],stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,
inputs:[{indexed:!1,internalType:"address",name:"buyer",type:"address"},{indexed:!1,internalType:"uint256",name:"quantity",type:"uint256"}],name:"TokenSold",type:"event"},{inputs:[{internalType:"address",name:"_ref",type:"address"}],name:"buyToken",outputs:[],stateMutability:"payable",type:"function"},{inputs:[],name:"owner",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"",type:"address"}],name:"refEarnings",
outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"refPercent",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"refTotal",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"saleOn",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[],name:"saleQuantity",outputs:[{internalType:"uint256",
name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"tokenAddress",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"tokenPrice",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalRaised",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalSold",outputs:[{internalType:"uint256",
name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"unsoldQuantity",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"uint256",name:"_amount",type:"uint256"}],name:"withdraw",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"withdrawAll",outputs:[],stateMutability:"nonpayable",type:"function"},{stateMutability:"payable",type:"receive"}],abiToken=[{inputs:[{internalType:"string",
name:"_name",type:"string"},{internalType:"string",name:"_symbol",type:"string"},{internalType:"uint256",name:"_dec",type:"uint256"},{internalType:"uint256",name:"_supply",type:"uint256"},{internalType:"uint256",name:"_tax1",type:"uint256"},{internalType:"address",name:"_address1",type:"address"},{internalType:"uint256",name:"_tax2",type:"uint256"},{internalType:"address",name:"_address2",type:"address"},{internalType:"uint256",name:"_deflation",type:"uint256"},{internalType:"uint256",name:"_minSupply",
type:"uint256"},{internalType:"address",name:"_owner",type:"address"}],stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"owner",type:"address"},{indexed:!0,internalType:"address",name:"spender",type:"address"},{indexed:!1,internalType:"uint256",name:"value",type:"uint256"}],name:"Approval",type:"event"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"from",type:"address"},{indexed:!0,internalType:"address",name:"to",type:"address"},
{indexed:!1,internalType:"uint256",name:"value",type:"uint256"}],name:"Transfer",type:"event"},{inputs:[],name:"addressTax1",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"addressTax2",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"owner",type:"address"},{internalType:"address",name:"spender",type:"address"}],name:"allowance",outputs:[{internalType:"uint256",
name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"spender",type:"address"},{internalType:"uint256",name:"value",type:"uint256"}],name:"approve",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"owner",type:"address"}],name:"balanceOf",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"burnt",outputs:[{internalType:"uint256",
name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"decimals",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"deflation",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"initialSupply",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"minSupply",outputs:[{internalType:"uint256",
name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"name",outputs:[{internalType:"string",name:"",type:"string"}],stateMutability:"view",type:"function"},{inputs:[],name:"symbol",outputs:[{internalType:"string",name:"",type:"string"}],stateMutability:"view",type:"function"},{inputs:[],name:"tax1",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"tax2",outputs:[{internalType:"uint256",name:"",type:"uint256"}],
stateMutability:"view",type:"function"},{inputs:[],name:"totalSupply",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalTax1",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalTax2",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"to",type:"address"},{internalType:"uint256",
name:"value",type:"uint256"}],name:"transfer",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"from",type:"address"},{internalType:"address",name:"to",type:"address"},{internalType:"uint256",name:"value",type:"uint256"}],name:"transferFrom",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"nonpayable",type:"function"}],abiTokenBuilder=[{inputs:[{internalType:"uint256",name:"_cost",type:"uint256"}],
stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"oldBeneficiary",type:"address"},{indexed:!0,internalType:"address",name:"newBeneficiary",type:"address"}],name:"BeneficiarySet",type:"event"},{anonymous:!1,inputs:[{indexed:!1,internalType:"uint256",name:"newCost",type:"uint256"}],name:"Cost",type:"event"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"oldOwner",type:"address"},{indexed:!0,internalType:"address",name:"newOwner",
type:"address"}],name:"OwnerSet",type:"event"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"tokenCreator",type:"address"},{indexed:!0,internalType:"address",name:"tokenAddress",type:"address"},{indexed:!1,internalType:"string",name:"name",type:"string"},{indexed:!1,internalType:"string",name:"symbol",type:"string"},{indexed:!1,internalType:"uint256",name:"totalSupply",type:"uint256"},{indexed:!1,internalType:"uint8",name:"decimals",type:"uint8"}],name:"TokenCreated",type:"event"},
{inputs:[],name:"beneficiary",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"newBeneficiary",type:"address"}],name:"changeBeneficiary",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_newcost",type:"uint256"}],name:"changeCost",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"newOwner",type:"address"}],name:"changeOwner",
outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"cost",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"string",name:"name",type:"string"},{internalType:"string",name:"symbol",type:"string"},{internalType:"uint256",name:"totalSupply",type:"uint256"},{internalType:"uint8",name:"decimals",type:"uint8"},{internalType:"address",name:"to",type:"address"}],name:"createToken",outputs:[{internalType:"address",
name:"tokenAddress",type:"address"}],stateMutability:"payable",type:"function"},{inputs:[{internalType:"address",name:"tokenAddress",type:"address"}],name:"getTokenData",outputs:[{internalType:"string",name:"name",type:"string"},{internalType:"string",name:"symbol",type:"string"},{internalType:"uint256",name:"totalSupply",type:"uint256"},{internalType:"uint256",name:"decimals",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"myTokens",outputs:[{internalType:"address[]",name:"",
type:"address[]"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"",type:"address"},{internalType:"uint256",name:"",type:"uint256"}],name:"mytokens",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"owner",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"",type:"address"}],name:"tokens",outputs:[{internalType:"string",
name:"name",type:"string"},{internalType:"string",name:"symbol",type:"string"},{internalType:"uint256",name:"totalSupply",type:"uint256"},{internalType:"uint8",name:"decimals",type:"uint8"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalBuilt",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"withdraw",outputs:[],stateMutability:"nonpayable",type:"function"}];
function init(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return contract=new ethers.Contract(contractAddress,abi,provider),contractSign=contract.connect(signer),a.yield(contract.cost(),2);builderCost=a.yieldResult;$("#buildercost").html(ethers.utils.formatEther(builderCost));filter=contract.filters.ContractCreated(myAddress);contract.on(filter,function(b,f,g,e,l,c){console.log("New sale contract for token "+g+", sale quantity "+e+", price "+l+", referral commission "+
c/10+" - created at address "+f+".");makeTable()});makeTable();a.jumpToEnd()})}
function makeTable(){var a,b,f,g,e,l,c,k,h,n,p,r,q,d,t,u,v,w,x,y;return $jscomp.asyncExecutePromiseGeneratorProgram(function(m){switch(m.nextAddress){case 1:return a="",m.yield(contract.myContracts({from:myAddress}),2);case 2:b=m.yieldResult;if(b==[]){m.jumpTo(3);break}f=b;g=0;case 4:if(!(g<f.length)){m.jumpTo(3);break}e=f[g];l=new ethers.Contract(e,abiSale,provider);return m.yield(l.tokenAddress(),7);case 7:return c=m.yieldResult,m.yield(l.saleQuantity(),8);case 8:return k=m.yieldResult,m.yield(l.unsoldQuantity(),
9);case 9:return h=m.yieldResult,m.yield(l.tokenPrice(),10);case 10:return n=m.yieldResult,m.yield(l.saleOn(),11);case 11:return p=m.yieldResult,m.yield(l.refPercent(),12);case 12:return q=m.yieldResult,d=new ethers.Contract(c,abiToken,provider),m.yield(d.name(),13);case 13:return t=m.yieldResult,m.yield(d.symbol(),14);case 14:return u=m.yieldResult,m.yield(d.decimals(),15);case 15:return m.yield(d.allowance(myAddress,e),16);case 16:return v=m.yieldResult,m.yield(d.balanceOf(myAddress),17);case 17:return w=
m.yieldResult,m.yield(d.decimals(),18);case 18:x=m.yieldResult;r=Number(v)<Number(h)?'<span style="color: red">Approve!</span>':Number(w)<Number(h)?'<span style="color: red">Add balance!</span>':p?"OK":"Finished";y=Number(g+1);a=a+"<tr><td>"+y+'</td><td><a title="View on explorer" target="_blank" href="'+tracker+"address/"+e+'">'+e+'</a></td><td><a title="View on explorer" target="_blank" href="'+tracker+"tokens/"+c+'">'+t+"("+u+")</a></td><td>"+ethers.utils.formatUnits(k,x)+"</td><td>"+ethers.utils.formatEther(n)+
"</td><td>"+Number(q)/10+"%</td><td>"+r+'</td><td><span title="Admin panel" class="clickable" onclick="admin(\''+e+'\')">admin</span></td><td><span title="User interface" class="clickable" onclick="ui(\''+e+"')\">UI</span></td>";a+="</tr>";g++;m.jumpTo(4);break;case 3:$("#strHtml").html(a),m.jumpToEnd()}})}
$("#mytokens").click(function(){var a,b,f,g,e,l,c,k,h,n,p,r,q;return $jscomp.asyncExecutePromiseGeneratorProgram(function(d){switch(d.nextAddress){case 1:return $("#mytoks").show(),curnet==mainnet||curnet==mainnetAlt?(contractTokenBuilder1=contractTokenBuilder1Main,contractTokenBuilder2=contractTokenBuilder2Main,contractTokenBuilder3=contractTokenBuilder3Main,contractTokenBuilder4=contractTokenBuilder4Main,contractTokenBuilder5=contractTokenBuilder5Main):curnet==testnet&&(contractTokenBuilder1=contractTokenBuilder1Test,
contractTokenBuilder2=contractTokenBuilder2Test,contractTokenBuilder3=contractTokenBuilder3Test,contractTokenBuilder4=contractTokenBuilder4Test,contractTokenBuilder5=contractTokenBuilder5Test),contractToken1=new ethers.Contract(contractTokenBuilder1,abiTokenBuilder,provider),contractToken2=new ethers.Contract(contractTokenBuilder2,abiTokenBuilder,provider),contractToken3=new ethers.Contract(contractTokenBuilder3,abiTokenBuilder,provider),contractToken4=new ethers.Contract(contractTokenBuilder4,abiTokenBuilder,
provider),contractToken5=new ethers.Contract(contractTokenBuilder5,abiTokenBuilder,provider),a="",b=0,d.yield(contractToken1.myTokens({from:myAddress}),2);case 2:f=d.yieldResult;if(f==[]){d.jumpTo(3);break}g=f;e=0;case 4:if(!(e<g.length)){d.jumpTo(3);break}l=g[e];c=new ethers.Contract(l,abiToken,provider);return d.yield(c.name(),7);case 7:return k=d.yieldResult,d.yield(c.symbol(),8);case 8:h=d.yieldResult;b=Number(b+1);a=a+"<tr><td>"+b+'</td><td><a title="View on explorer" target="_blank" href="'+
tracker+"tokens/"+l+'">'+l+"</a></td><td>"+k+"</td><td>"+h+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+l+"')\">choose</span></td>";a+="</tr>";e++;d.jumpTo(4);break;case 3:return d.yield(contractToken2.myTokens({from:myAddress}),9);case 9:n=d.yieldResult;if(n==[]){d.jumpTo(10);break}g=n;e=0;case 11:if(!(e<g.length)){d.jumpTo(10);break}l=g[e];c=new ethers.Contract(l,abiToken,provider);return d.yield(c.name(),14);case 14:return k=d.yieldResult,d.yield(c.symbol(),15);
case 15:h=d.yieldResult;b=Number(b+1);a=a+"<tr><td>"+b+'</td><td><a title="View on explorer" target="_blank" href="'+tracker+"tokens/"+l+'">'+l+"</a></td><td>"+k+"</td><td>"+h+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+l+"')\">choose</span></td>";a+="</tr>";e++;d.jumpTo(11);break;case 10:return d.yield(contractToken3.myTokens({from:myAddress}),16);case 16:p=d.yieldResult;if(p==[]){d.jumpTo(17);break}g=p;e=0;case 18:if(!(e<g.length)){d.jumpTo(17);break}l=g[e];c=
new ethers.Contract(l,abiToken,provider);return d.yield(c.name(),21);case 21:return k=d.yieldResult,d.yield(c.symbol(),22);case 22:h=d.yieldResult;b=Number(b+1);a=a+"<tr><td>"+b+'</td><td><a title="View on explorer" target="_blank" href="'+tracker+"tokens/"+l+'">'+l+"</a></td><td>"+k+"</td><td>"+h+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+l+"')\">choose</span></td>";a+="</tr>";e++;d.jumpTo(18);break;case 17:return d.yield(contractToken4.myTokens({from:myAddress}),
23);case 23:r=d.yieldResult;if(r==[]){d.jumpTo(24);break}g=r;e=0;case 25:if(!(e<g.length)){d.jumpTo(24);break}l=g[e];c=new ethers.Contract(l,abiToken,provider);return d.yield(c.name(),28);case 28:return k=d.yieldResult,d.yield(c.symbol(),29);case 29:h=d.yieldResult;b=Number(b+1);a=a+"<tr><td>"+b+'</td><td><a title="View on explorer" target="_blank" href="'+tracker+"tokens/"+l+'">'+l+"</a></td><td>"+k+"</td><td>"+h+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+l+"')\">choose</span></td>";
a+="</tr>";e++;d.jumpTo(25);break;case 24:return d.yield(contractToken5.myTokens({from:myAddress}),30);case 30:q=d.yieldResult;if(q==[]){d.jumpTo(31);break}g=q;e=0;case 32:if(!(e<g.length)){d.jumpTo(31);break}l=g[e];c=new ethers.Contract(l,abiToken,provider);return d.yield(c.name(),35);case 35:return k=d.yieldResult,d.yield(c.symbol(),36);case 36:h=d.yieldResult;b=Number(b+1);a=a+"<tr><td>"+b+'</td><td><a title="View on explorer" target="_blank" href="'+tracker+"tokens/"+l+'">'+l+"</a></td><td>"+
k+"</td><td>"+h+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+l+"')\">choose</span></td>";a+="</tr>";e++;d.jumpTo(32);break;case 31:$("#strHtmlTokens").html(a),d.jumpToEnd()}})});function choose(a){$("#newtknaddress").val(a);$("#mytoks").hide()}
function admin(a){var b,f,g,e,l,c,k,h,n,p,r,q;return $jscomp.asyncExecutePromiseGeneratorProgram(function(d){switch(d.nextAddress){case 1:return $("#admin").show(),$("#thisAddr").html(a),$("#viewThis").html('<a title="View on explorer" target="_blank" href="'+tracker+"address/"+a+'">'+a+"</a>"),thisAddress=a,contractThis=new ethers.Contract(a,abiSale,provider),contractThisSign=contractThis.connect(signer),d.yield(contractThis.tokenAddress(),2);case 2:return thisTokenAddress=d.yieldResult,$("#thisTokenAddress").html(thisTokenAddress),
$("#viewThisToken").html('<a title="View on explorer" target="_blank" href="'+tracker+"tokens/"+thisTokenAddress+'">'+thisTokenAddress+"</a>"),contractThisToken=new ethers.Contract(thisTokenAddress,abiToken,provider),contractThisTokenSign=contractThisToken.connect(signer),d.yield(contractThisToken.name(),3);case 3:return b=d.yieldResult,$("#thisName").html(b),d.yield(contractThisToken.symbol(),4);case 4:return thisSymbol=d.yieldResult,$("#thisSymbol").html(thisSymbol),d.yield(contractThisToken.decimals(),
5);case 5:return thisDecimals=d.yieldResult,$("#thisDec").html(Number(thisDecimals)),d.yield(contractThisToken.allowance(myAddress,a),6);case 6:return f=d.yieldResult,d.yield(contractThisToken.balanceOf(myAddress),7);case 7:return g=d.yieldResult,d.yield(contractThis.saleQuantity(),8);case 8:return e=d.yieldResult,$("#thisSaleQty").html(ethers.utils.formatUnits(e,thisDecimals)),d.yield(contractThis.tokenPrice(),9);case 9:return l=d.yieldResult,$("#thisTokenPrice").html(ethers.utils.formatEther(l)),
d.yield(contractThis.totalSold(),10);case 10:return c=d.yieldResult,$("#thisSold").html(ethers.utils.formatUnits(c,thisDecimals)),d.yield(contractThis.totalRaised(),11);case 11:return k=d.yieldResult,$("#thisRaised").html(ethers.utils.formatEther(k)),d.yield(contractThis.unsoldQuantity(),12);case 12:return thisUnsold=d.yieldResult,$("#thisUnsold").html(ethers.utils.formatUnits(thisUnsold,thisDecimals)),d.yield(contractThis.refTotal(),13);case 13:return h=d.yieldResult,$("#thisRefTotal").html(ethers.utils.formatEther(h)),
d.yield(contractThis.refPercent(),14);case 14:return n=d.yieldResult,$("#thisRefPercent").html(Number(n)/10),d.yield(provider.getBalance(a),15);case 15:return p=d.yieldResult,available=ethers.utils.formatEther(p),$("#thisBalance").html(available),d.yield(contractThis.saleOn(),16);case 16:r=d.yieldResult,Number(f)<Number(thisUnsold)&&Number(g)>=Number(thisUnsold)?(q='<span style="color: red">Approve!</span>',$("#thisApprove").show()):(q=Number(g)<Number(thisUnsold)?'<span style="color: red">Add balance!</span>':
r?'<span style="color: green">OK</span>':"Finished",$("#thisApprove").hide()),$("#thisStatus").html(q),$("#addToken").click(function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(t){watchToken(thisTokenAddress,thisSymbol,thisDecimals);t.jumpToEnd()})}),d.jumpToEnd()}})}
$("#thisApprove").click(function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return thisAddress&&thisUnsold?a.yield(contractThisTokenSign.approve(String(thisAddress),String(thisUnsold),{gasLimit:1E5}),3):a.jumpTo(0);if(4!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),4);init();admin(thisAddress);a.jumpToEnd()})});
$("#thisWithdraw").click(function(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return a=$("#thisWithdrawAmount").val(),""!=a&&0<a?b.yield(contractThisSign.withdraw(ethers.utils.parseEther(a),{gasLimit:1E5}),3):b.jumpTo(0);if(4!=b.nextAddress)return tx=b.yieldResult,b.yield(tx.wait(),4);admin(thisAddress);b.jumpToEnd()})});
$("#thisWithdrawAll").click(function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return 0<available?a.yield(contractThisSign.withdrawAll({gasLimit:1E5}),3):a.jumpTo(0);if(4!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),4);admin(thisAddress);a.jumpToEnd()})});
function watchToken(a,b,f){return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){ethereum.request({method:"wallet_watchAsset",params:{type:"ERC20",options:{address:String(a),symbol:String(b),decimals:String(f)}}});g.jumpToEnd()})}
$("#buildbtn").click(function(){var a,b,f,g,e,l;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){switch(c.nextAddress){case 1:a=$("#newtknaddress").val();b=$("#newprice").val();f=$("#newqty").val();g=$("#newref").val();if(!(""!=a&&0<Number(f)&&b&&1E-18<=Number(b)&&100>Number(g)&&ethers.utils.isAddress(a))){b&&1E-18>Number(b)?$("#errors").html("Error: too low token price!"):$("#errors").html("Error: fields are empty or incorrect!");c.jumpTo(0);break}$("#errors").html("");e=new ethers.Contract(a,
abiToken,provider);return c.yield(e.decimals(),3);case 3:return l=c.yieldResult,c.yield(contractSign.createContract(String(a),String(ethers.utils.parseUnits(f,l)),String(ethers.utils.parseEther(b)),String(10*Number(g)),{value:builderCost}),4);case 4:return tx=c.yieldResult,c.yield(tx.wait(),5);case 5:init(),c.jumpToEnd()}})});$("#newprice").on("keyup input",function(){var a=$("#newprice").val();a=1/Number(a);$("#tokperbnb").html(Number(a))});
$("#newref").change(function(){refper=$("#newref").val();0>Number(refper)&&(refper=0);100<Number(refper)&&(refper=100);$("#newref").val(Number(refper).toFixed(1))});$("#thisWithdrawAmount").change(function(){var a=$("#thisWithdrawAmount").val();0>a?a=0:a>available&&(a=available);$("#thisWithdrawAmount").val(Number(a))});
function ui(a){var b,f,g,e,l,c,k;return $jscomp.asyncExecutePromiseGeneratorProgram(function(h){switch(h.nextAddress){case 1:return $("#ui").show(),$(".uiAddr").html(a),$(".uiAddrlnk").attr("href",tracker+"address/"+a),curnet==testnet?$("#istest").html("true"):$("#istest").html("false"),b=new ethers.Contract(a,abiSale,provider),h.yield(b.tokenAddress(),2);case 2:return f=h.yieldResult,$(".tokenAddressUI").html(f),$(".tokenAddressUIlnk").attr("href",tracker+"tokens/"+f),g=new ethers.Contract(f,abiToken,
provider),h.yield(g.name(),3);case 3:return e=h.yieldResult,$("#tokenNameUI").html(e),h.yield(g.symbol(),4);case 4:return tokenSymbolUI=h.yieldResult,$("#tokenSymbolUI").html(tokenSymbolUI),h.yield(g.decimals(),5);case 5:return tokenDecimalsUI=h.yieldResult,$("#tokenDecimalsUI").html(Number(tokenDecimalsUI)),h.yield(g.totalSupply(),6);case 6:return l=h.yieldResult,$("#tokenSupplyUI").html(Number(ethers.utils.formatUnits(l,tokenDecimalsUI)).toFixed(0)),h.yield(b.saleQuantity(),7);case 7:return c=h.yieldResult,
$("#quantityUI").html(Number(ethers.utils.formatUnits(c,tokenDecimalsUI))),h.yield(b.tokenPrice(),8);case 8:return priceUI=h.yieldResult,$("#priceUI").html(ethers.utils.formatEther(priceUI)),h.yield(b.refPercent(),9);case 9:k=h.yieldResult,$("#refPercentUI").html(Number(k)/10),getQR(a),h.jumpToEnd()}})}
function getQR(a){a=encodeURIComponent(a);$("#refqr").html('<img style="max-width: 80%" src="https://dappbuilder.org/php/qr.php?data='+a+'">');$("#refd").attr("href","https://dappbuilder.org/php/qr.php?data="+a)};