var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(a==Array.prototype||a==Object.prototype)return a;a[b]=d.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var d=$jscomp.propertyToPolyfillSymbol[b];if(null==d)return a[b];d=a[d];return void 0!==d?d:a[b]};$jscomp.polyfill=function(a,b,d,f){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,d,f):$jscomp.polyfillUnisolated(a,b,d,f))};
$jscomp.polyfillUnisolated=function(a,b,d,f){d=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var e=a[f];if(!(e in d))return;d=d[e]}a=a[a.length-1];f=d[a];b=b(f);b!=f&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,d,f){var e=a.split(".");a=1===e.length;f=e[0];f=!a&&f in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var m=0;m<e.length-1;m++){var c=e[m];if(!(c in f))return;f=f[c]}e=e[e.length-1];d=$jscomp.IS_SYMBOL_NATIVE&&"es6"===d?f[e]:null;b=b(d);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==d&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&(d=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+d+"$"+e),$jscomp.defineProperty(f,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(d){}return!1};
$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};
$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){var d=$jscomp.makeIterator(a),f=d.next();$jscomp.generator.ensureIteratorResultIsObject_(f);if(f.done)this.yieldResult=f.value,this.nextAddress=b;else return this.yieldAllIterator_=d,this.yield(f.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,d){d?this.finallyContexts_[d]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var d=this.finallyContexts_.splice(b||0)[0];if(d=this.abruptCompletion_=this.abruptCompletion_||d){if(d.isException)return this.jumpToErrorHandler_();void 0!=d.jumpTo&&this.finallyAddress_<d.jumpTo?(this.nextAddress=d.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(d){return{value:d,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,d){try{var f=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(f);if(!f.done)return this.context_.stop_(),f;var e=f.value}catch(m){return this.context_.yieldAllIterator_=null,this.context_.throw_(m),this.nextStep_()}this.context_.yieldAllIterator_=null;d.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var d=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(d,a.prototype);return d};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(f){return a.next(f)}function d(f){return a["throw"](f)}return new Promise(function(f,e){function m(c){c.done?f(c.value):Promise.resolve(c.value).then(b,d).then(m,e)}m(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.initSymbol=function(){};$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(m,c){this.$jscomp$symbol$id_=m;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:c})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",f=0,e=function(m){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(d+(m||"")+"_"+f++,m)};return e},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),d=0;d<b.length;d++){var f=$jscomp.global[b[d]];"function"===typeof f&&"function"!=typeof f.prototype[a]&&$jscomp.defineProperty(f.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function d(c){return c instanceof e?c:new e(function(h,g){h(c)})}if(a&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&"undefined"===typeof $jscomp.global.PromiseRejectionEvent)||!$jscomp.global.Promise||-1===$jscomp.global.Promise.toString().indexOf("[native code]")))return a;b.prototype.asyncExecute=function(c){if(null==this.batch_){this.batch_=[];var h=this;this.asyncExecuteFunction(function(){h.executeBatch_()})}this.batch_.push(c)};
var f=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(c){f(c,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var c=this.batch_;this.batch_=[];for(var h=0;h<c.length;++h){var g=c[h];c[h]=null;try{g()}catch(n){this.asyncThrow_(n)}}}this.batch_=null};b.prototype.asyncThrow_=function(c){this.asyncExecuteFunction(function(){throw c;})};var e=function(c){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var h=this.createResolveAndReject_();
try{c(h.resolve,h.reject)}catch(g){h.reject(g)}};e.prototype.createResolveAndReject_=function(){function c(n){return function(p){g||(g=!0,n.call(h,p))}}var h=this,g=!1;return{resolve:c(this.resolveTo_),reject:c(this.reject_)}};e.prototype.resolveTo_=function(c){if(c===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(c instanceof e)this.settleSameAsPromise_(c);else{a:switch(typeof c){case "object":var h=null!=c;break a;case "function":h=!0;break a;default:h=!1}h?this.resolveToNonPromiseObj_(c):
this.fulfill_(c)}};e.prototype.resolveToNonPromiseObj_=function(c){var h=void 0;try{h=c.then}catch(g){this.reject_(g);return}"function"==typeof h?this.settleSameAsThenable_(h,c):this.fulfill_(c)};e.prototype.reject_=function(c){this.settle_(2,c)};e.prototype.fulfill_=function(c){this.settle_(1,c)};e.prototype.settle_=function(c,h){if(0!=this.state_)throw Error("Cannot settle("+c+", "+h+"): Promise already settled in state"+this.state_);this.state_=c;this.result_=h;2===this.state_&&this.scheduleUnhandledRejectionCheck_();
this.executeOnSettledCallbacks_()};e.prototype.scheduleUnhandledRejectionCheck_=function(){var c=this;f(function(){if(c.notifyUnhandledRejection_()){var h=$jscomp.global.console;"undefined"!==typeof h&&h.error(c.result_)}},1)};e.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var c=$jscomp.global.CustomEvent,h=$jscomp.global.Event,g=$jscomp.global.dispatchEvent;if("undefined"===typeof g)return!0;"function"===typeof c?c=new c("unhandledrejection",{cancelable:!0}):
"function"===typeof h?c=new h("unhandledrejection",{cancelable:!0}):(c=$jscomp.global.document.createEvent("CustomEvent"),c.initCustomEvent("unhandledrejection",!1,!0,c));c.promise=this;c.reason=this.result_;return g(c)};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var c=0;c<this.onSettledCallbacks_.length;++c)m.asyncExecute(this.onSettledCallbacks_[c]);this.onSettledCallbacks_=null}};var m=new b;e.prototype.settleSameAsPromise_=function(c){var h=this.createResolveAndReject_();
c.callWhenSettled_(h.resolve,h.reject)};e.prototype.settleSameAsThenable_=function(c,h){var g=this.createResolveAndReject_();try{c.call(h,g.resolve,g.reject)}catch(n){g.reject(n)}};e.prototype.then=function(c,h){function g(l,q){return"function"==typeof l?function(u){try{n(l(u))}catch(v){p(v)}}:q}var n,p,r=new e(function(l,q){n=l;p=q});this.callWhenSettled_(g(c,n),g(h,p));return r};e.prototype["catch"]=function(c){return this.then(void 0,c)};e.prototype.callWhenSettled_=function(c,h){function g(){switch(n.state_){case 1:c(n.result_);
break;case 2:h(n.result_);break;default:throw Error("Unexpected state: "+n.state_);}}var n=this;null==this.onSettledCallbacks_?m.asyncExecute(g):this.onSettledCallbacks_.push(g);this.isRejectionHandled_=!0};e.resolve=d;e.reject=function(c){return new e(function(h,g){g(c)})};e.race=function(c){return new e(function(h,g){for(var n=$jscomp.makeIterator(c),p=n.next();!p.done;p=n.next())d(p.value).callWhenSettled_(h,g)})};e.all=function(c){var h=$jscomp.makeIterator(c),g=h.next();return g.done?d([]):new e(function(n,
p){function r(u){return function(v){l[u]=v;q--;0==q&&n(l)}}var l=[],q=0;do l.push(void 0),q++,d(g.value).callWhenSettled_(r(l.length-1),p),g=h.next();while(!g.done)})};return e},"es6","es3");$(".erc").html(" (BEP-20)");$(".changenet").each(function(){this.href+="tokensalewithreferral2/"});
var contractAddressMain="0xf3911e9D528e6171d15FDc3a345caDCC7979a91c",contractAddressTest="0x4a5a91B70E0357C2a5Ed5339Cbbf73B975450Eb8",contractTokenBuilder1Main="0x32D332487C8703D94C46F99E55b12D3BaAB45190",contractTokenBuilder1Test="0x32D332487C8703D94C46F99E55b12D3BaAB45190",contractTokenBuilder2Main="0x76079d9098b84cb28F2045c4fbC44EF6AAf5b0e7",contractTokenBuilder2Test="0xA61Bc01643CC20e722761E35e4C270BbF4c36A03",contractTokenBuilder3Main="0xeE4B8458741492455d7B9929F87342Aed9D4eF4b",contractTokenBuilder3Test=
"0xBFFEfDCC6275bd0D6703fCe006bB69e2a06Fb4B6",contractTokenBuilder4Main="0x592173bc112099c812216b62504a20aaeb38c679",contractTokenBuilder4Test="0x34e18d89B43d0Ef859896D54D024072785D8C48f",contractTokenBuilder5Main="0xF74A3016E6cb9C0f112F6F6ACf5e9A5dcFB13C66",contractTokenBuilder5Test="0xA56750825ad3c76b53731AFaa7C9Eb982Fb7F0C3",contractTokenBuilder1,contractTokenBuilder2,contractTokenBuilder3,contractTokenBuilder4,contractTokenBuilder5,builderCost,builderedge,contractThis,contractThisSign,contractThisToken,
contractThisTokenSign,balanceEth,thisDecimals,thisTokenAddress,thisAddress,thisSymbol,thisUnsold,thisUnsoldQty,available,thisBalance,thisHardcap,maxDecimals=18,dayms=86400,hourms=3600,abi=[{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"creator",type:"address"},{indexed:!0,internalType:"address",name:"contractAddress",type:"address"}],name:"ContractCreated",type:"event"},{inputs:[{internalType:"address",name:"_newBeneficiary",type:"address"}],name:"changeBeneficiary",outputs:[],stateMutability:"nonpayable",
type:"function"},{inputs:[{internalType:"uint256",name:"_newcost",type:"uint256"}],name:"changeCost",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_newedge",type:"uint256"}],name:"changeEdge",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"_newOwner",type:"address"}],name:"changeOwner",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"_tokenAddress",type:"address"},
{internalType:"uint256",name:"_rate",type:"uint256"},{internalType:"uint256",name:"_hardcap",type:"uint256"},{internalType:"uint256",name:"_ref",type:"uint256"},{internalType:"bool",name:"_free",type:"bool"}],name:"createTokenSale",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"payable",type:"function"},{stateMutability:"payable",type:"receive"},{inputs:[],name:"withdraw",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],stateMutability:"nonpayable",type:"constructor"},
{inputs:[],name:"beneficiary",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"builtFree",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"builtPaid",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"cost",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},
{inputs:[],name:"edge",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"myContracts",outputs:[{internalType:"address[]",name:"",type:"address[]"}],stateMutability:"view",type:"function"},{inputs:[],name:"owner",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalBuilt",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"}],
abiSale=[{inputs:[{internalType:"address",name:"_tokenAddress",type:"address"},{internalType:"uint256",name:"_rate",type:"uint256"},{internalType:"uint256",name:"_hardcap",type:"uint256"},{internalType:"uint256",name:"_ref",type:"uint256"},{internalType:"address",name:"_dappbuilderAddress",type:"address"},{internalType:"uint256",name:"_edge",type:"uint256"}],stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,inputs:[{indexed:!1,internalType:"address",name:"buyer",type:"address"},{indexed:!1,
internalType:"uint256",name:"amount",type:"uint256"}],name:"Contribution",type:"event"},{inputs:[{internalType:"address",name:"_ref",type:"address"}],name:"buyToken",outputs:[],stateMutability:"payable",type:"function"},{inputs:[{internalType:"uint256",name:"_qty",type:"uint256"}],name:"checkAmount",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"uint256",name:"_payment",type:"uint256"}],name:"checkChange",outputs:[{internalType:"uint256",
name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"uint256",name:"_payment",type:"uint256"}],name:"checkQty",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"dappbuilderEdge",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"hardcap",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},
{inputs:[],name:"owner",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"rate",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"",type:"address"}],name:"refEarnings",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"refPercent",outputs:[{internalType:"uint256",name:"",type:"uint256"}],
stateMutability:"view",type:"function"},{inputs:[],name:"refTotal",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"remaining",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"saleOn",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"view",type:"function"},{inputs:[],name:"tokenAddress",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",
type:"function"},{inputs:[],name:"totalRaised",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalSold",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"withdrawBNB",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"_address",type:"address"}],name:"withdrawCustomToken",outputs:[],stateMutability:"nonpayable",type:"function"},
{stateMutability:"payable",type:"receive"}],abiToken=[{inputs:[{internalType:"string",name:"_name",type:"string"},{internalType:"string",name:"_symbol",type:"string"},{internalType:"uint256",name:"_dec",type:"uint256"},{internalType:"uint256",name:"_supply",type:"uint256"},{internalType:"uint256",name:"_tax1",type:"uint256"},{internalType:"address",name:"_address1",type:"address"},{internalType:"uint256",name:"_tax2",type:"uint256"},{internalType:"address",name:"_address2",type:"address"},{internalType:"uint256",
name:"_deflation",type:"uint256"},{internalType:"uint256",name:"_minSupply",type:"uint256"},{internalType:"address",name:"_owner",type:"address"}],stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"owner",type:"address"},{indexed:!0,internalType:"address",name:"spender",type:"address"},{indexed:!1,internalType:"uint256",name:"value",type:"uint256"}],name:"Approval",type:"event"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"from",
type:"address"},{indexed:!0,internalType:"address",name:"to",type:"address"},{indexed:!1,internalType:"uint256",name:"value",type:"uint256"}],name:"Transfer",type:"event"},{inputs:[],name:"addressTax1",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"addressTax2",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"owner",type:"address"},{internalType:"address",
name:"spender",type:"address"}],name:"allowance",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"spender",type:"address"},{internalType:"uint256",name:"value",type:"uint256"}],name:"approve",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"owner",type:"address"}],name:"balanceOf",outputs:[{internalType:"uint256",name:"",type:"uint256"}],
stateMutability:"view",type:"function"},{inputs:[],name:"burnt",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"decimals",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"deflation",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"initialSupply",outputs:[{internalType:"uint256",name:"",type:"uint256"}],
stateMutability:"view",type:"function"},{inputs:[],name:"minSupply",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"name",outputs:[{internalType:"string",name:"",type:"string"}],stateMutability:"view",type:"function"},{inputs:[],name:"symbol",outputs:[{internalType:"string",name:"",type:"string"}],stateMutability:"view",type:"function"},{inputs:[],name:"tax1",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",
type:"function"},{inputs:[],name:"tax2",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalSupply",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalTax1",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalTax2",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",
type:"function"},{inputs:[{internalType:"address",name:"to",type:"address"},{internalType:"uint256",name:"value",type:"uint256"}],name:"transfer",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"address",name:"from",type:"address"},{internalType:"address",name:"to",type:"address"},{internalType:"uint256",name:"value",type:"uint256"}],name:"transferFrom",outputs:[{internalType:"bool",name:"",type:"bool"}],stateMutability:"nonpayable",
type:"function"}],abiTokenBuilder=[{inputs:[{internalType:"uint256",name:"_cost",type:"uint256"}],stateMutability:"nonpayable",type:"constructor"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"oldBeneficiary",type:"address"},{indexed:!0,internalType:"address",name:"newBeneficiary",type:"address"}],name:"BeneficiarySet",type:"event"},{anonymous:!1,inputs:[{indexed:!1,internalType:"uint256",name:"newCost",type:"uint256"}],name:"Cost",type:"event"},{anonymous:!1,inputs:[{indexed:!0,
internalType:"address",name:"oldOwner",type:"address"},{indexed:!0,internalType:"address",name:"newOwner",type:"address"}],name:"OwnerSet",type:"event"},{anonymous:!1,inputs:[{indexed:!0,internalType:"address",name:"tokenCreator",type:"address"},{indexed:!0,internalType:"address",name:"tokenAddress",type:"address"},{indexed:!1,internalType:"string",name:"name",type:"string"},{indexed:!1,internalType:"string",name:"symbol",type:"string"},{indexed:!1,internalType:"uint256",name:"totalSupply",type:"uint256"},
{indexed:!1,internalType:"uint8",name:"decimals",type:"uint8"}],name:"TokenCreated",type:"event"},{inputs:[],name:"beneficiary",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"newBeneficiary",type:"address"}],name:"changeBeneficiary",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[{internalType:"uint256",name:"_newcost",type:"uint256"}],name:"changeCost",outputs:[],stateMutability:"nonpayable",
type:"function"},{inputs:[{internalType:"address",name:"newOwner",type:"address"}],name:"changeOwner",outputs:[],stateMutability:"nonpayable",type:"function"},{inputs:[],name:"cost",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"string",name:"name",type:"string"},{internalType:"string",name:"symbol",type:"string"},{internalType:"uint256",name:"totalSupply",type:"uint256"},{internalType:"uint8",name:"decimals",type:"uint8"},
{internalType:"address",name:"to",type:"address"}],name:"createToken",outputs:[{internalType:"address",name:"tokenAddress",type:"address"}],stateMutability:"payable",type:"function"},{inputs:[{internalType:"address",name:"tokenAddress",type:"address"}],name:"getTokenData",outputs:[{internalType:"string",name:"name",type:"string"},{internalType:"string",name:"symbol",type:"string"},{internalType:"uint256",name:"totalSupply",type:"uint256"},{internalType:"uint256",name:"decimals",type:"uint256"}],stateMutability:"view",
type:"function"},{inputs:[],name:"myTokens",outputs:[{internalType:"address[]",name:"",type:"address[]"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",name:"",type:"address"},{internalType:"uint256",name:"",type:"uint256"}],name:"mytokens",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[],name:"owner",outputs:[{internalType:"address",name:"",type:"address"}],stateMutability:"view",type:"function"},{inputs:[{internalType:"address",
name:"",type:"address"}],name:"tokens",outputs:[{internalType:"string",name:"name",type:"string"},{internalType:"string",name:"symbol",type:"string"},{internalType:"uint256",name:"totalSupply",type:"uint256"},{internalType:"uint8",name:"decimals",type:"uint8"}],stateMutability:"view",type:"function"},{inputs:[],name:"totalBuilt",outputs:[{internalType:"uint256",name:"",type:"uint256"}],stateMutability:"view",type:"function"},{inputs:[],name:"withdraw",outputs:[],stateMutability:"nonpayable",type:"function"}];
function init(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return contract=new ethers.Contract(contractAddress,abi,provider),contractSign=contract.connect(signer),a.yield(contract.cost(),2);if(3!=a.nextAddress)return builderCost=a.yieldResult,$("#buildercost").html(ethers.utils.formatEther(builderCost)),a.yield(contract.edge(),3);builderEdge=a.yieldResult;$("#builderedge").html(Number(builderEdge)/10);makeTable();a.jumpToEnd()})}
function makeTable(){var a,b,d,f,e,m,c,h,g,n,p,r,l,q,u,v,t;return $jscomp.asyncExecutePromiseGeneratorProgram(function(k){switch(k.nextAddress){case 1:return a="",k.yield(contract.myContracts({from:myAddress}),2);case 2:b=k.yieldResult;if(!(0<b.length)){k.jumpTo(3);break}d=b;f=0;case 4:if(!(f<d.length)){k.jumpTo(3);break}e=d[f];m=new ethers.Contract(e,abiSale,provider);return k.yield(m.tokenAddress(),7);case 7:return c=k.yieldResult,k.yield(m.remaining(),8);case 8:return h=k.yieldResult,k.yield(m.checkQty(h),
9);case 9:return g=k.yieldResult,k.yield(m.saleOn(),10);case 10:return n=k.yieldResult,r=new ethers.Contract(c,abiToken,provider),k.yield(r.name(),11);case 11:return l=k.yieldResult,k.yield(r.symbol(),12);case 12:return q=k.yieldResult,k.yield(r.balanceOf(myAddress),13);case 13:return u=k.yieldResult,k.yield(r.allowance(myAddress,e),14);case 14:v=k.yieldResult;0<Number(g)&&n?(p="Active",Number(u)<Number(g)?p+=' <span class="err">Add tokens to your wallet!</span>':Number(v)<Number(g)&&(p+='<br><span class="err">Approve token sale!</span>')):
p="Finished";t=Number(f+1);a=a+'<div class="salerow" title="Click to open admin panel" onclick="admin(\''+e+'\')"><div class="saleno">'+t+'</div><div class="saleaddress">'+e+'</div><div class="saletoken">'+l+"("+q+')</div><div class="salestatus">'+p+"</div>";a+="</div>";f++;k.jumpTo(4);break;case 3:$("#mycontr").html(a),k.jumpToEnd()}})}
$("#mytokens").click(function(){var a,b,d,f,e,m,c,h,g,n,p,r;return $jscomp.asyncExecutePromiseGeneratorProgram(function(l){switch(l.nextAddress){case 1:return $("#mytoks").show(),curnet==mainnet||curnet==mainnetAlt?(contractTokenBuilder1=contractTokenBuilder1Main,contractTokenBuilder2=contractTokenBuilder2Main,contractTokenBuilder3=contractTokenBuilder3Main,contractTokenBuilder4=contractTokenBuilder4Main,contractTokenBuilder5=contractTokenBuilder5Main):curnet==testnet&&(contractTokenBuilder1=contractTokenBuilder1Test,
contractTokenBuilder2=contractTokenBuilder2Test,contractTokenBuilder3=contractTokenBuilder3Test,contractTokenBuilder4=contractTokenBuilder4Test,contractTokenBuilder5=contractTokenBuilder5Test),contractToken1=new ethers.Contract(contractTokenBuilder1,abiTokenBuilder,provider),contractToken2=new ethers.Contract(contractTokenBuilder2,abiTokenBuilder,provider),contractToken3=new ethers.Contract(contractTokenBuilder3,abiTokenBuilder,provider),contractToken4=new ethers.Contract(contractTokenBuilder4,abiTokenBuilder,
provider),contractToken5=new ethers.Contract(contractTokenBuilder5,abiTokenBuilder,provider),a="",l.yield(contractToken1.myTokens({from:myAddress}),2);case 2:b=l.yieldResult;if(b==[]){l.jumpTo(3);break}d=b;f=0;case 4:if(!(f<d.length)){l.jumpTo(3);break}e=d[f];m=new ethers.Contract(e,abiToken,provider);return l.yield(m.name(),7);case 7:return c=l.yieldResult,l.yield(m.symbol(),8);case 8:h=l.yieldResult;a=a+'<tr><td><a title="View on explorer" target="_blank" href="'+tracker+"token/"+e+'">'+e+"</a></td><td>"+
c+"</td><td>"+h+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+e+"')\">choose</span></td>";a+="</tr>";f++;l.jumpTo(4);break;case 3:return l.yield(contractToken2.myTokens({from:myAddress}),9);case 9:g=l.yieldResult;if(g==[]){l.jumpTo(10);break}d=g;f=0;case 11:if(!(f<d.length)){l.jumpTo(10);break}e=d[f];m=new ethers.Contract(e,abiToken,provider);return l.yield(m.name(),14);case 14:return c=l.yieldResult,l.yield(m.symbol(),15);case 15:h=l.yieldResult;a=a+'<tr><td><a title="View on explorer" target="_blank" href="'+
tracker+"token/"+e+'">'+e+"</a></td><td>"+c+"</td><td>"+h+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+e+"')\">choose</span></td>";a+="</tr>";f++;l.jumpTo(11);break;case 10:return l.yield(contractToken3.myTokens({from:myAddress}),16);case 16:n=l.yieldResult;if(n==[]){l.jumpTo(17);break}d=n;f=0;case 18:if(!(f<d.length)){l.jumpTo(17);break}e=d[f];m=new ethers.Contract(e,abiToken,provider);return l.yield(m.name(),21);case 21:return c=l.yieldResult,l.yield(m.symbol(),
22);case 22:h=l.yieldResult;a=a+'<tr><td><a title="View on explorer" target="_blank" href="'+tracker+"token/"+e+'">'+e+"</a></td><td>"+c+"</td><td>"+h+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+e+"')\">choose</span></td>";a+="</tr>";f++;l.jumpTo(18);break;case 17:return l.yield(contractToken4.myTokens({from:myAddress}),23);case 23:p=l.yieldResult;if(p==[]){l.jumpTo(24);break}d=p;f=0;case 25:if(!(f<d.length)){l.jumpTo(24);break}e=d[f];m=new ethers.Contract(e,abiToken,
provider);return l.yield(m.name(),28);case 28:return c=l.yieldResult,l.yield(m.symbol(),29);case 29:h=l.yieldResult;a=a+'<tr><td><a title="View on explorer" target="_blank" href="'+tracker+"token/"+e+'">'+e+"</a></td><td>"+c+"</td><td>"+h+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+e+"')\">choose</span></td>";a+="</tr>";f++;l.jumpTo(25);break;case 24:return l.yield(contractToken5.myTokens({from:myAddress}),30);case 30:r=l.yieldResult;if(r==[]){l.jumpTo(31);break}d=
r;f=0;case 32:if(!(f<d.length)){l.jumpTo(31);break}e=d[f];m=new ethers.Contract(e,abiToken,provider);return l.yield(m.name(),35);case 35:return c=l.yieldResult,l.yield(m.symbol(),36);case 36:h=l.yieldResult;a=a+'<tr><td><a title="View on explorer" target="_blank" href="'+tracker+"token/"+e+'">'+e+"</a></td><td>"+c+"</td><td>"+h+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+e+"')\">choose</span></td>";a+="</tr>";f++;l.jumpTo(32);break;case 31:$.ajax({type:"get",url:"/bsc/tokenwithbuyback/php/load.php",
data:{net:curnet,wallet:myAddress},contentType:"application/json; charset=utf-8",dataType:"json",cache:!1,success:function(q){return $jscomp.asyncExecutePromiseGeneratorProgram(function(u){$.each(q,function(v,t){var k,x,y;return $jscomp.asyncExecutePromiseGeneratorProgram(function(w){if(1==w.nextAddress)return k=new ethers.Contract(t.contract,abiToken,provider),w.yield(k.name(),2);if(3!=w.nextAddress)return x=w.yieldResult,w.yield(k.symbol(),3);y=w.yieldResult;a=a+'<tr><td><a title="View on explorer" target="_blank" href="'+
tracker+"token/"+t.contract+'">'+t.contract+"</a></td><td>"+x+"</td><td>"+y+'</td><td><span title="Choose this token" class="clickable" onclick="choose(\''+t.contract+"')\">choose</span></td>";a+="</tr>";$("#strHtmlTokens").html(a);w.jumpToEnd()})});u.jumpToEnd()})},error:function(q){}}),$("#strHtmlTokens").html(a),l.jumpToEnd()}})});function choose(a){$("#newtknaddress").val(a);$("#mytoks").hide();checkToken()}$("#newtknaddress").on("keyup input",checkToken);
function checkToken(){var a,b,d,f,e;return $jscomp.asyncExecutePromiseGeneratorProgram(function(m){switch(m.nextAddress){case 1:$("#tokendata").html("");$("#tokens").html("tokens");a=$("#newtknaddress").val();if(""==a||!ethers.utils.isAddress(a))return""==a?$("#tokendata").html(""):$("#tokendata").html('<span class="err">Error: check token address!</span>'),$("#tokens").html("tokens"),m["return"](!1);$("#errors").html("");m.setCatchFinallyBlocks(3);b=new ethers.Contract(a,abiToken,provider);return m.yield(b.name(),
5);case 5:return d=m.yieldResult,m.yield(b.symbol(),6);case 6:f=m.yieldResult;if(d&&f)return $("#tokendata").html('<span style="color: green">'+d+" ("+f+")</span>"),$("#tokens").html(f),m["return"](!0);$("#tokendata").html('<span class="err">Error: check token address!</span>');$("#tokens").html("tokens");return m["return"](!1);case 3:return e=m.enterCatchBlock(),console.log(e),$("#tokendata").html('<span class="err">Error: check token address!</span>'),$("#tokens").html("tokens"),m["return"](!1)}})}
function admin(a){var b,d,f,e,m,c,h,g,n,p,r,l,q,u,v,t;return $jscomp.asyncExecutePromiseGeneratorProgram(function(k){switch(k.nextAddress){case 1:return $("#admin").show(),$("#todo").html(""),$("#approveTokens").hide(),$("#addTokens").hide(),$("#thisAddr").html(a),$(".uiAddr").html(a),$("#uiAddrLnk").html(tracker+"address/"+a),$("#thisSaleAddress").html(a),$("#thisSaleAddress").attr("href",tracker+"address/"+a),$("#thisSaleAddress2").html(a),$("#thisSaleAddress2").attr("href",tracker+"address/"+a),
thisAddress=a,contractThis=new ethers.Contract(a,abiSale,provider),contractThisSign=contractThis.connect(signer),k.yield(contractThis.tokenAddress(),2);case 2:return thisTokenAddress=k.yieldResult,$("#thisTokenAddress").html(thisTokenAddress),$("#thisTokenAddress").attr("href",tracker+"token/"+thisTokenAddress),$(".tokenAddressUI").html(thisTokenAddress),$("#tokenAddressUIlnk").html(tracker+"token/"+thisTokenAddress),contractThisToken=new ethers.Contract(thisTokenAddress,abiToken,provider),contractThisTokenSign=
contractThisToken.connect(signer),k.yield(contractThisToken.name(),3);case 3:return b=k.yieldResult,$("#thisName").html(b),$("#tokenNameUI").html(b),k.yield(contractThisToken.symbol(),4);case 4:return thisSymbol=k.yieldResult,$(".thisSymbol").html(thisSymbol),k.yield(contractThisToken.decimals(),5);case 5:return thisDecimals=k.yieldResult,$("#thisDec").html(Number(thisDecimals)),$("#tokenDecimalsUI").html(Number(thisDecimals)),k.yield(contractThisToken.totalSupply(),6);case 6:return d=k.yieldResult,
$("#tokenSupplyUI").html(Number(ethers.utils.formatUnits(d,thisDecimals))),k.yield(contractThisToken.balanceOf(myAddress),7);case 7:return f=k.yieldResult,$("#tokenbalance").html(Number(ethers.utils.formatUnits(f,thisDecimals))),k.yield(contractThisToken.allowance(myAddress,thisAddress),8);case 8:return e=k.yieldResult,$("#allowance").html(Number(ethers.utils.formatUnits(e,thisDecimals))),k.yield(contractThis.owner(),9);case 9:return m=k.yieldResult,$("#thisOwner").html(m),k.yield(contractThis.rate(),
10);case 10:return c=k.yieldResult,h=ethers.utils.formatUnits(c,thisDecimals),$(".thisRate").html(h),g=1/Number(h),$(".thisPrice").html(g),k.yield(contractThis.hardcap(),11);case 11:return thisHardcap=k.yieldResult,$(".thisHardcap").html(ethers.utils.formatEther(thisHardcap)),k.yield(contractThis.checkQty(thisHardcap),12);case 12:return n=k.yieldResult,$(".thisQty").html(ethers.utils.formatUnits(n,thisDecimals)),k.yield(contractThis.refPercent(),13);case 13:return p=k.yieldResult,$(".thisRef").html(Number(p)/
10),k.yield(contractThis.refTotal(),14);case 14:return r=k.yieldResult,$("#thisRefTotal").html(ethers.utils.formatEther(r)),k.yield(contractThis.totalSold(),15);case 15:return l=k.yieldResult,$("#thisSold").html(ethers.utils.formatUnits(l,thisDecimals)),k.yield(contractThis.totalRaised(),16);case 16:return q=k.yieldResult,$("#thisRaised").html(ethers.utils.formatEther(q)),k.yield(contractThis.remaining(),17);case 17:return u=k.yieldResult,$("#thisRemaining").html(ethers.utils.formatEther(u)),$("#progress").attr("max",
thisHardcap),$("#progress").attr("value",q),k.yield(contractThis.checkQty(u),18);case 18:return thisUnsoldQty=k.yieldResult,$("#thisUnsoldQty").html(ethers.utils.formatUnits(thisUnsoldQty,thisDecimals)),k.yield(provider.getBalance(a),19);case 19:return thisBalance=k.yieldResult,available=ethers.utils.formatEther(thisBalance),$("#thisBalance").html(available),k.yield(contractThis.saleOn(),20);case 20:v=k.yieldResult,0<Number(thisUnsoldQty)&&v?(t="Active",Number(f)<Number(thisUnsoldQty)?(t+='<br><span class="err">Add tokens to your wallet!</span>',
$("#addTokens").show()):Number(e)<Number(thisUnsoldQty)&&(t+='<br><span class="err">Approve token sale!</span>',$("#approveTokens").show())):t="Finished",$("#thisStatus").html(t),curnet==testnet?($("#istest").html("true"),$("#switchbtnid").html("addTestBSC"),$("#switchbtn").html("To BSC Testnet")):($("#istest").html("false"),$("#switchbtnid").html("addMainBSC"),$("#switchbtn").html("To BSC Mainnet")),getQR(a),$("#uiAddr").attr("href","https://create.metaexchange.finance/bsc/tokensalewithreferral2/tokensale.html?id="+
thisAddress+"&net="+curnet),$("#uiAddr").html("https://create.metaexchange.finance/bsc/tokensalewithreferral2/tokensale.html?id="+thisAddress+"&net="+curnet),k.jumpToEnd()}})}$("#withdrawTok").click(withdrawTokens);
function withdrawTokens(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return(a=$("#toWithdrawTok").val())?b.yield(contractThisSign.withdrawCustomToken(String(a)),3):b.jumpTo(0);if(4!=b.nextAddress)return tx=b.yieldResult,b.yield(tx.wait(),4);admin(thisAddress);b.jumpToEnd()})}
$("#withdrawBnb").click(function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return 0<Number(thisBalance)?a.yield(contractThisSign.withdrawBNB(),3):a.jumpTo(0);if(4!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),4);admin(thisAddress);a.jumpToEnd()})});$("#addToken").click(function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){watchToken(thisTokenAddress,thisSymbol,thisDecimals);a.jumpToEnd()})});
function watchToken(a,b,d){return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){ethereum.request({method:"wallet_watchAsset",params:{type:"ERC20",options:{address:String(a),symbol:String(b),decimals:String(d)}}});f.jumpToEnd()})}
$("#buildbtnflat").click(function(){var a,b,d,f,e,m,c,h;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){switch(g.nextAddress){case 1:$("#errors").html("");if(!myAddress){g.jumpTo(0);break}return g.yield(provider.getBalance(myAddress),3);case 3:a=g.yieldResult;if(!(Number(a)>Number(builderCost))){$("#errors").html("Insufficient balance in your wallet! Contract creation cost is "+ethers.utils.formatEther(builderCost)+" BNB + network fees (gas)!");g.jumpTo(0);break}return g.yield(checkToken(),
5);case 5:b=g.yieldResult;d=$("#newrate").val();f=$("#newhardcap").val();if(!(b&&d&&0<Number(d)&&f&&0<Number(f))){checkToken();$("#errors").html("Error: fields are empty or incorrect!");g.jumpTo(0);break}$("#errors").html("");m=$("#newtknaddress").val();c=new ethers.Contract(m,abiToken,provider);return g.yield(c.decimals(),7);case 7:return h=g.yieldResult,(e=$("#newref").val())&&""!=e||(e=0),g.yield(contractSign.createTokenSale(String(m),String(ethers.utils.parseUnits(d,h)),String(ethers.utils.parseEther(f)),
String(10*Number(e)),!1,{value:builderCost}),8);case 8:return tx=g.yieldResult,g.yield(tx.wait(),9);case 9:init(),g.jumpToEnd()}})});
$("#buildbtnroyalty").click(function(){var a,b,d,f,e,m,c,h;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){switch(g.nextAddress){case 1:$("#errors").html("");if(!myAddress){g.jumpTo(0);break}return g.yield(provider.getBalance(myAddress),3);case 3:a=g.yieldResult;if(!(0<Number(a))){$("#errors").html("Insufficient balance in your wallet! Contract creation is free but you need some small amount to pay network fees (gas)!");g.jumpTo(0);break}return g.yield(checkToken(),5);case 5:b=g.yieldResult;
d=$("#newrate").val();f=$("#newhardcap").val();if(!(b&&d&&0<Number(d)&&f&&0<Number(f))){checkToken();$("#errors").html("Error: fields are empty or incorrect!");g.jumpTo(0);break}$("#errors").html("");m=$("#newtknaddress").val();c=new ethers.Contract(m,abiToken,provider);return g.yield(c.decimals(),7);case 7:return h=g.yieldResult,(e=$("#newref").val())&&""!=e||(e=0),g.yield(contractSign.createTokenSale(String(m),String(ethers.utils.parseUnits(d,h)),String(ethers.utils.parseEther(f)),String(10*Number(e)),
!0),8);case 8:return tx=g.yieldResult,g.yield(tx.wait(),9);case 9:init(),g.jumpToEnd()}})});$("#newrate").on("keyup input",function(){$("#tokenprice").html("");var a=$("#newrate").val();a&&""!=a&&0<Number(a)&&(a=1/Number(a),$("#tokenprice").html('<span style="color: green">1 token = '+Number(a)+"BNB</span>"));getQty()});$("#newhardcap").on("keyup input",getQty);
function getQty(){$("#quantity").html("");var a=$("#newhardcap").val(),b=$("#newrate").val();a&&""!=a&&b&&""!=b&&(a=Number(a)*Number(b),$("#quantity").html('<span style="color: green"> ~ '+Number(a)+"tokens</span>"))}function getQR(a){a=encodeURIComponent(a);$("#refqr").html('<img style="max-width: 80%" src="https://create.metaexchange.finance/php/qr.php?data='+a+'">');$("#refd").attr("href","https://create.metaexchange.finance/php/qr.php?data="+a)}
$("#copyaddress").on("click",function(){var a=$("<textarea>");$("body").append(a);a.val($("#thisTokenAddress").html()).select();document.execCommand("copy");a.remove()});$("#copysaleaddress").on("click",function(){var a=$("<textarea>");$("body").append(a);a.val($("#thisSaleAddress").html()).select();document.execCommand("copy");a.remove()});
$("#copysaleaddress2").on("click",function(){var a=$("<textarea>");$("body").append(a);a.val($("#thisSaleAddress2").html()).select();document.execCommand("copy");a.remove()});$("#copyUIlink").on("click",function(){var a=$("<textarea>");$("body").append(a);a.val($("#uiAddr").text()).select();document.execCommand("copy");a.remove()});
$("#approvePresale").click(function(){return $jscomp.asyncExecutePromiseGeneratorProgram(function(a){if(1==a.nextAddress)return a.yield(contractThisTokenSign.approve(String(thisAddress),String(thisUnsoldQty)),2);if(3!=a.nextAddress)return tx=a.yieldResult,a.yield(tx.wait(),3);admin(thisAddress);a.jumpToEnd()})});