$('.ethereum').html('Polygon (MATIC)');
$('.eth').html('MATIC');
$('.short').html('MATIC');
$('.ethhref').attr('href','https://dappbuilder.org/matic/');
var tokentracker;
var trackerMain = 'https://polygonscan.com/';
var trackerTest = 'https://mumbai.polygonscan.com/';
var mainnet = 0x89;
var testnet = 0x13881;
var mainnetname = 'Polygon (MATIC) Mainnet';
var testnetname = 'Polygon (MATIC) Mumbai Testnet';
var wrongnet = '<span class="err">Please use Polygon (MATIC) Mainnet or Mumbai Testnet</span>';